ci: Fix bpf-linker installation macOS
aya-rs/aya pull request #1022
Opened 2024-09-07 18:24 UTC by vadorovsky

LLVM 19 is not packaged in brew or any other package repository for macOS. Use LLVM tarball from Rust CI instead, to make sure we use the newest LLVM.

Also, install LLVM 19 on Linux for consistency.

2024-09-08 20:25 UTC, tyrone-wu commented
I finally got it to pass in a dum way. 😭
Here are the changed I made to make it pass:
In `test/integration-ebpf/src/test.rs`, I modified tracepoint program to:
```rust
#[tracepoint]
pub fn test_tracepoint(ctx: TracePointContext) -> u32 {
    // some arbitrary work
    let mut res = ctx.uid().wrapping_add(ctx.pid());
    for _ in 0..10_000 {
        res = res.wrapping_mul(123);
        res ^= (ctx.pid() << 3) ^ (ctx.uid() << 4);
        res = res.rotate_left(2);
        res = res.reverse_bits();
        res = res.swap_bytes();
        res = res.count_ones();
        unsafe { bpf_printk!(b"number %u", res) };
    }
    res
}
```
And in `test/integration-test/src/tests/info.rs`, I added this in between for `test_prog_stats()`:
```rust
...
prog.attach("syscalls", "sys_enter_bpf").unwrap();

// Executing bpf syscalls to trigger `sys_enter_bpf`
for _ in 0..5 {
        let _ = loaded_programs().collect::<Vec<_>>();
}

let test_prog = prog.info().unwrap();
...
```

I experimented with just one of the modifications above, and it wasn't enough to "pass", so it looks like a combination of both is needed for macos.

I'm fairly confident that macos is recording in milliseconds. I did some janky experiments (ik, this is a dum way to do this 😭), and `run_time` always outputs in 1,000,000s:
- https://github.com/tyrone-wu/aya/actions/runs/10762544881/job/29843006983
- https://github.com/tyrone-wu/aya/actions/runs/10762624479/job/29843187343

2024-09-09 14:22 UTC, tamird requested changes
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1022)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @dave-tucker and @vadorovsky)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M6pqF2FFEp0HjQ9Px):*
Please wrap at 72 columns
___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M86yo5HBanIGmxZIr):*
can we use the tarball from rust CI on linux too?
___
*[`.github/workflows/ci.yml` line 199 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M7CP2AbfsPxMKPufH:-O6M7CP2AbfsPxMKPufI:b39pp3j) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/.github/workflows/ci.yml#L199)):*
> ```YAML
>           submodules: recursive
> 
>       - uses: dtolnay/rust-toolchain@master
> ```

why did this need to move?
___
*[`.github/workflows/ci.yml` line 237 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M7Pu83TnID7yHaOL_:-O6M7Pu83TnID7yHaOLa:bul920p) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/.github/workflows/ci.yml#L237)):*
> ```YAML
>         # The clang shipped on macOS doesn't support BPF, so we need LLVM from brew.
>         #
>         # We also need the newest LLVM static libraries for bpf-linker, potentially newer than the
> ```

just remove this? we already talk about clang above.
___
*[`.github/workflows/ci.yml` line 252 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M72-k1qTUgPImR1f6:-O6M72-k1qTUgPImR1f7:b-djdw35) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/.github/workflows/ci.yml#L252)):*
> ```YAML
>           echo $(brew --prefix)/opt/llvm/bin >> $GITHUB_PATH
> 
>           # LLVM packaged in brew is usually too old for bpf-linker or any other package repository for macOS.
> ```

LLVM packaged in brew or any other package repository for macOS is usually too old for bpf-linker.



_Code quote:_
```YAML
LLVM packaged in brew is usually too old for bpf-linker or any other package repository for macOS.
```
___
*[`.github/workflows/ci.yml` line 272 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M7wtb3XPcaEiOXXmJ:-O6M7wtb3XPcaEiOXXmK:b-717cti) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/.github/workflows/ci.yml#L272)):*
> ```YAML
>         if: runner.os == 'macOS'
>         # NB: rustc doesn't ship libLLVM.so on macOS, so disable proxying (default feature). We also
>         # --force so that bpf-linker gets always relinked against the latest LLVM from the Rust CI
> ```

just say "latest LLVM downloaded above." to avoid rewriting this every time we change the implementation details
___
*[`.github/workflows/ci.yml` line 275 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M8SbGDfH23LigS-Nx:-O6M8SbH-OgapR551-G_:b-qvkyoa) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/.github/workflows/ci.yml#L275)):*
> ```YAML
>         # tarball.
>         env:
>           LLVM_SYS_191_PREFIX: /usr/local/lib/rustc-llvm
> ```

this is slightly unfortunate. I think if you download the rust LLVM tarball and add it to `GITHUB_PATH` *before* installing LLVM from brew then you could avoid it - the llvm_config from rust would win. WDYT?
___
*[`test/integration-ebpf/src/test.rs` line 37 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M8pl7C3EC61Wu5920:-O6M8pl7C3EC61Wu5921:bm7ptkb) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/test/integration-ebpf/src/test.rs#L37)):*
> ```XML
> pub fn test_tracepoint(ctx: TracePointContext) -> u32 {
>     // Some arbitrary work, to make the program running for some time and have
>     // a real `run_time` in `test_program_info`.
> ```

why do we care about this? I read [this comment](https://github.com/aya-rs/aya/pull/1022#issuecomment-2336814180) and it doesn't make any sense to me that "macos is recording in milliseconds" - nothing about these integration tests runs on macos at all, it's all on an emulated linux kernel.
___
*[`test/integration-test/src/tests/info.rs` line 218 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M8jTL48gBGXMbXUsx:-O6M8jTL48gBGXMbXUsy:bnft6w6) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/test/integration-test/src/tests/info.rs#L218)):*
> ```XML
>     prog.attach("syscalls", "sys_enter_bpf").unwrap();
> 
>     // Executing bpf syscalls to trigger `sys_enter_bpf`
> ```

it's not clear to me from this comment nor from the commit message why this addition was needed. help?


<!-- Sent from Reviewable.io -->

2024-09-09 15:57 UTC, tyrone-wu commented
> _[`test/integration-ebpf/src/test.rs` line 37 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M8pl7C3EC61Wu5920:-O6M8pl7C3EC61Wu5921:bm7ptkb) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/test/integration-ebpf/src/test.rs#L37)):_
> 
> > ```
> > pub fn test_tracepoint(ctx: TracePointContext) -> u32 {
> >     // Some arbitrary work, to make the program running for some time and have
> >     // a real `run_time` in `test_program_info`.
> > ```
> 
> why do we care about this? I read [this comment](https://github.com/aya-rs/aya/pull/1022#issuecomment-2336814180) and it doesn't make any sense to me that "macos is recording in milliseconds" - nothing about these integration tests runs on macos at all, it's all on an emulated linux kernel.

I shouldn't have worded it as "recording". The only thing I'm certain is that I observed `run_time_ns` having exactly 1,000,000 precision in macos. The test program performs enough work for running time to be non-zero.

> _[`test/integration-test/src/tests/info.rs` line 218 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M8jTL48gBGXMbXUsx:-O6M8jTL48gBGXMbXUsy:bnft6w6) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/test/integration-test/src/tests/info.rs#L218)):_
> 
> > ```
> >     prog.attach("syscalls", "sys_enter_bpf").unwrap();
> > 
> >     // Executing bpf syscalls to trigger `sys_enter_bpf`
> > ```
> 
> it's not clear to me from this comment nor from the commit message why this addition was needed. help?

I had `loaded_programs()` execute a couple bpf syscall times to trigger the test program. I tried just doing it once but macos wasn't passing, so I place it in loop.
Beforehand `prog.info()` was the one triggering the program.

---

Honestly I don't have a clue as to why macos runner is behaving like this. 😓
The only thing I could trace is possible https://github.com/torvalds/linux/blob/master/kernel/sched/clock.c#L62 overrided in https://github.com/torvalds/linux/blob/master/kernel/bpf/trampoline.c#L888? but that's just a guess...

2024-09-16 03:27 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1022)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @dave-tucker and @tamird)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M6pqF2FFEp0HjQ9Px):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Please wrap at 72 columns
</blockquote></details>

Done.
___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M86yo5HBanIGmxZIr):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can we use the tarball from rust CI on linux too?
</blockquote></details>

Done.

I also switched to upstream LLVM pre-release tarballs for clang (on Linux), so we can ditch apt.llvm.org all together.
___
*[`.github/workflows/ci.yml` line 199 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M7CP2AbfsPxMKPufH:-O6WVOvA4RbpO_oaGfWG:b-bydms9) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/.github/workflows/ci.yml#L199)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why did this need to move?
</blockquote></details>

Because I'm using `rustc --version` to find the latest commit SHA, which is then used for picking the latest tarball.
___
*[`.github/workflows/ci.yml` line 237 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M7Pu83TnID7yHaOL_:-O6Wm8HJCpeIKMdRWvJV:bo566yu) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/.github/workflows/ci.yml#L237)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

just remove this? we already talk about clang above.
</blockquote></details>

I would keep this line as it is, now it's on the top before installing libLLVM from Rust CI tarball. And it's good to have an explanation for `brew install llvm`.
___
*[`.github/workflows/ci.yml` line 252 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M72-k1qTUgPImR1f6:-O6Wm8a95qFYZX6tsTKz:b-lln520) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/.github/workflows/ci.yml#L252)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

LLVM packaged in brew or any other package repository for macOS is usually too old for bpf-linker.
</blockquote></details>

I just removed that sentence from here and moved the installation of libLLVM from Rust CI tarballs to a separate step, which runs both for Linux and macOS, with its own explanation.
___
*[`.github/workflows/ci.yml` line 272 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M7wtb3XPcaEiOXXmJ:-O6Wm91v2WVkut4Biu-v:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/.github/workflows/ci.yml#L272)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

just say "latest LLVM downloaded above." to avoid rewriting this every time we change the implementation details
</blockquote></details>

Done.
___
*[`.github/workflows/ci.yml` line 275 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M8SbGDfH23LigS-Nx:-O6Wm9KQ0gAiXtEOdEZ2:b-hlr3fe) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/.github/workflows/ci.yml#L275)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this is slightly unfortunate. I think if you download the rust LLVM tarball and add it to `GITHUB_PATH` *before* installing LLVM from brew then you could avoid it - the llvm_config from rust would win. WDYT?
</blockquote></details>

Actually the opposite worked - installing libLLVM.so at the end. Echoing to `GITHUB_PATH` is adding the path at the beginning of `PATH`.
___
*[`test/integration-test/src/tests/info.rs` line 218 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M8jTL48gBGXMbXUsx:-O6spljDC1gW2p_3RhmQ:b-y8x5nr) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/test/integration-test/src/tests/info.rs#L218)):*
<details><summary><i>Previously, tyrone-wu (Tyrone Wu) wrote…</i></summary><blockquote>

I had `loaded_programs()` execute a couple bpf syscall times to trigger the test program. I tried just doing it once but macos wasn't passing, so I place it in loop.
Beforehand `prog.info()` was the one triggering the program.

---

Honestly I don't have a clue as to why macos runner is behaving like this. 😓
The only thing I could trace is possible https://github.com/torvalds/linux/blob/master/kernel/sched/clock.c#L62 overrided in https://github.com/torvalds/linux/blob/master/kernel/bpf/trampoline.c#L888? but that doesn't feel right, and is just a guess...

</blockquote></details>

We definitely needs to do some root cause analysis here and have a clear explanations why do we need that. I think it would be great to try to reproduce the issue on QEMU on Linux host as well - maybe it's a virtualization-related issue in general. I have limited time for that this week, but I will try my best to spend at least a bit of time on it. Your help would be appreciated though, @tyrone-wu :slightly_smiling_face: 


<!-- Sent from Reviewable.io -->

2024-09-16 13:57 UTC, tamird requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1022)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @dave-tucker and @vadorovsky)

___
*[`.github/workflows/ci.yml` line 199 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M7CP2AbfsPxMKPufH:-O6v5rHQ747NJIlMoxga:b-g7gdgc) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/.github/workflows/ci.yml#L199)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

Because I'm using `rustc --version` to find the latest commit SHA, which is then used for picking the latest tarball.
</blockquote></details>

where you use `rustc --version` is *below* where this used to be.
___
*[`.github/workflows/ci.yml` line 229 at r4](https://reviewable.io/reviews/aya-rs/aya/1022#-O6v6Cot7wBGdY-9f3yY:-O6v6Cot7wBGdY-9f3yZ:b-lzim9u) ([raw file](https://github.com/aya-rs/aya/blob/40d2ad5d6d7bcc2dcd36c04468f09f550ed82ddf/.github/workflows/ci.yml#L229)):*
> ```YAML
>              .browser_download_url')
>           sudo mkdir -p /usr/local/lib/llvm-upstream
>           wget -q -O - $llvm_tarball_url | sudo tar -xJ --strip-components 1 \
> ```

sudo tar? why do we need to stick this in a location that requires sudo?
___
*[`.github/workflows/ci.yml` line 239 at r4](https://reviewable.io/reviews/aya-rs/aya/1022#-O6v6cseC5DhfN4wSxlm:-O6v6cseC5DhfN4wSxln:b-7m5jh1) ([raw file](https://github.com/aya-rs/aya/blob/40d2ad5d6d7bcc2dcd36c04468f09f550ed82ddf/.github/workflows/ci.yml#L239)):*
> ```YAML
>         # The tar shipped on macOS doesn't support --wildcards, so we need GNU tar.
>         #
>         # The clang shipped on macOS doesn't support BPF, so we need LLVM from brew.
> ```

why are we not getting this from the llvm releases like we do for linux? I see assets like `clang+llvm-17.0.6-arm64-apple-darwin22.0.tar.xz",`
___
*[`.github/workflows/ci.yml` line 247 at r4](https://reviewable.io/reviews/aya-rs/aya/1022#-O6v66I17T4w9Nu5F5o6:-O6v66I17T4w9Nu5F5o7:bssj79x) ([raw file](https://github.com/aya-rs/aya/blob/40d2ad5d6d7bcc2dcd36c04468f09f550ed82ddf/.github/workflows/ci.yml#L247)):*
> ```YAML
>           | grep -q ^/Library/Frameworks/Python.framework/Versions/' _ {} \; -exec rm -v {} \;
>           HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 \
>           brew install dpkg findutils gnu-tar llvm pkg-config qemu          
> ```

random whitespace
___
*[`.github/workflows/ci.yml` line 264 at r4](https://reviewable.io/reviews/aya-rs/aya/1022#-O6v6vU_DIcEGh-0M8qQ:-O6v6vU_DIcEGh-0M8qR:btc33y3) ([raw file](https://github.com/aya-rs/aya/blob/40d2ad5d6d7bcc2dcd36c04468f09f550ed82ddf/.github/workflows/ci.yml#L264)):*
> ```YAML
>             --header 'content-type: application/json' \
>             | jq -r '.sha')
>           sudo mkdir -p /usr/local/lib/rustc-llvm
> ```

please no sudo where it isn't needed


<!-- Sent from Reviewable.io -->

2024-09-17 02:23 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1022)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @dave-tucker and @tamird)

___
*[`.github/workflows/ci.yml` line 239 at r4](https://reviewable.io/reviews/aya-rs/aya/1022#-O6v6cseC5DhfN4wSxlm:-O6xmDUp8Ubth5uFYKl_:b-2d92my) ([raw file](https://github.com/aya-rs/aya/blob/40d2ad5d6d7bcc2dcd36c04468f09f550ed82ddf/.github/workflows/ci.yml#L239)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why are we not getting this from the llvm releases like we do for linux? I see assets like `clang+llvm-17.0.6-arm64-apple-darwin22.0.tar.xz",`
</blockquote></details>

Pre-releases don't have assets for macOS, here there are only tarballs for Linux: https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.0-rc4

But the stable releases have them, I just haven't noticed that before: https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.8

I will try to use the stable releases.


<!-- Sent from Reviewable.io -->

2024-09-17 18:31 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1022)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @dave-tucker and @tamird)

___
*[`.github/workflows/ci.yml` line 239 at r4](https://reviewable.io/reviews/aya-rs/aya/1022#-O6v6cseC5DhfN4wSxlm:-O70F39f-g4mwpJVflTW:b-s3iu2q) ([raw file](https://github.com/aya-rs/aya/blob/40d2ad5d6d7bcc2dcd36c04468f09f550ed82ddf/.github/workflows/ci.yml#L239)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Sounds good. I think 19.1.0 stable has been released.
</blockquote></details>

And they stopped attaching tarballs with binaries :facepalm: 

https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.0


<!-- Sent from Reviewable.io -->

2024-09-17 18:32 UTC, tamird reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1022)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @dave-tucker and @vadorovsky)

___
*[`.github/workflows/ci.yml` line 239 at r4](https://reviewable.io/reviews/aya-rs/aya/1022#-O6v6cseC5DhfN4wSxlm:-O70FVUT6OJ5poqWSIbj:b-tl60l8) ([raw file](https://github.com/aya-rs/aya/blob/40d2ad5d6d7bcc2dcd36c04468f09f550ed82ddf/.github/workflows/ci.yml#L239)):*
> The binaries can take a while to show up since they require some manual input.


<!-- Sent from Reviewable.io -->

2024-09-17 18:46 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1022)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @dave-tucker and @tamird)

___
*[`.github/workflows/ci.yml` line 199 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M7CP2AbfsPxMKPufH:-O70Hy3oA2WTMBg1_gYS:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/.github/workflows/ci.yml#L199)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

where you use `rustc --version` is *below* where this used to be.
</blockquote></details>

Done.
___
*[`.github/workflows/ci.yml` line 229 at r4](https://reviewable.io/reviews/aya-rs/aya/1022#-O6v6Cot7wBGdY-9f3yY:-O70I1XpCGTImHgSUjoM:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/40d2ad5d6d7bcc2dcd36c04468f09f550ed82ddf/.github/workflows/ci.yml#L229)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

sudo tar? why do we need to stick this in a location that requires sudo?
</blockquote></details>

Done.
___
*[`.github/workflows/ci.yml` line 239 at r4](https://reviewable.io/reviews/aya-rs/aya/1022#-O6v6cseC5DhfN4wSxlm:-O70I2Xe9iakIaqgr5iB:bz57j8y) ([raw file](https://github.com/aya-rs/aya/blob/40d2ad5d6d7bcc2dcd36c04468f09f550ed82ddf/.github/workflows/ci.yml#L239)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

> The binaries can take a while to show up since they require some manual input.
</blockquote></details>

I checked the older releases. In the latest 18.x there are macOS tarballs only for aarch64. There is no x86_64-apple-macos. https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.8

Which is a bummer. Same for 17.0.6. I think it's better to stick to brew in that case.
___
*[`.github/workflows/ci.yml` line 247 at r4](https://reviewable.io/reviews/aya-rs/aya/1022#-O6v66I17T4w9Nu5F5o6:-O70IYOQ6uzFFjt3mujd:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/40d2ad5d6d7bcc2dcd36c04468f09f550ed82ddf/.github/workflows/ci.yml#L247)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

random whitespace
</blockquote></details>

Done.
___
*[`.github/workflows/ci.yml` line 264 at r4](https://reviewable.io/reviews/aya-rs/aya/1022#-O6v6vU_DIcEGh-0M8qQ:-O70IZSV4nu1oKY_O7I3:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/40d2ad5d6d7bcc2dcd36c04468f09f550ed82ddf/.github/workflows/ci.yml#L264)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

please no sudo where it isn't needed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-17 22:23 UTC, tamird requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1022)* status: all files reviewed, 3 unresolved discussions (waiting on @dave-tucker, @tyrone-wu, and @vadorovsky)

___
*[`.github/workflows/ci.yml` line 239 at r4](https://reviewable.io/reviews/aya-rs/aya/1022#-O6v6cseC5DhfN4wSxlm:-O70JBYO6buCr23kx1y8:b-ul8jow) ([raw file](https://github.com/aya-rs/aya/blob/40d2ad5d6d7bcc2dcd36c04468f09f550ed82ddf/.github/workflows/ci.yml#L239)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

I checked the older releases. In the latest 18.x there are macOS tarballs only for aarch64. There is no x86_64-apple-macos. https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.8

Which is a bummer. Same for 17.0.6. I think it's better to stick to brew in that case.
</blockquote></details>

Let's document please!
___
*[`test/integration-ebpf/src/test.rs` line 37 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M8pl7C3EC61Wu5920:-O70JUZq0eILEvryjP00:bp17wzf) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/test/integration-ebpf/src/test.rs#L37)):*
<details><summary><i>Previously, tyrone-wu (Tyrone Wu) wrote…</i></summary><blockquote>

I shouldn't have worded it as "recording". The only thing I'm certain is that I observed `run_time_ns` having exactly 1,000,000 precision in macos. The test program performs enough work for running time to be non-zero.
</blockquote></details>

We need to document the voodoo we're doing here.
___
*[`test/integration-test/src/tests/info.rs` line 218 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M8jTL48gBGXMbXUsx:-O70JYO15ltuHnJnr7Tq:bp17wzf) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/test/integration-test/src/tests/info.rs#L218)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

We definitely needs to do some root cause analysis here and have a clear explanations why do we need that. I think it would be great to try to reproduce the issue on QEMU on Linux host as well - maybe it's a virtualization-related issue in general. I have limited time for that this week, but I will try my best to spend at least a bit of time on it. Your help would be appreciated though, @tyrone-wu :slightly_smiling_face:
</blockquote></details>

We need to document the voodoo we're doing here.


<!-- Sent from Reviewable.io -->

2024-09-22 17:07 UTC, tamird reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1022)* status: all files reviewed, 2 unresolved discussions (waiting on @dave-tucker, @tyrone-wu, and @vadorovsky)



<!-- Sent from Reviewable.io -->

2024-09-22 17:57 UTC, tyrone-wu commented
@vadorovsky I would also add that specifically the `hvf` qemu accelerator is causing the millisecond resolution to occur.

2024-09-25 10:26 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1022)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @dave-tucker and @tamird)

___
*[`.github/workflows/ci.yml` line 239 at r4](https://reviewable.io/reviews/aya-rs/aya/1022#-O6v6cseC5DhfN4wSxlm:-O7Hztpt8QeX1sWgHbGT:b-2yopmv) ([raw file](https://github.com/aya-rs/aya/blob/40d2ad5d6d7bcc2dcd36c04468f09f550ed82ddf/.github/workflows/ci.yml#L239)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Let's document please!
</blockquote></details>

Done. Unfortunately the LLVM binary tarballs for macOS are broken, so I'm sticking to brew. Let me know if you find the explanation in the comment sufficient.

See https://github.com/llvm/llvm-project/issues/92260#issuecomment-2367474348
___
*[`test/integration-ebpf/src/test.rs` line 37 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M8pl7C3EC61Wu5920:-O7T0Ay_72O73TFxIdfV:b-7mvsxa) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/test/integration-ebpf/src/test.rs#L37)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

We need to document the voodoo we're doing here.
</blockquote></details>

Done, tried my best to explain that.
___
*[`test/integration-test/src/tests/info.rs` line 218 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M8jTL48gBGXMbXUsx:-O7T0K2k3cGTruQ_0XNU:b4amdd5) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/test/integration-test/src/tests/info.rs#L218)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

We need to document the voodoo we're doing here.
</blockquote></details>

Done and I also simplified the voodoo.

We don't need the loop, executing `loaded_programs()` (or we could do anything triggering the BPF syscall) followed by a short sleep is sufficient.


<!-- Sent from Reviewable.io -->

2024-09-25 13:24 UTC, tamird approved these changes
> Reviewed 2 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1022)* status: all files reviewed, 7 unresolved discussions (waiting on @dave-tucker, @tyrone-wu, and @vadorovsky)

___
*[`.github/workflows/ci.yml` line 202 at r9](https://reviewable.io/reviews/aya-rs/aya/1022#-O7dKCmP1fvKaXNiWbS-:-O7dKCmP1fvKaXNiWbS0:b-npbyh3) ([raw file](https://github.com/aya-rs/aya/blob/5b2900869112990eb8478f2700bd067b20fa7d3d/.github/workflows/ci.yml#L202)):*
> ```YAML
>         if: runner.os == 'Linux'
>         # ubuntu-22.04 comes with clang 14[0] which doesn't include support for signed and 64bit
>         # enum values which was added in clang 15[1].
> ```

we should keep this blurb as well (else it's not clear why we can't use distro-packaged clang)

i believe if we move to ubuntu-24.04 (recently GA) we can go back to distro clang
___
*[`.github/workflows/ci.yml` line 229 at r9](https://reviewable.io/reviews/aya-rs/aya/1022#-O7dK6PS913qTZ53shHs:-O7dK6PS913qTZ53shHt:bmbfwh) ([raw file](https://github.com/aya-rs/aya/blob/5b2900869112990eb8478f2700bd067b20fa7d3d/.github/workflows/ci.yml#L229)):*
> ```YAML
>         # The tar shipped on macOS doesn't support --wildcards, so we need GNU tar.
>         #
>         # The clang shipped on macOS doesn't support BPF, so we need LLVM from brew.
> ```

we still need this sentence else it isn't clear why we can't use the system's clang
___
*[`.github/workflows/ci.yml` line 248 at r9](https://reviewable.io/reviews/aya-rs/aya/1022#-O7dKipS9Q48aFU6Ksoa:-O7dKipS9Q48aFU6Ksob:bd6sssg) ([raw file](https://github.com/aya-rs/aya/blob/929c9e3309061966d1d7e5d614994d32c4377b23/.github/workflows/ci.yml#L248)):*
> ```YAML
>         # of clang. Version parity with LLVM shipped with Rust nightly is not
>         # required for clang, as it is only used for compiling eBPF programs
>         # written in C for integration tests. But we still prefer using a
> ```

This last sentence is sounding alarm in my head: we should try to use the oldest version we can reasonably get our hands on - we don't want to force our users to do this same thing. If it works with distro/mac/brew then we should assert that here.
___
*[`.github/workflows/ci.yml` line 330 at r9](https://reviewable.io/reviews/aya-rs/aya/1022#-O7dJzcXEyfH4_GbIqx-:-O7dJzcXEyfH4_GbIqx0:bxwj5hn) ([raw file](https://github.com/aya-rs/aya/blob/929c9e3309061966d1d7e5d614994d32c4377b23/.github/workflows/ci.yml#L330)):*
> ```YAML
>         run: find test/.tmp -name 'vmlinuz-*' | xargs -t cargo xtask integration-test vm
> 
>       - name: Setup tmate session
> ```

remove before merging
___
*[`test/integration-ebpf/src/test.rs` line 39 at r9](https://reviewable.io/reviews/aya-rs/aya/1022#-O7dL5mJDCAHfr1qzQ0J:-O7dL5mJDCAHfr1qzQ0K:b1i0bh5) ([raw file](https://github.com/aya-rs/aya/blob/929c9e3309061966d1d7e5d614994d32c4377b23/test/integration-ebpf/src/test.rs#L39)):*
> ```XML
>     // resolved in milliseconds instead of nanoseconds.
>     // Therefore, to make sure that we receive a non-zero `run_time` in
>     // `test_program_info` when running on macOS, make some arbitrary work
> ```

nit: s/make/do/
___
*[`test/integration-test/src/tests/info.rs` line 218 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M8jTL48gBGXMbXUsx:-O7dLT56CTfiaZBrE_NY:bs8bzjc) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/test/integration-test/src/tests/info.rs#L218)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

Done and I also simplified the voodoo.

We don't need the loop, executing `loaded_programs()` (or we could do anything triggering the BPF syscall) followed by a short sleep is sufficient.
</blockquote></details>

can you fix the grammar?
___
*[`test/integration-test/src/tests/info.rs` line 222 at r9](https://reviewable.io/reviews/aya-rs/aya/1022#-O7dLUfw0D7K4oMcyy28:-O7dLUfw0D7K4oMcyy29:b7d7e2s) ([raw file](https://github.com/aya-rs/aya/blob/929c9e3309061966d1d7e5d614994d32c4377b23/test/integration-test/src/tests/info.rs#L222)):*
> ```XML
>     // execute.
>     let _ = loaded_programs().collect::<Vec<_>>();
>     std::thread::sleep(std::time::Duration::from_millis(100));
> ```

100 millis! how about 10?


<!-- Sent from Reviewable.io -->

2024-09-25 14:55 UTC, tamird reviewed
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1022)* status: all files reviewed, 4 unresolved discussions (waiting on @dave-tucker and @vadorovsky)



<!-- Sent from Reviewable.io -->

2024-09-25 15:16 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1022)* status: all files reviewed, 4 unresolved discussions (waiting on @dave-tucker and @tamird)

___
*[`.github/workflows/ci.yml` line 202 at r9](https://reviewable.io/reviews/aya-rs/aya/1022#-O7dKCmP1fvKaXNiWbS-:-O7dXoRJ8qi_Ua8mar6H:b-p2zcxn) ([raw file](https://github.com/aya-rs/aya/blob/5b2900869112990eb8478f2700bd067b20fa7d3d/.github/workflows/ci.yml#L202)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

we should keep this blurb as well (else it's not clear why we can't use distro-packaged clang)

i believe if we move to ubuntu-24.04 (recently GA) we can go back to distro clang
</blockquote></details>

Do you mean the blurb about lack of signed enum support in clang 14? Do you mind if I rather add it in the "Install LLVM" step? I can move it before the "Install prerequisites" steps, so the explanation would come first before any packages are installed.
___
*[`.github/workflows/ci.yml` line 229 at r9](https://reviewable.io/reviews/aya-rs/aya/1022#-O7dK6PS913qTZ53shHs:-O7d_Hhi6kADATcmPi4y:b-p6jd9u) ([raw file](https://github.com/aya-rs/aya/blob/5b2900869112990eb8478f2700bd067b20fa7d3d/.github/workflows/ci.yml#L229)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

we still need this sentence else it isn't clear why we can't use the system's clang
</blockquote></details>

As mentioned above, if we move the "Install LLVM" step up, we won't have to mention it twice.
___
*[`.github/workflows/ci.yml` line 248 at r9](https://reviewable.io/reviews/aya-rs/aya/1022#-O7dKipS9Q48aFU6Ksoa:-O7d_k9P-bhy4cu-obNd:bq74hut) ([raw file](https://github.com/aya-rs/aya/blob/929c9e3309061966d1d7e5d614994d32c4377b23/.github/workflows/ci.yml#L248)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

This last sentence is sounding alarm in my head: we should try to use the oldest version we can reasonably get our hands on - we don't want to force our users to do this same thing. If it works with distro/mac/brew then we should assert that here.
</blockquote></details>

Fair, that's a good point. I will try using the LLVM 15 tarball on Linux and stick to brew on macOS.
___
*[`test/integration-ebpf/src/test.rs` line 39 at r9](https://reviewable.io/reviews/aya-rs/aya/1022#-O7dL5mJDCAHfr1qzQ0J:-O7dd6E37kh3lixcn3sZ:bb6un1j) ([raw file](https://github.com/aya-rs/aya/blob/929c9e3309061966d1d7e5d614994d32c4377b23/test/integration-ebpf/src/test.rs#L39)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: s/make/do/
</blockquote></details>

Done
___
*[`test/integration-test/src/tests/info.rs` line 218 at r1](https://reviewable.io/reviews/aya-rs/aya/1022#-O6M8jTL48gBGXMbXUsx:-O7dciBfCCRDBdVslIG7:bagndbx) ([raw file](https://github.com/aya-rs/aya/blob/19f30d9ff126c06b6647f193079a10e99194b4a8/test/integration-test/src/tests/info.rs#L218)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you fix the grammar?
</blockquote></details>

How is it now?
___
*[`test/integration-test/src/tests/info.rs` line 222 at r9](https://reviewable.io/reviews/aya-rs/aya/1022#-O7dLUfw0D7K4oMcyy28:-O7dkF_W74-1GeefKSCP:b51krku) ([raw file](https://github.com/aya-rs/aya/blob/929c9e3309061966d1d7e5d614994d32c4377b23/test/integration-test/src/tests/info.rs#L222)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

100 millis! how about 10?
</blockquote></details>

10 was still flaky, but 20 seems to work


<!-- Sent from Reviewable.io -->

2024-09-25 17:27 UTC, tamird reviewed
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1022)* status: all files reviewed, 3 unresolved discussions (waiting on @dave-tucker and @vadorovsky)

___
*[`.github/workflows/ci.yml` line 202 at r9](https://reviewable.io/reviews/aya-rs/aya/1022#-O7dKCmP1fvKaXNiWbS-:-O7dkZS16N3i_PTuizfH:b-pi87jn) ([raw file](https://github.com/aya-rs/aya/blob/5b2900869112990eb8478f2700bd067b20fa7d3d/.github/workflows/ci.yml#L202)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

Do you mean the blurb about lack of signed enum support in clang 14? Do you mind if I rather add it in the "Install LLVM" step? I can move it before the "Install prerequisites" steps, so the explanation would come first before any packages are installed.
</blockquote></details>

Yeah, the blurb that explains why we need to download LLVM binaries at all, but see #1039 - I don't think we need to do this anymore.
___
*[`.github/workflows/ci.yml` line 229 at r9](https://reviewable.io/reviews/aya-rs/aya/1022#-O7dK6PS913qTZ53shHs:-O7eD-Xb0lGUkNy07euY:b-2h57yg) ([raw file](https://github.com/aya-rs/aya/blob/5b2900869112990eb8478f2700bd067b20fa7d3d/.github/workflows/ci.yml#L229)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

As mentioned above, if we move the "Install LLVM" step up, we won't have to mention it twice.
</blockquote></details>

Not sure I follow. The reasons are different on mac and linux. On mac I believe the issue is that system clang can't target bpfel.
___
*[`.github/workflows/ci.yml` line 248 at r9](https://reviewable.io/reviews/aya-rs/aya/1022#-O7dKipS9Q48aFU6Ksoa:-O7eD8sz5x6BZTbVnKxU:b-j5x29k) ([raw file](https://github.com/aya-rs/aya/blob/929c9e3309061966d1d7e5d614994d32c4377b23/.github/workflows/ci.yml#L248)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

Fair, that's a good point. I will try using the LLVM 15 tarball on Linux and stick to brew on macOS.
</blockquote></details>

No need for tarballs! See #1039.


<!-- Sent from Reviewable.io -->

2024-09-25 17:55 UTC, tamird reviewed
@tyrone-wu heads up: I just remove the `run_time` assertion in https://github.com/aya-rs/aya/pull/1039/commits/087e10ae027b4f66112b272acf1544e733b0c19f. Feel free to reland it on its own, it need not block this PR imo.

> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1022#-:-O7eJ_o-0fdEsmahNGRA:bonitbd)* status: all files reviewed, 3 unresolved discussions (waiting on @dave-tucker and @vadorovsky)



<!-- Sent from Reviewable.io -->

2024-09-25 18:03 UTC, tamird commented
I rebased this on #1039 and reduced the scope - it now *only* fetches libLLVM from rust CI. See the updated commit message. Hope this is OK!

2024-09-25 18:23 UTC, tamird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1022#-:-O7eQ2sQ-vPCiohSGdw3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dave-tucker)



<!-- Sent from Reviewable.io -->

2024-09-25 18:25 UTC, tamird approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1022)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dave-tucker)



<!-- Sent from Reviewable.io -->

2024-09-25 18:39 UTC, merged