aya: add feature probing program types
aya-rs/aya pull request #1063
Opened 2024-10-19 20:15 UTC by tyrone-wu

Removed `aya-obj` to `obj` alias since this gave 3 ways to imports/use `aya-obj` objects, which was starting to get a little confusing. 😵

---

Add API for probing whether kernel supports a program type. Also add `const fn bpf_insn::new(...)` so that common bpf instructions are not re-computed every time from `copy_instructions()`.

Assertions for `LircMode2` and `Lsm` are disabled because they require certain kernel configs to be enabled, which are not by default in VM integration tests.

---

I verified that the `feature_probe_programs` integration test passes on my machine using ubuntu mainline kernel versions:
- `4. [ 4, 7, 8, 9, 10, 13, 14, 15, 17, 18, 19, 20 ]`
- `5. [ 2, 3, 5, 6, 7, 9, 14 ]`
- `6. [ 1, 4, 9 ]`

I haven't been able to test with `v4.1` because it was giving `stat(/sys/fs/bpf) failed Caused by: ENOENT: No such file or directory` errors. :P

2025-03-01 13:32 UTC, tamird commented
@tyrone-wu can you rebase this please?

2025-03-03 17:56 UTC, tamird commented
@tyrone-wu I rebased this for you.

2025-03-03 18:27 UTC, tamird reviewed
> Reviewed 1 of 51 files at r1, 38 of 47 files at r2, 7 of 12 files at r4, 9 of 11 files at r7, 3 of 6 files at r8, 1 of 1 files at r9, 2 of 8 files at r10, 1 of 4 files at r12, 6 of 9 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1063)* status: 48 of 51 files reviewed, 5 unresolved discussions (waiting on @alessandrod)

___
*[`aya/Cargo.toml` line 25 at r13](https://reviewable.io/reviews/aya-rs/aya/1063#-OKSEwvcDJz98jlCFFmQ:-OKSEwvcDJz98jlCFFmR:b6ytbxv) ([raw file](https://github.com/aya-rs/aya/blob/f4df1a99190eea3381633438b5265626b14c60d3/aya/Cargo.toml#L25)):*
> ```TOML
> log = { workspace = true }
> object = { workspace = true, features = ["elf", "read_core", "std", "write"] }
> once_cell = { workspace = true, features = ["race"] }
> ```

back this out? see comment in `info.rs`
___
*[`aya/src/programs/info.rs` line 11 at r13](https://reviewable.io/reviews/aya-rs/aya/1063#-OKSEtoz9u5N_xlmUeLa:-OKSEtoz9u5N_xlmUeLb:b8ygn4c) ([raw file](https://github.com/aya-rs/aya/blob/f4df1a99190eea3381633438b5265626b14c60d3/aya/src/programs/info.rs#L11)):*
> ```XML
> 
> use aya_obj::generated::{bpf_prog_info, bpf_prog_type};
> use once_cell::race::OnceBool;
> ```

why can't we use std::cell::OnceCell here?
___
*[`aya/src/programs/info.rs` line 125 at r13](https://reviewable.io/reviews/aya-rs/aya/1063#-OKSFW_u09dFWpJ2YhQq:-OKSFW_u09dFWpJ2YhQr:b-n8d5au) ([raw file](https://github.com/aya-rs/aya/blob/f4df1a99190eea3381633438b5265626b14c60d3/aya/src/programs/info.rs#L125)):*
> ```XML
>         } else {
>             Ok(None)
>         }
> ```

this transformation doesn't look right to me. What am I missing?



_Code quote:_
```XML
    pub fn map_ids(&self) -> Result<Option<Vec<u32>>, ProgramError> {
        if self.0.nr_map_ids > 0 {
            let mut map_ids = vec![0u32; self.0.nr_map_ids as usize];
            bpf_prog_get_info_by_fd(self.fd()?.as_fd(), &mut map_ids)?;
            return Ok(Some(map_ids));
        }

        static CACHE: OnceBool = OnceBool::new();
        if CACHE.get_or_init(|| matches!(is_prog_info_map_ids_supported(), Ok(true))) {
            Ok(Some(vec![]))
        } else {
            Ok(None)
        }
```
___
*[`aya/src/programs/info.rs` line 152 at r13](https://reviewable.io/reviews/aya-rs/aya/1063#-OKSFa2A0O0XaoFOO8QW:-OKSFa2A0O0XaoFOO8QX:b-wy0jn4) ([raw file](https://github.com/aya-rs/aya/blob/f4df1a99190eea3381633438b5265626b14c60d3/aya/src/programs/info.rs#L152)):*
> ```XML
>     pub fn gpl_compatible(&self) -> Option<bool> {
>         if self.0.gpl_compatible() != 0 {
>             return Some(true);
> ```

the previous code checked both conditions, why is it ok to short circuit now?
___
*[`test/integration-test/src/tests/feature_probe.rs` line 199 at r7](https://reviewable.io/reviews/aya-rs/aya/1063#-OKS9Lb47sX5B1BD7YVF:-OKS9Lb47sX5B1BD7YVG:b447s1) ([raw file](https://github.com/aya-rs/aya/blob/69b42f4745a7b32a5c96dd6451794c25b698e1ab/test/integration-test/src/tests/feature_probe.rs#L199)):*
> ```XML
> }
> 
> // Back-to-back calls can be flaky and return `EPERM`.
> ```

That's weird. Citation?


<!-- Sent from Reviewable.io -->

2025-03-24 15:24 UTC, tamird reviewed
> Reviewed 2 of 12 files at r14, 1 of 4 files at r15, 7 of 9 files at r16, 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1063)* status: 49 of 51 files reviewed, 1 unresolved discussion (waiting on @alessandrod and @tyrone-wu)



<!-- Sent from Reviewable.io -->

2025-03-24 16:01 UTC, tyrone-wu reviewed
Sorry for incredibly late update. will try to fix up some stuff by the end of today.

> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1063#-:-OM7sHhC0MSGQ8cmX5fR:b-7giux6)* status: 49 of 51 files reviewed, 1 unresolved discussion (waiting on @alessandrod and @tamird)

___
*[`aya/src/programs/info.rs` line 11 at r13](https://reviewable.io/reviews/aya-rs/aya/1063#-OKSEtoz9u5N_xlmUeLa:-OM7YuVf3GSAG3rqFk_U:b-vz5y0u) ([raw file](https://github.com/aya-rs/aya/blob/f4df1a99190eea3381633438b5265626b14c60d3/aya/src/programs/info.rs#L11)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why can't we use std::cell::OnceCell here?
</blockquote></details>

`std::cell::OnceCell` + `thread_local!` could also work too, but the data won't be shared/accessed between threads if used in a multi-thread context. each thread would just keep track of their own initialization.
from my understanding, `OnceBool` uses `LazyLock` underneath with some minor optimizations for representing the `bool`, however it requires the cargo feature race from once_cell.
___
*[`aya/src/programs/info.rs` line 125 at r13](https://reviewable.io/reviews/aya-rs/aya/1063#-OKSFW_u09dFWpJ2YhQq:-OM7nT88BPaYVRV6e3MS:br3g0t2) ([raw file](https://github.com/aya-rs/aya/blob/f4df1a99190eea3381633438b5265626b14c60d3/aya/src/programs/info.rs#L125)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this transformation doesn't look right to me. What am I missing?
</blockquote></details>

`nr_map_ids = 0` could mean either: there's no maps, or it wasn't filled meaning that the feature isn't available.
If not zero, it short-circuits to get the map ids. But if zero, then it checks whether there truely is no maps used in the program.
___
*[`aya/src/programs/info.rs` line 152 at r13](https://reviewable.io/reviews/aya-rs/aya/1063#-OKSFa2A0O0XaoFOO8QW:-OM7pP3aDI_CkUVAkJuo:b3bgjpp) ([raw file](https://github.com/aya-rs/aya/blob/f4df1a99190eea3381633438b5265626b14c60d3/aya/src/programs/info.rs#L152)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

the previous code checked both conditions, why is it ok to short circuit now?
</blockquote></details>

I used the same short circuit logic from `map_ids` here as well. If zero, then it'll need to perform additional check to see if it's non-GPL or unavailable.
___
*[`test/integration-test/src/tests/feature_probe.rs` line 199 at r7](https://reviewable.io/reviews/aya-rs/aya/1063#-OKS9Lb47sX5B1BD7YVF:-OM7rN4493EukehabIkp:b62hdkf) ([raw file](https://github.com/aya-rs/aya/blob/69b42f4745a7b32a5c96dd6451794c25b698e1ab/test/integration-test/src/tests/feature_probe.rs#L199)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

That's weird. Citation?
</blockquote></details>

The issue I im running into was related to my own weird env setup. I'll revert this. 🙃


<!-- Sent from Reviewable.io -->

2025-03-24 18:19 UTC, tamird reviewed
> Reviewed 1 of 4 files at r19, 6 of 7 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1063)* status: 49 of 51 files reviewed, 3 unresolved discussions (waiting on @alessandrod)

___
*[`test/integration-test/src/tests/feature_probe.rs` line 8 at r20](https://reviewable.io/reviews/aya-rs/aya/1063#-OM8N-iv9jUIAORINYGx:-OM8N-iv9jUIAORINYGy:b-f9y1vw) ([raw file](https://github.com/aya-rs/aya/blob/3ace956c5bd57f431f45e633530b24a16ea7eab6/test/integration-test/src/tests/feature_probe.rs#L8)):*
> ```XML
> use aya::{maps::MapType, programs::ProgramType, sys::feature_probe::*, util::KernelVersion};
> 
> // TODO: Enable certain CONFIG_* options when compiling the image for VM tests.
> ```

remove this, it isn't actionable. what is "certain"?
___
*[`test/integration-test/src/tests/feature_probe.rs` line 112 at r20](https://reviewable.io/reviews/aya-rs/aya/1063#-OM8N3YF3MXADVUmFLeJ:-OM8N3YF3MXADVUmFLeK:b-r7fn07) ([raw file](https://github.com/aya-rs/aya/blob/3ace956c5bd57f431f45e633530b24a16ea7eab6/test/integration-test/src/tests/feature_probe.rs#L112)):*
> ```XML
>     if current >= KernelVersion::new(4, 18, 0) {
>         assert_matches!(lwt_seg6local, Ok(true));
>         // assert_matches!(lirc_mode2, Ok(true));
> ```

rather than all these commented-out assertions, write the inverse assertion so it passes and name the needed CONFIG in the string
___
*[`aya/src/sys/feature_probe.rs` line 252 at r20](https://reviewable.io/reviews/aya-rs/aya/1063#-OM8NIw94tB2ncPWM-lZ:-OM8NIw94tB2ncPWM-l_:b-hqob17) ([raw file](https://github.com/aya-rs/aya/blob/3ace956c5bd57f431f45e633530b24a16ea7eab6/aya/src/sys/feature_probe.rs#L252)):*
> ```XML
> /// Create a minimal program with the specified type.
> /// Types not created for `Extension` and `StructOps`.
> fn create_minimal_program(
> ```

there is another function, very similar to this, that i added a while ago. Can you reconcile the two? mine is called `with_trivial_prog`


<!-- Sent from Reviewable.io -->

2025-03-26 21:06 UTC, dave-tucker commented on test/integration-test/src/tests/feature_probe.rs
> +// TODO: Enable certain CONFIG_* options when compiling the image for VM tests.
Note. Since #1160 merged, you can inspect the config for our test images.
E.g: `less test/.tmp/boot/config-6.10.11+bpo-cloud-amd64`

2025-03-26 21:10 UTC, dave-tucker commented on test/integration-test/src/tests/feature_probe.rs
> +    // // Requires `CONFIG_BPF_LSM=y` & `CONFIG_DEBUG_INFO_BTF=y`
Both appear set on the 6.1 and 6.10 kernels in CI:
```
CONFIG_DEBUG_INFO_BTF=y

#
# BPF subsystem
#
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT=y
# CONFIG_BPF_JIT_ALWAYS_ON is not set
CONFIG_BPF_JIT_DEFAULT_ON=y
CONFIG_BPF_UNPRIV_DEFAULT_OFF=y
# CONFIG_BPF_PRELOAD is not set
CONFIG_BPF_LSM=y
# end of BPF subsystem
```

2025-03-29 14:25 UTC, tyrone-wu reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1063)* status: 42 of 53 files reviewed, 5 unresolved discussions (waiting on @alessandrod, @dave-tucker, and @tamird)

___
*[`aya/src/programs/info.rs` line 125 at r13](https://reviewable.io/reviews/aya-rs/aya/1063#-OKSFW_u09dFWpJ2YhQq:-OMXDAdB1VkwpWSVTK1O:b3om685) ([raw file](https://github.com/aya-rs/aya/blob/f4df1a99190eea3381633438b5265626b14c60d3/aya/src/programs/info.rs#L125)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I changed this back to the old logic + the cached feature check. If we want to change the logic, let's at least do it in a separate commit.
</blockquote></details>

:thumbsup: they should be in a separate commit now
___
*[`aya/src/programs/info.rs` line 152 at r13](https://reviewable.io/reviews/aya-rs/aya/1063#-OKSFa2A0O0XaoFOO8QW:-OMXESDE14MK7YqAysFX:b3om685) ([raw file](https://github.com/aya-rs/aya/blob/f4df1a99190eea3381633438b5265626b14c60d3/aya/src/programs/info.rs#L152)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Same here, I changed the logic back -- if you want to change it, I think that can be a separate commit.
</blockquote></details>

:thumbsup: they should be in a separate commit now
___
*[`aya/src/sys/feature_probe.rs` line 252 at r20](https://reviewable.io/reviews/aya-rs/aya/1063#-OM8NIw94tB2ncPWM-lZ:-OMXEVX_Eeq06PZT7oqU:b4c9lyr) ([raw file](https://github.com/aya-rs/aya/blob/3ace956c5bd57f431f45e633530b24a16ea7eab6/aya/src/sys/feature_probe.rs#L252)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

there is another function, very similar to this, that i added a while ago. Can you reconcile the two? mine is called `with_trivial_prog`
</blockquote></details>

:thumbsup: 
___
*[`test/integration-test/src/tests/feature_probe.rs` line 8 at r20](https://reviewable.io/reviews/aya-rs/aya/1063#-OM8N-iv9jUIAORINYGx:-OMXEuh84RzPq2S-nJZv:bn1wz0t) ([raw file](https://github.com/aya-rs/aya/blob/3ace956c5bd57f431f45e633530b24a16ea7eab6/test/integration-test/src/tests/feature_probe.rs#L8)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

remove this, it isn't actionable. what is "certain"?
</blockquote></details>

:thumbsup:
___
*[`test/integration-test/src/tests/feature_probe.rs` line 112 at r20](https://reviewable.io/reviews/aya-rs/aya/1063#-OM8N3YF3MXADVUmFLeJ:-OMXEf5LEmXacfqRTEXR:b-eplmd) ([raw file](https://github.com/aya-rs/aya/blob/3ace956c5bd57f431f45e633530b24a16ea7eab6/test/integration-test/src/tests/feature_probe.rs#L112)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

rather than all these commented-out assertions, write the inverse assertion so it passes and name the needed CONFIG in the string
</blockquote></details>

:thumbsup:  I added some additional checks for programs requiring specific `CONFIG`_*.


<!-- Sent from Reviewable.io -->

2025-03-29 14:25 UTC, tyrone-wu commented on test/integration-test/src/tests/feature_probe.rs
> +// TODO: Enable certain CONFIG_* options when compiling the image for VM tests.
:thumbsup: 
<!-- Reviewable comment -OMXEdoGCCPOZ5BCLrt6:b4c9lyr -->
<!-- Sent from Reviewable.io -->

2025-03-29 14:25 UTC, tyrone-wu commented on test/integration-test/src/tests/feature_probe.rs
> +    // // Requires `CONFIG_BPF_LSM=y` & `CONFIG_DEBUG_INFO_BTF=y`
:thumbsup: 
<!-- Reviewable comment -OMXErG1BZaFFcDy9JyF:b4c9lyr -->
<!-- Sent from Reviewable.io -->

2025-04-15 16:12 UTC, tyrone-wu reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1063)* status: 42 of 53 files reviewed, 13 unresolved discussions (waiting on @alessandrod, @dave-tucker, and @tamird)

___
*[`aya/src/sys/feature_probe.rs` line 83 at r21](https://reviewable.io/reviews/aya-rs/aya/1063#-OMh38DN-pAiTlFAPAu6:-ONuCyjY3GepXDOZSdTN:b-xcx1oa) ([raw file](https://github.com/aya-rs/aya/blob/d9c368c2f0f87798b620d95e790ca1df26501d3a/aya/src/sys/feature_probe.rs#L83)):*
<details><summary><i>Previously, tyrone-wu (Tyrone Wu) wrote…</i></summary><blockquote>

The message `Tracing programs must provide btf_id` initially came from `check_attach_btf_id()` in versions 5.5 up to 5.9 (https://elixir.bootlin.com/linux/v5.9/source/kernel/bpf/verifier.c#L10849). Then it got moved to into `bpf_check_attach_target()` in 5.10 and onward, https://elixir.bootlin.com/linux/v5.10/source/kernel/bpf/verifier.c#L11516

`attach_btf_id` is set for `tracing` and `lsm`, as it first aims for a valid load, that is, if the the BTF sym can be found. If not, then it expects an `EINVAL`, in which it defers to logs.
</blockquote></details>

Sorry if what i wrote is confusing. 😓 I can elaborate more if needed.


<!-- Sent from Reviewable.io -->

2025-04-15 16:53 UTC, tamird requested changes
The two week latency here is rough. Please let me know when you're prepared to iterate quickly, so I don't burn more time paging it all in and then waiting another 2 weeks.

> Reviewed 9 of 11 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1063#-:-ONuMSRhB_OuPCpyh2pt:byhhvso)* status: 43 of 53 files reviewed, 6 unresolved discussions (waiting on @alessandrod, @dave-tucker, and @tyrone-wu)

___
*[`aya/src/sys/bpf.rs` line 747 at r21](https://reviewable.io/reviews/aya-rs/aya/1063#-OMh0JBc9a__KKZEzh-9:-ONuKYQg7WP2FCy6GnYM:b-qmyrmy) ([raw file](https://github.com/aya-rs/aya/blob/d9c368c2f0f87798b620d95e790ca1df26501d3a/aya/src/sys/bpf.rs#L747)):*
<details><summary><i>Previously, tyrone-wu (Tyrone Wu) wrote…</i></summary><blockquote>

Done.
For `cgroup_sock`, I recently tested on kernel 4.10 (when the type was added) up to 4.16, that setting `expected_attach_type` for  produces `E2BIG`.
`sk_reuseport` doesn't encounter this issue when testing against 4.19 and onward.
</blockquote></details>

I still see `_ => None`?
___
*[`aya/src/sys/feature_probe.rs` line 38 at r21](https://reviewable.io/reviews/aya-rs/aya/1063#-OMh1bsS6uhfC6nHqHcA:-ONuKrrn8_kM16HR48JW:b-j3x0q) ([raw file](https://github.com/aya-rs/aya/blob/d9c368c2f0f87798b620d95e790ca1df26501d3a/aya/src/sys/feature_probe.rs#L38)):*
<details><summary><i>Previously, tyrone-wu (Tyrone Wu) wrote…</i></summary><blockquote>

It was an const that I chose arbitrarily at first, it looks like any size between 128 and 16,777,215 should work as well (https://elixir.bootlin.com/linux/v4.15/source/kernel/bpf/verifier.c#L4674).

The full log for this particular error is
`Tracing programs must provide btf_id\nprocessed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0\n\0`, so I trimmed the buffer size down now.
</blockquote></details>

Needs a comment.
___
*[`aya/src/sys/feature_probe.rs` line 39 at r21](https://reviewable.io/reviews/aya-rs/aya/1063#-OMh1kw74UXfHe7f9mKX:-ONuLAKH7Q_2Kn_j-tcM:b-k02cxj) ([raw file](https://github.com/aya-rs/aya/blob/d9c368c2f0f87798b620d95e790ca1df26501d3a/aya/src/sys/feature_probe.rs#L39)):*
<details><summary><i>Previously, tyrone-wu (Tyrone Wu) wrote…</i></summary><blockquote>

`bpf_fentry_test1` comes from https://elixir.bootlin.com/linux/v5.5/source/net/bpf/test_run.c#L112. It appeared in the mainline kernel ubuntu images that I was testing against, but any other func symbol in the BTF can work as well.

`bpf_lsm_bpf` comes from https://elixir.bootlin.com/linux/v5.7/source/include/linux/lsm_hook_defs.h#L364, or https://elixir.bootlin.com/linux/v5.11/source/kernel/bpf/bpf_lsm.c#L135 on newer versions. This can also work with any of the other LSM hooks in `bpf_lsm.c`.

`tracing`, `lsm`, and `extension` all require an `attach_btf_id` for a successful load. However, `extension` has some additional setup for a valid load, i.e. another prog loaded with BTF. How it detects for support is elaborated more in https://reviewable.io/reviews/aya-rs/aya/1063#-OMh2Uu45nsKqxaV3gvr since it goes with the question.
</blockquote></details>

In the future: please just include the explanation in the code. It's very confusing when you include it in this response because then I need to figure out how it maps to what you put in the code.
___
*[`aya/src/sys/feature_probe.rs` line 58 at r21](https://reviewable.io/reviews/aya-rs/aya/1063#-OMh2Uu45nsKqxaV3gvr:-ONuLOZYA15E7Df7tOQD:b3pd95b) ([raw file](https://github.com/aya-rs/aya/blob/d9c368c2f0f87798b620d95e790ca1df26501d3a/aya/src/sys/feature_probe.rs#L58)):*
<details><summary><i>Previously, tyrone-wu (Tyrone Wu) wrote…</i></summary><blockquote>

`attach_btf_id` is needed for a successful load in `tracing` and `lsm`, however, if it isn't able to get the BTF id of their func symbols for whatever reason, then the field is left unset.
When unset, loading produces `EINVAL`, and so it defers to the verifier logs. If logs is filled with `Tracing programs must provide btf_id...` (), then the loading process reached up to the verifier section, which indicates that it's at least aware of the prog type variant. If logs is empty, then the variant isn't supported since it's immediately rejected.

`extension` needs addtional setup for a valid load, so it leaves the attach fields unset so that the target message is written to the logs.
</blockquote></details>

again i am confused why there's a lot more detail here versus in code comments
___
*[`aya/src/sys/feature_probe.rs` line 83 at r21](https://reviewable.io/reviews/aya-rs/aya/1063#-OMh38DN-pAiTlFAPAu6:-ONuLUeB3a6zZPVYgRpo:bkhfmdk) ([raw file](https://github.com/aya-rs/aya/blob/d9c368c2f0f87798b620d95e790ca1df26501d3a/aya/src/sys/feature_probe.rs#L83)):*
<details><summary><i>Previously, tyrone-wu (Tyrone Wu) wrote…</i></summary><blockquote>

Sorry if what i wrote is confusing. 😓 I can elaborate more if needed.
</blockquote></details>

code comments only plz
___
*[`aya/src/sys/feature_probe.rs` line 97 at r25](https://reviewable.io/reviews/aya-rs/aya/1063#-ONuLscA-5Wd2Ao6hssI:-ONuLscA-5Wd2Ao6hssJ:b-1v4kq4) ([raw file](https://github.com/aya-rs/aya/blob/d88f9cdd0e4b91b47a12f1abe2230bd6b2defc2e/aya/src/sys/feature_probe.rs#L97)):*
> ```XML
>                         program_type,
>                         ProgramType::Tracing | ProgramType::Extension | ProgramType::Lsm
>                             if verifier_log.starts_with(b"Tracing programs must provide btf_id"));
> ```

this can just be matches!(...) && verifier_log....

let's not abuse match guards so much



_Code quote:_
```XML
                    let supported = matches!(
                        program_type,
                        ProgramType::Tracing | ProgramType::Extension | ProgramType::Lsm
                            if verifier_log.starts_with(b"Tracing programs must provide btf_id"));
```
___
*[`test/integration-test/src/tests/feature_probe.rs` line 10 at r25](https://reviewable.io/reviews/aya-rs/aya/1063#-ONuM5s--xOH7mcjwmiM:-ONuM5s--xOH7mcjwmiN:b-q4y0cv) ([raw file](https://github.com/aya-rs/aya/blob/d88f9cdd0e4b91b47a12f1abe2230bd6b2defc2e/test/integration-test/src/tests/feature_probe.rs#L10)):*
> ```XML
> #[test]
> fn probe_supported_programs() {
>     let mut kern_version: KernelVersion;
> ```

there is no need for this to be mutable. you can just shadow it.


<!-- Sent from Reviewable.io -->

2025-04-15 21:30 UTC, tyrone-wu reviewed
Sorry, I'm prepared to iterate quickly. I'm in the process of adding comments to the map probe section, so I can ping you once it's ready for review.

> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1063#-:-ONvKEABE4LBB1LM-ey2:b-l2tzqo)* status: 43 of 53 files reviewed, 6 unresolved discussions (waiting on @alessandrod, @dave-tucker, and @tamird)

___
*[`aya/src/sys/bpf.rs` line 747 at r21](https://reviewable.io/reviews/aya-rs/aya/1063#-OMh0JBc9a__KKZEzh-9:-ONuQiWrDmS0vqZgXCwZ:b3h32rw) ([raw file](https://github.com/aya-rs/aya/blob/d9c368c2f0f87798b620d95e790ca1df26501d3a/aya/src/sys/bpf.rs#L747)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I still see `_ => None`?
</blockquote></details>

Oh sorry, I misinterpreted.

I just realized `expected_attach_type` field was added in 4.17 https://elixir.bootlin.com/linux/v4.17/source/include/uapi/linux/bpf.h#L310, which was why I was getting `E2BIG` from earlier. `cgroup_skb`'s attach type was zero, so that happened to work out in its favor.
___
*[`aya/src/sys/feature_probe.rs` line 38 at r21](https://reviewable.io/reviews/aya-rs/aya/1063#-OMh1bsS6uhfC6nHqHcA:-ONuPMzY0kCASJWP4p8N:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/d9c368c2f0f87798b620d95e790ca1df26501d3a/aya/src/sys/feature_probe.rs#L38)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Needs a comment.
</blockquote></details>

Done.
___
*[`aya/src/sys/feature_probe.rs` line 58 at r21](https://reviewable.io/reviews/aya-rs/aya/1063#-OMh2Uu45nsKqxaV3gvr:-ONufu5z4JBkJDvaKGjN:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/d9c368c2f0f87798b620d95e790ca1df26501d3a/aya/src/sys/feature_probe.rs#L58)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

again i am confused why there's a lot more detail here versus in code comments
</blockquote></details>

Done.
___
*[`aya/src/sys/feature_probe.rs` line 97 at r25](https://reviewable.io/reviews/aya-rs/aya/1063#-ONuLscA-5Wd2Ao6hssI:-ONuW9Sw9ODnmLDlWmCv:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/d88f9cdd0e4b91b47a12f1abe2230bd6b2defc2e/aya/src/sys/feature_probe.rs#L97)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this can just be matches!(...) && verifier_log....

let's not abuse match guards so much
</blockquote></details>

Done.
___
*[`test/integration-test/src/tests/feature_probe.rs` line 10 at r25](https://reviewable.io/reviews/aya-rs/aya/1063#-ONuM5s--xOH7mcjwmiM:-ONuXk460DoE_gr4LVnZ:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/d88f9cdd0e4b91b47a12f1abe2230bd6b2defc2e/test/integration-test/src/tests/feature_probe.rs#L10)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

there is no need for this to be mutable. you can just shadow it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-04-17 00:23 UTC, tamird requested changes
I think we'll need to wait for something like https://github.com/aya-rs/aya/pull/1251, or else how can we test this? We may also need to look for another source of kernel images that allows us to go back further than 5.10.

> Reviewed 8 of 10 files at r29.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1063#-:-OO06AxhBg_7FEblmdWO:b-6p0giq)* status: 43 of 53 files reviewed, 2 unresolved discussions (waiting on @alessandrod and @dave-tucker)

___
*[`aya/src/sys/bpf.rs` line 747 at r21](https://reviewable.io/reviews/aya-rs/aya/1063#-OMh0JBc9a__KKZEzh-9:-ONzpyI66kmzzXQ5aH4T:b6zwme1) ([raw file](https://github.com/aya-rs/aya/blob/d9c368c2f0f87798b620d95e790ca1df26501d3a/aya/src/sys/bpf.rs#L747)):*
<details><summary><i>Previously, tyrone-wu (Tyrone Wu) wrote…</i></summary><blockquote>

Oh sorry, I misinterpreted.

I just realized `expected_attach_type` field was added in 4.17 https://elixir.bootlin.com/linux/v4.17/source/include/uapi/linux/bpf.h#L310, which was why I was getting `E2BIG` from earlier. `cgroup_skb`'s attach type was zero, so that happened to work out in its favor.
</blockquote></details>

I guess we'll know what works when we add CI for those old kernels.
___
*[`aya/src/sys/bpf.rs` line 761 at r29](https://reviewable.io/reviews/aya-rs/aya/1063#-ONzq5LpDdyANefhlDVd:-ONzq5LpDdyANefhlDVe:b-nedb74) ([raw file](https://github.com/aya-rs/aya/blob/0071895ecebd058af120b663f90bd7941001dcca/aya/src/sys/bpf.rs#L761)):*
> ```XML
>         ProgramType::Netfilter => Some(bpf_attach_type::BPF_NETFILTER),
>         // Program types below v4.17, or do not accept `expected_attach_type`, should leave the
>         // field unset.
> ```

empty comment line between paragraphs


<!-- Sent from Reviewable.io -->

2025-04-18 14:17 UTC, tyrone-wu reviewed
I've been grabbing my kernel images from https://kernel.ubuntu.com/mainline/. However, `linux-image-*` packages includes a few other stuff besides the image, like firmware, modules, etc., which take up considerable portion of its size.
Cilium appears to build their kernel images from [source](https://github.com/cilium/ci-kernels/blob/main/download.sh) and stores them via githubs container registry.

> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1063#-:-OO822w059UNGeCAqjxY:b-aev2ku)* status: 43 of 53 files reviewed, 2 unresolved discussions (waiting on @alessandrod, @dave-tucker, and @tamird)

___
*[`aya/src/sys/bpf.rs` line 761 at r29](https://reviewable.io/reviews/aya-rs/aya/1063#-ONzq5LpDdyANefhlDVd:-OO3eFu1DMpd_XWcU2Pe:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/0071895ecebd058af120b663f90bd7941001dcca/aya/src/sys/bpf.rs#L761)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

empty comment line between paragraphs
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-04-21 14:27 UTC, tamird reviewed
> Reviewed 10 of 10 files at r33, 5 of 5 files at r34, 8 of 8 files at r35, 1 of 1 files at r36, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1063)* status: all files reviewed, 9 unresolved discussions (waiting on @alessandrod and @dave-tucker)

___
*[`aya/src/sys/feature_probe.rs` line 36 at r33](https://reviewable.io/reviews/aya-rs/aya/1063#-OONhuCt6WARnwEAf8Xt:-OONhuCt6WARnwEAf8Xu:bghcwpm) ([raw file](https://github.com/aya-rs/aya/blob/0614367c3629f58bb90ad70f231117975a6a881d/aya/src/sys/feature_probe.rs#L36)):*
> ```XML
> 
>     // Verifier log is used in tracing, extension, and lsm to help detect support if loading fails.
>     // The expected target message for these types is:
> ```

empty comment lines where you don't want things re-wrapped
___
*[`aya/src/sys/feature_probe.rs` line 39 at r33](https://reviewable.io/reviews/aya-rs/aya/1063#-OONhyMdE5uZ4ijytSlC:-OONhyMdE5uZ4ijytSlD:biksluj) ([raw file](https://github.com/aya-rs/aya/blob/0614367c3629f58bb90ad70f231117975a6a881d/aya/src/sys/feature_probe.rs#L39)):*
> ```XML
>     // `Tracing programs must provide btf_id\nprocessed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0\n\0`
>     // https://elixir.bootlin.com/linux/v5.5/source/kernel/bpf/verifier.c#L9535
>     let mut verifier_log = [0_u8; 136];
> ```

is that exactly the count? maybe give it 256 so we can be confident we didn't truncate
___
*[`aya/src/sys/feature_probe.rs` line 69 at r33](https://reviewable.io/reviews/aya-rs/aya/1063#-OONiG5Q5fY1ICnpHH_h:-OONiG5Q5fY1ICnpHH_i:b-ibza6) ([raw file](https://github.com/aya-rs/aya/blob/0614367c3629f58bb90ad70f231117975a6a881d/aya/src/sys/feature_probe.rs#L69)):*
> ```XML
>             u.attach_btf_id = attach_btf_id;
>         }
>         match program_type {
> ```

why is this conditional?
___
*[`aya/src/sys/feature_probe.rs` line 101 at r33](https://reviewable.io/reviews/aya-rs/aya/1063#-OONiTcW2MrQyXIxSso1:-OONiTcXBgBhfsHzY4rs:bjniab1) ([raw file](https://github.com/aya-rs/aya/blob/0614367c3629f58bb90ad70f231117975a6a881d/aya/src/sys/feature_probe.rs#L101)):*
> ```XML
>                     // At this point for tracing, extension, and lsm, loading failed due to unset
>                     // `attach_btf_id`, so we examine verifier log for the target message.
>                     // Message originates in `check_attach_btf_id()` in v5.5 to v5.9 https://elixir.bootlin.com/linux/v5.5/source/kernel/bpf/verifier.c#L9535,
> ```

can we wrap this as normal? 
___
*[`aya/src/sys/feature_probe.rs` line 107 at r33](https://reviewable.io/reviews/aya-rs/aya/1063#-OONi_MA9C8Vcr6iOGY0:-OONi_MA9C8Vcr6iOGY1:b-exqfwh) ([raw file](https://github.com/aya-rs/aya/blob/0614367c3629f58bb90ad70f231117975a6a881d/aya/src/sys/feature_probe.rs#L107)):*
> ```XML
>                     // up to the verifier section, which indicates that the kernel is at least
>                     // aware of the program type variants.
>                     // If logs is empty, then it was immediately rejected by the kernel, meaning
> ```

ditto, if you want a line break, insert an empty comment line
___
*[`test/integration-test/src/tests/feature_probe.rs` line 129 at r33](https://reviewable.io/reviews/aya-rs/aya/1063#-OONitv22j9CZCndCXmE:-OONitv22j9CZCndCXmF:b-4c6bo7) ([raw file](https://github.com/aya-rs/aya/blob/0614367c3629f58bb90ad70f231117975a6a881d/test/integration-test/src/tests/feature_probe.rs#L129)):*
> ```XML
>     kernel_assert!(is_supported!(ProgramType::Syscall), kern_version);
> 
>     let kern_version = KernelVersion::new(6, 4, 0);
> ```

as mentioned previously, we're gonna need to change out CI to validate all this. are you interested in doing that work?
___
*[`aya/src/sys/feature_probe.rs` line 224 at r34](https://reviewable.io/reviews/aya-rs/aya/1063#-OONjDsC6ktnS9v_UqOS:-OONjDsC6ktnS9v_UqOT:b-tqhmtv) ([raw file](https://github.com/aya-rs/aya/blob/1655df36c7e376d779476b7bf5ea21894f7acec6/aya/src/sys/feature_probe.rs#L224)):*
> ```XML
>     u.max_entries = max_entries;
> 
>     // Ensure that fd doesn't get dropped due to scoping for for *_of_maps type.
> ```

"for for"
___
*[`aya/src/sys/feature_probe.rs` line 301 at r34](https://reviewable.io/reviews/aya-rs/aya/1063#-OONjY7cEFOb5udFbVdx:-OONjY7cEFOb5udFbVdy:b-vmpp62) ([raw file](https://github.com/aya-rs/aya/blob/1655df36c7e376d779476b7bf5ea21894f7acec6/aya/src/sys/feature_probe.rs#L301)):*
> ```XML
>         // For these types, `EBADF` from `btf_get_by_fd()` https://elixir.bootlin.com/linux/v5.2/source/kernel/bpf/btf.c#L3428
>         // indicates that map_create advanced far enough in the validation to recognize the type
>         // before being rejected.
> ```

everywhere you want a line break use an empty comment line please


<!-- Sent from Reviewable.io -->

2025-04-30 00:23 UTC, tyrone-wu reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1063)* status: 43 of 53 files reviewed, 9 unresolved discussions (waiting on @alessandrod, @dave-tucker, and @tamird)

___
*[`aya/src/sys/feature_probe.rs` line 36 at r33](https://reviewable.io/reviews/aya-rs/aya/1063#-OONhuCt6WARnwEAf8Xt:-OOYU3bX5KA7s8BK4d_P:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/0614367c3629f58bb90ad70f231117975a6a881d/aya/src/sys/feature_probe.rs#L36)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

empty comment lines where you don't want things re-wrapped
</blockquote></details>

Done.
___
*[`aya/src/sys/feature_probe.rs` line 39 at r33](https://reviewable.io/reviews/aya-rs/aya/1063#-OONhyMdE5uZ4ijytSlC:-OOYUrYZ0gZmKRaVASPZ:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/0614367c3629f58bb90ad70f231117975a6a881d/aya/src/sys/feature_probe.rs#L39)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is that exactly the count? maybe give it 256 so we can be confident we didn't truncate
</blockquote></details>

Done.
___
*[`aya/src/sys/feature_probe.rs` line 69 at r33](https://reviewable.io/reviews/aya-rs/aya/1063#-OONiG5Q5fY1ICnpHH_h:-OOYZCh57TxClrs8e-dj:b-rz3i4f) ([raw file](https://github.com/aya-rs/aya/blob/0614367c3629f58bb90ad70f231117975a6a881d/aya/src/sys/feature_probe.rs#L69)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why is this conditional?
</blockquote></details>

Only those types make use of the verifier log. I updated the logic to make it a bit more clear.
___
*[`aya/src/sys/feature_probe.rs` line 101 at r33](https://reviewable.io/reviews/aya-rs/aya/1063#-OONiTcW2MrQyXIxSso1:-OOY_E-k9TaRwusw2I3O:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/0614367c3629f58bb90ad70f231117975a6a881d/aya/src/sys/feature_probe.rs#L101)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can we wrap this as normal?
</blockquote></details>

Done.
___
*[`aya/src/sys/feature_probe.rs` line 107 at r33](https://reviewable.io/reviews/aya-rs/aya/1063#-OONi_MA9C8Vcr6iOGY0:-OOY_DgXBuInMA5DGRg9:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/0614367c3629f58bb90ad70f231117975a6a881d/aya/src/sys/feature_probe.rs#L107)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ditto, if you want a line break, insert an empty comment line
</blockquote></details>

Done.
___
*[`aya/src/sys/feature_probe.rs` line 224 at r34](https://reviewable.io/reviews/aya-rs/aya/1063#-OONjDsC6ktnS9v_UqOS:-OOYb7SABz0MeXaeSfmR:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/1655df36c7e376d779476b7bf5ea21894f7acec6/aya/src/sys/feature_probe.rs#L224)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

"for for"
</blockquote></details>

Done.
___
*[`aya/src/sys/feature_probe.rs` line 301 at r34](https://reviewable.io/reviews/aya-rs/aya/1063#-OONjY7cEFOb5udFbVdx:-OOYcIVgAY7W4bpsp35k:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/1655df36c7e376d779476b7bf5ea21894f7acec6/aya/src/sys/feature_probe.rs#L301)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

everywhere you want a line break use an empty comment line please
</blockquote></details>

Done.
___
*[`test/integration-test/src/tests/feature_probe.rs` line 129 at r33](https://reviewable.io/reviews/aya-rs/aya/1063#-OONitv22j9CZCndCXmE:-OP27pXI-ByctR-EqjEv:bbvdcz1) ([raw file](https://github.com/aya-rs/aya/blob/0614367c3629f58bb90ad70f231117975a6a881d/test/integration-test/src/tests/feature_probe.rs#L129)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

as mentioned previously, we're gonna need to change out CI to validate all this. are you interested in doing that work?
</blockquote></details>

yea, I can take on that work. I did some prototyping, in which I'm building the kernel images from source, and storing the vmlinuz artifacts in Github Packages. This is my first time using GH Packages , but from what I've researched it can be used as a registry for hosting generic artifacts. It's still a working progress so it might take some time until it's ready. I'm also open to other idea .

wip stuff: https://github.com/tyrone-wu/aya/blob/main/.github/workflows/build-kernels.yml
https://github.com/tyrone-wu/aya/pkgs/container/vmlinuz


<!-- Sent from Reviewable.io -->

2025-05-05 19:01 UTC, tamird reviewed
> Reviewed 10 of 10 files at r37, 5 of 5 files at r38, 8 of 8 files at r39, 1 of 1 files at r40, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1063)* status: all files reviewed, 4 unresolved discussions (waiting on @alessandrod and @dave-tucker)

___
*[`test/integration-test/src/tests/feature_probe.rs` line 129 at r33](https://reviewable.io/reviews/aya-rs/aya/1063#-OONitv22j9CZCndCXmE:-OPWogMQBylSY-z39Xup:b-a95w2a) ([raw file](https://github.com/aya-rs/aya/blob/0614367c3629f58bb90ad70f231117975a6a881d/test/integration-test/src/tests/feature_probe.rs#L129)):*
<details><summary><i>Previously, tyrone-wu (Tyrone Wu) wrote…</i></summary><blockquote>

yea, I can take on that work. I did some prototyping, in which I'm building the kernel images from source, and storing the vmlinuz artifacts in Github Packages. This is my first time using GH Packages , but from what I've researched it can be used as a registry for hosting generic artifacts. It's still a working progress so it might take some time until it's ready. I'm also open to other idea .

wip stuff: https://github.com/tyrone-wu/aya/blob/main/.github/workflows/build-kernels.yml
https://github.com/tyrone-wu/aya/pkgs/container/vmlinuz
</blockquote></details>

Obviously I'd prefer to avoid owning the machinery for building kernels from source. Perhaps @dave-tucker has thoughts as well.
___
*[`aya/src/sys/feature_probe.rs` line 35 at r37](https://reviewable.io/reviews/aya-rs/aya/1063#-OPWoIUl4o5hOdokqrMO:-OPWoIUl4o5hOdokqrMP:b-9kik66) ([raw file](https://github.com/aya-rs/aya/blob/f10b2d27f4c2b5b9ff5380915df2ce9f6d623719/aya/src/sys/feature_probe.rs#L35)):*
> ```XML
>     }
> 
>     // Verifier log is used in tracing, extension, and lsm to help detect support if loading fails.
> ```

it would be good to explain why only these types and not others.
___
*[`aya/src/sys/feature_probe.rs` line 112 at r37](https://reviewable.io/reviews/aya-rs/aya/1063#-OPWo9bd7hG_cxUJEjH9:-OPWo9bd7hG_cxUJEjHA:b-lswqyq) ([raw file](https://github.com/aya-rs/aya/blob/f10b2d27f4c2b5b9ff5380915df2ce9f6d623719/aya/src/sys/feature_probe.rs#L112)):*
> ```XML
>                     // aware of the program type variants.
>                     //
>                     // If logs is empty, then it was immediately rejected by the kernel, meaning
> ```

log is? the log is?


<!-- Sent from Reviewable.io -->

2025-05-13 18:11 UTC, tyrone-wu reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1063)* status: 43 of 53 files reviewed, 4 unresolved discussions (waiting on @alessandrod, @dave-tucker, and @tamird)

___
*[`aya/src/sys/feature_probe.rs` line 35 at r37](https://reviewable.io/reviews/aya-rs/aya/1063#-OPWoIUl4o5hOdokqrMO:-OQ9OZeA623WSiWOVgVA:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/f10b2d27f4c2b5b9ff5380915df2ce9f6d623719/aya/src/sys/feature_probe.rs#L35)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

it would be good to explain why only these types and not others.
</blockquote></details>

Done.
___
*[`aya/src/sys/feature_probe.rs` line 112 at r37](https://reviewable.io/reviews/aya-rs/aya/1063#-OPWo9bd7hG_cxUJEjH9:-OQ95vEBA21whL4X8aZQ:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/f10b2d27f4c2b5b9ff5380915df2ce9f6d623719/aya/src/sys/feature_probe.rs#L112)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

log is? the log is?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-05-13 18:17 UTC, tamird reviewed
> Reviewed 2 of 5 files at r42, 7 of 8 files at r43, 1 of 1 files at r44, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1063)* status: all files reviewed, 2 unresolved discussions (waiting on @alessandrod and @dave-tucker)



<!-- Sent from Reviewable.io -->

2025-05-14 10:05 UTC, dave-tucker approved these changes

2025-05-14 10:16 UTC, tamird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1063#-:-OQDHsYy4QSQ61haHKnU:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @alessandrod and @dave-tucker)



<!-- Sent from Reviewable.io -->

2025-05-14 12:03 UTC, tamird commented
Alrighty, we've agreed to take this and follow up with older kernel tests in follow up work.

2025-05-14 12:03 UTC, merged