feat(aya): Add iterator program type
aya-rs/aya pull request #1088
Opened 2024-11-18 08:51 UTC by vadorovsky

BPF iterators[0] are a way to dump kernel data into user-space and an alternative to `/proc` filesystem.

This change adds support for BPF iterators on the user-space side. It provides a possibility to retrieve the outputs of BPF iterator programs both from sync and async Rust code.

[0] https://docs.kernel.org/bpf/bpf_iterators.html

2024-11-19 08:24 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1088)* status: all files reviewed, 15 unresolved discussions (waiting on @alessandrod and @tamird)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBztcX-BcleiGW2gXng:-OC2OHRtDt4qrIweK1_g:b-7wkfbu):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

do we need to worry about compatibility with older kernels?
</blockquote></details>

I don't think so. On older kernels, the program will just fail to load - but I think that's OK. I'm not a big fan of explicit kernel version checks. There are no incompatibilties across kernels supporting iterators.
___
*[`aya/src/programs/mod.rs` line 332 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBztUAMBcQUUJ-6L6pF:-OC2PNySB3k4ASmjOEPy:bfjipbm) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/programs/mod.rs#L332)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

how come?
</blockquote></details>

Iterators are a subset of tracing programs:

https://elixir.bootlin.com/linux/v6.12-rc7/source/tools/lib/bpf/libbpf.c#L9405

I will add a comment.
___
*[`aya/src/sys/bpf.rs` line 416 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzu67AEJHtU_W-pw26:-OC2R5kL0aCXracGDkMl:b-rx7ghd) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/sys/bpf.rs#L416)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why aren't we linking to github? also, linking to the kernel side would be more convincing =/
</blockquote></details>

I personally find bootlin easier to use to jump around kernel code. Their search actually works, unlike search on github. :stuck_out_tongue: Jumping to symbol definitions always works. I would strongly insist on sticking to bootlin for kernel code.

I know we have mixed github and bootlin links in different places in Aya. I would be happy to change all of them to bootlin in a separate PR.

Regarding the kernel side proof, let me try to find it. The overall expl
___
*[`test/integration-test/bpf/iter.bpf.c` line 12 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzvI3I7T-joxCEnPtd:-OC2RMzK9GKQD07uzC1V:bumvi3i) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/test/integration-test/bpf/iter.bpf.c#L12)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

under what circumstances is this possible?
</blockquote></details>

Good point, that should never happen.


<!-- Sent from Reviewable.io -->

2024-11-19 14:27 UTC, tamird requested changes
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1088)* status: all files reviewed, 14 unresolved discussions (waiting on @alessandrod and @vadorovsky)

___
*[`aya/src/sys/bpf.rs` line 416 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzu67AEJHtU_W-pw26:-OC3oJ6X0weCI1zRXw5M:b-6mvpgz) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/sys/bpf.rs#L416)):*
> I personally find bootlin easier to use to jump around kernel code. Their search actually works, unlike search on github. 😛 Jumping to symbol definitions always works. I would strongly insist on sticking to bootlin for kernel code.

Yeah, github is a bit iffy on this tooling, but it's getting better, and it's the canonical repo.

> I know we have mixed github and bootlin links in different places in Aya. I would be happy to change all of them to bootlin in a separate PR.

I think we should go the other way.

```
tamird@Tamirs-MacBook-Pro aya % git grep elixir | wc -l
       6
tamird@Tamirs-MacBook-Pro aya % git grep -F 'torvalds/linux' | wc -l
      46
```


<!-- Sent from Reviewable.io -->

2024-11-23 09:01 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1088)* status: all files reviewed, 14 unresolved discussions (waiting on @alessandrod and @tamird)

___
*[`aya/Cargo.toml` line 34 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBztNKD7PFjABdHiFE6:-OCN8XP7C9DfInnNrFl8:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/Cargo.toml#L34)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

these new dependencies belong in the intergration test crate, not here. they are not used by aya.
</blockquote></details>

Done.
___
*[`aya/src/programs/iter.rs` line 8 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzwTCaEe9mUgrDN6DP:-OCN8iK36hvmkGnrR9k6:bhynz8q) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/programs/iter.rs#L8)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

inconsistent import here
</blockquote></details>

I left this one and removed the other one (`obj::generated`) - other `aya/src/program` modules import from `crate::generated`.
___
*[`aya/src/programs/iter.rs` line 22 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzvP509K_vBUexk_Ov:-OCN8xKqEuHNM8J09_-d:b-z515wc) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/programs/iter.rs#L22)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

the antecedent of "which offers more flexibility" is a bit unclear. like, i don't know if you're saying the iterator is more flexible or procfs is.
</blockquote></details>

Done, but feel free to propose something else, if it still doesn't look good to you.
___
*[`aya/src/programs/iter.rs` line 96 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzwtFX45JpDeWrAaSe:-OCN9b3g4xBJiWLep-2K:b-gra8n4) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/programs/iter.rs#L96)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

i can't parse this sentence because half of it is in the future tense and half is in the present tense.
</blockquote></details>

Good call, done. It's a copy paste from other modules though, so it needs to be fixed there as well.
___
*[`aya/src/programs/iter.rs` line 166 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzxDPP7igt6j_AzZUk:-OCNAx0rCbt5tj7ROkLC:bjr36ql) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/programs/iter.rs#L166)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can we just use `From<OwnedFd>`? https://doc.rust-lang.org/std/fs/struct.File.html#impl-From%3COwnedFd%3E-for-File

MockableFd.into_inner() returns OwnedFd.
</blockquote></details>

Nice one! With that trick, I don't even have to do the whole dance with `ManuallyDrop`. Thanks!
___
*[`aya/src/programs/iter.rs` line 176 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzxaTz8XA5gOeYLXNZ:-OCNBThr-Rm9b3wJmpZ7:b8a8f7g) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/programs/iter.rs#L176)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

it is completely pointless to provide this IMO, the caller can trivially do it having obtained the std File
</blockquote></details>

You're right, done.
___
*[`aya/src/programs/iter.rs` line 205 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzxgrz0NIdryUWLd3A:-OCNBXtk7qhplyVdEK6a:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/programs/iter.rs#L205)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ditto

https://docs.rs/tokio/latest/tokio/fs/struct.File.html#method.from_std
</blockquote></details>

Done.
___
*[`aya/src/sys/bpf.rs` line 416 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzu67AEJHtU_W-pw26:-OCNDMDu9LdlnPAZim05:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/sys/bpf.rs#L416)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

> I personally find bootlin easier to use to jump around kernel code. Their search actually works, unlike search on github. 😛 Jumping to symbol definitions always works. I would strongly insist on sticking to bootlin for kernel code.

Yeah, github is a bit iffy on this tooling, but it's getting better, and it's the canonical repo.

> I know we have mixed github and bootlin links in different places in Aya. I would be happy to change all of them to bootlin in a separate PR.

I think we should go the other way.

```
tamird@Tamirs-MacBook-Pro aya % git grep elixir | wc -l
       6
tamird@Tamirs-MacBook-Pro aya % git grep -F 'torvalds/linux' | wc -l
      46
```
</blockquote></details>

Done.
___
*[`test/integration-test/bpf/iter.bpf.c` line 12 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzvI3I7T-joxCEnPtd:-OCNDgp63XkHUdwoE96E:b-99o5pl) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/test/integration-test/bpf/iter.bpf.c#L12)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

Good point, that should never happen.
</blockquote></details>

Lol, removing it makes verifier unhappy

```
0: R1=ctx(off=0,imm=0) R10=fp0
; struct seq_file *seq = ctx->meta->seq;
0: (79) r2 = *(u64 *)(r1 +0)
func 'bpf_iter_task' arg0 has btf_id 14387 type STRUCT 'bpf_iter_meta'
1: R1=ctx(off=0,imm=0) R2_w=trusted_ptr_bpf_iter_meta(off=0,imm=0)
; struct task_struct *task = ctx->task;
1: (79) r7 = *(u64 *)(r1 +8)          ; R1=ctx(off=0,imm=0) R7_w=ptr_or_null_task_struct(id=1,off=0,imm=0)
; struct seq_file *seq = ctx->meta->seq;
2: (79) r6 = *(u64 *)(r2 +0)          ; R2_w=trusted_ptr_bpf_iter_meta(off=0,imm=0) R6_w=trusted_ptr_seq_file(off=0,imm=0)
; if (ctx->meta->seq_num == 0) {
3: (79) r1 = *(u64 *)(r2 +16)         ; R1_w=scalar() R2_w=trusted_ptr_bpf_iter_meta(off=0,imm=0)
; if (ctx->meta->seq_num == 0) {
4: (55) if r1 != 0x0 goto pc+8        ; R1_w=0
5: (bf) r4 = r10                      ; R4_w=fp0 R10=fp0
; BPF_SEQ_PRINTF(seq, "tgid     pid      name\n");
6: (07) r4 += -24                     ; R4_w=fp-24
7: (bf) r1 = r6                       ; R1_w=trusted_ptr_seq_file(off=0,imm=0) R6_w=trusted_ptr_seq_file(off=0,imm=0)
8: (18) r2 = 0xffff888f3a46a910       ; R2_w=map_value(off=0,ks=4,vs=38,imm=0)
10: (b7) r3 = 24                      ; R3_w=24
11: (b7) r5 = 0                       ; R5_w=0
12: (85) call bpf_seq_printf#126      ; R0=scalar()
; BPF_SEQ_PRINTF(seq, "%-8d %-8d %s\n", task->tgid, task->pid, task->comm);
13: (61) r1 = *(u32 *)(r7 +2460)
R7 invalid mem access 'ptr_or_null_'
verification time 305 usec
stack depth 24
```
___
*[`test/integration-test/src/tests/iter.rs` line 24 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzuvYQCGHcDa38f-YC:-OCNEqW533ctcPfQH5V6:b-uwzx3n) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/test/integration-test/src/tests/iter.rs#L24)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this assertion emits nothing useful on failure
</blockquote></details>

I added some manual message, but overall it's a bummer that there is no `assert_in!` which would do that for me.
___
*[`test/integration-test/src/tests/iter.rs` line 44 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzvCLn2O7NBBSD7kWW:-OCNEybH8gA02yFmgQcq:b-7ropln) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/test/integration-test/src/tests/iter.rs#L44)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto


<!--  [...]

2024-11-23 12:02 UTC, tamird requested changes
> Reviewed 6 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1088)* status: all files reviewed, 11 unresolved discussions (waiting on @alessandrod and @vadorovsky)

___
*[`aya/Cargo.toml` line 34 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBztNKD7PFjABdHiFE6:-OCNrVyT-6-qe589bndo:br0odsd) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/Cargo.toml#L34)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

async-fs is still here.
___
*[`aya/src/programs/iter.rs` line 8 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzwTCaEe9mUgrDN6DP:-OCNrf3pCl-j6sEsnCV-:b1o2p6t) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/programs/iter.rs#L8)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

I left this one and removed the other one (`obj::generated`) - other `aya/src/program` modules import from `crate::generated`.
</blockquote></details>

the other inconsistency is that you import `BPF_TRACE_ITER` but not `bpf_prog_type::BPF_PROG_TYPE_TRACING` (same with `bpf_link_type::BPF_LINK_TYPE_ITER`
___
*[`aya/src/programs/iter.rs` line 22 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzvP509K_vBUexk_Ov:-OCNsIAS8v7gbgSMZR25:bjyzav4) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/programs/iter.rs#L22)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

Done, but feel free to propose something else, if it still doesn't look good to you.
</blockquote></details>

I think removing the comma after "filesystem" would make things clearer.
___
*[`aya/src/programs/iter.rs` line 72 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzwhZSBg7btsNgfdQ1:-OCNsW0YANnup2Opzqla:b-otbfkn) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/programs/iter.rs#L72)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this should be [`Iter::detach`] or [`Self::detach`].
</blockquote></details>

Why not Self?
___
*[`aya/src/programs/iter.rs` line 96 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzwtFX45JpDeWrAaSe:-OCNsbETCa7gO2adcr1l:bv9wg7v) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/programs/iter.rs#L96)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

Good call, done. It's a copy paste from other modules though, so it needs to be fixed there as well.
</blockquote></details>

Did you fix the others?
___
*[`test/integration-test/Cargo.toml` line 30 at r3](https://reviewable.io/reviews/aya-rs/aya/1088#-OCNtgIo72gNVGqVoJ57:-OCNtgIo72gNVGqVoJ58:bxd0egm) ([raw file](https://github.com/aya-rs/aya/blob/f19731774b193681ecdb44c2aa0ee0dbb2cb4cbf/test/integration-test/Cargo.toml#L30)):*
> ```TOML
> tokio = { workspace = true, features = [
>     "fs",
>     "io-util",
> ```

as in another comment i think we can revert this, no need to test tokio itself
___
*[`test/integration-test/src/tests/iter.rs` line 34 at r3](https://reviewable.io/reviews/aya-rs/aya/1088#-OCNt_UD3Kl9fUQQ42-e:-OCNt_UD3Kl9fUQQ42-f:b-xnt1hh) ([raw file](https://github.com/aya-rs/aya/blob/f19731774b193681ecdb44c2aa0ee0dbb2cb4cbf/test/integration-test/src/tests/iter.rs#L34)):*
> ```XML
> 
> #[test(tokio::test)]
> async fn iter_async_task() {
> ```

do we get any value out of testing this? we're just testing tokio here.
___
*[`aya/src/programs/iter.rs` line 14 at r3](https://reviewable.io/reviews/aya-rs/aya/1088#-OCNsFZT29Aqvua_8hxC:-OCNs8BZAX-5YVoTWi2J:bewu6bf) ([raw file](https://github.com/aya-rs/aya/blob/f19731774b193681ecdb44c2aa0ee0dbb2cb4cbf/aya/src/programs/iter.rs#L14)):*
> ```XML
> };
> 
> /// An eBPF iterator which allows to dump into user space.
> ```

s/eBPF/BPF/ per the docs
___
*[`aya/src/programs/iter.rs` line 154 at r3](https://reviewable.io/reviews/aya-rs/aya/1088#-OCNsjBLAiWQtFmxhKp-:-OCNsjBLAiWQtFmxhKp0:bipsyhw) ([raw file](https://github.com/aya-rs/aya/blob/f19731774b193681ecdb44c2aa0ee0dbb2cb4cbf/aya/src/programs/iter.rs#L154)):*
> ```XML
>                 })
>             })?;
>             let file: std::fs::File = fd.into_inner().into();
> ```

nit: I think you can drop local? `Ok(fd.into_inner().into())` should be ale to infer the target type
___
*[`aya/src/sys/bpf.rs` line 420 at r3](https://reviewable.io/reviews/aya-rs/aya/1088#-OCNtC0K0liJiSdoRaFo:-OCNtC0K0liJiSdoRaFp:b-h5frac) ([raw file](https://github.com/aya-rs/aya/blob/f19731774b193681ecdb44c2aa0ee0dbb2cb4cbf/aya/src/sys/bpf.rs#L420)):*
> ```XML
>         // https://github.com/torvalds/linux/blob/v6.12/kernel/bpf/bpf_iter.c#L517-L518
>         LinkTarget::Iter => {
>             attr.link_create.__bindgen_anon_2.target_fd = 0;
> ```

wait do we actually need to do this? we start with a mem::zeroed above. I mean it's fine to do it, but I think it is't necessary.


<!-- Sent from Reviewable.io -->

2024-11-24 08:00 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1088)* status: all files reviewed, 11 unresolved discussions (waiting on @alessandrod and @tamird)

___
*[`aya/Cargo.toml` line 34 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBztNKD7PFjABdHiFE6:-OCS0m27-VhR1sCjt1ri:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/Cargo.toml#L34)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

async-fs is still here.
</blockquote></details>

Done.
___
*[`aya/src/programs/iter.rs` line 8 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzwTCaEe9mUgrDN6DP:-OCS0mPK5PJ06ArqdxaG:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/programs/iter.rs#L8)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

the other inconsistency is that you import `BPF_TRACE_ITER` but not `bpf_prog_type::BPF_PROG_TYPE_TRACING` (same with `bpf_link_type::BPF_LINK_TYPE_ITER`
</blockquote></details>

Done.
___
*[`aya/src/programs/iter.rs` line 22 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzvP509K_vBUexk_Ov:-OCS0nZC30TrIFPrIlPm:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/programs/iter.rs#L22)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I think removing the comma after "filesystem" would make things clearer.
</blockquote></details>

Done.
___
*[`aya/src/programs/iter.rs` line 72 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzwhZSBg7btsNgfdQ1:-OCO01JJDyTDu8c0d02P:bb6un1j) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/programs/iter.rs#L72)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Why not Self?
</blockquote></details>

Done
___
*[`aya/src/programs/iter.rs` line 89 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzwpklB44vmK1TMrvU:-OCS0uooEYidFyFox5-w:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/programs/iter.rs#L89)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`aya/src/programs/iter.rs` line 96 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzwtFX45JpDeWrAaSe:-OCO0O_W3O7s8Imkpkx8:b-cw219t) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/programs/iter.rs#L96)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Did you fix the others?
</blockquote></details>

No, because I'm not touching the other files in this PR. To be clear - I copy pasted that docstring from the XDP module. I think it deserves a separate PR.
___
*[`aya/src/programs/iter.rs` line 14 at r3](https://reviewable.io/reviews/aya-rs/aya/1088#-OCNsFZT29Aqvua_8hxC:-OCS0mumDW9aQUDpnewo:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/f19731774b193681ecdb44c2aa0ee0dbb2cb4cbf/aya/src/programs/iter.rs#L14)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

s/eBPF/BPF/ per the docs
</blockquote></details>

Done.
___
*[`aya/src/programs/iter.rs` line 154 at r3](https://reviewable.io/reviews/aya-rs/aya/1088#-OCNsjBLAiWQtFmxhKp-:-OCS10zn1D-ZZRZjcMnm:b-hu48ua) ([raw file](https://github.com/aya-rs/aya/blob/f19731774b193681ecdb44c2aa0ee0dbb2cb4cbf/aya/src/programs/iter.rs#L154)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: I think you can drop local? `Ok(fd.into_inner().into())` should be ale to infer the target type
</blockquote></details>

Nice one, done
___
*[`aya/src/sys/bpf.rs` line 420 at r3](https://reviewable.io/reviews/aya-rs/aya/1088#-OCNtC0K0liJiSdoRaFo:-OCO0c8EAJR6Ue8qZBGu:bmdsk6b) ([raw file](https://github.com/aya-rs/aya/blob/f19731774b193681ecdb44c2aa0ee0dbb2cb4cbf/aya/src/sys/bpf.rs#L420)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

wait do we actually need to do this? we start with a mem::zeroed above. I mean it's fine to do it, but I think it is't necessary.
</blockquote></details>

That's true, let's just drop it.
___
*[`test/integration-test/Cargo.toml` line 30 at r3](https://reviewable.io/reviews/aya-rs/aya/1088#-OCNtgIo72gNVGqVoJ57:-OCS2DMCECCi9iPbaZhF:b7dcdyv) ([raw file](https://github.com/aya-rs/aya/blob/f19731774b193681ecdb44c2aa0ee0dbb2cb4cbf/test/integration-test/Cargo.toml#L30)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

as in another comment i think we can revert this, no need to test tokio itself
</blockquote></details>

Honestly I added the tokio test mostly as an example for people how to use BPF iterators with Tokio.

I removed the Tokio test, but I added an example with Tokio in the docstring in iter.rs.
___
*[`test/integration-test/src/tests/iter.rs` line 34 at r3](https://reviewable.io/reviews/aya-rs/aya/1088#-OCNt_UD3Kl9fUQQ42-e:-OCS5sRU8dpm5CpqpwKW:byr4ffv) ([raw file](https://github.com/aya-rs/aya/blob/f19731774b193681ecdb44c2aa0ee0dbb2cb4cbf/test/integration-test/src/tests/iter.rs#L34)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

do we get any value out of testing this? we're just testing tokio here.
</blockquote></details>

see above


<!-- Sent from Reviewable.io -->

2024-11-24 08:01 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1088)* status: 9 of 15 files reviewed, 12 unresolved discussions (waiting on @alessandrod and @tamird)

___
*[`aya/Cargo.toml` line 32 at r4](https://reviewable.io/reviews/aya-rs/aya/1088#-OCSB3WtCJO1msSNrwFx:-OCSB3WuA1-DJeLFbYsM:b-kjzaqb) ([raw file](https://github.com/aya-rs/aya/blob/2be594f73b5cd697660f16efcf4a5536cdceafd7/aya/Cargo.toml#L32)):*
> ```TOML
> # We are using the `fs` and `io-util` features of Tokio in the code example
> # in the documentation.
> tokio = { workspace = true, features = ["fs", "io-util", "rt"] }
> ```

To be clear - I removed the Tokio test, but I still want to keep some Tokio code example, so I decided to include it in docs.


<!-- Sent from Reviewable.io -->

2024-11-24 08:50 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1088)* status: 9 of 15 files reviewed, 12 unresolved discussions (waiting on @alessandrod and @tamird)

___
*[`aya/Cargo.toml` line 32 at r4](https://reviewable.io/reviews/aya-rs/aya/1088#-OCSB3WtCJO1msSNrwFx:-OCSMBs34NlYYr_uHAtZ:b6nwk3i) ([raw file](https://github.com/aya-rs/aya/blob/2be594f73b5cd697660f16efcf4a5536cdceafd7/aya/Cargo.toml#L32)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

To be clear - I removed the Tokio test, but I still want to keep some Tokio code example, so I decided to include it in docs.
</blockquote></details>

Or nevermind, clippy was complaining about this dep

https://github.com/aya-rs/aya/actions/runs/11994377992/job/33436346948?pr=1088

I removed it and I will just include the Tokio example in the book.


<!-- Sent from Reviewable.io -->

2024-11-24 11:35 UTC, tamird approved these changes
> Reviewed 3 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1088)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @alessandrod and @vadorovsky)

___
*[`aya/src/programs/iter.rs` line 96 at r1](https://reviewable.io/reviews/aya-rs/aya/1088#-OBzwtFX45JpDeWrAaSe:-OCSwVG42LJ0wQacclcE:b9ykumu) ([raw file](https://github.com/aya-rs/aya/blob/88d20a0c990a89f7f51e417a900953e43b96ebab/aya/src/programs/iter.rs#L96)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

No, because I'm not touching the other files in this PR. To be clear - I copy pasted that docstring from the XDP module. I think it deserves a separate PR.
</blockquote></details>

Sure. I think it can just be another commit in this PR.
___
*[`test/integration-test/Cargo.toml` line 30 at r3](https://reviewable.io/reviews/aya-rs/aya/1088#-OCNtgIo72gNVGqVoJ57:-OCSwykA7VVFqcTZ18jf:b-7axat0) ([raw file](https://github.com/aya-rs/aya/blob/f19731774b193681ecdb44c2aa0ee0dbb2cb4cbf/test/integration-test/Cargo.toml#L30)):*
<details><summary><i>Previously, vadorovsky (Michal Rostecki) wrote…</i></summary><blockquote>

Honestly I added the tokio test mostly as an example for people how to use BPF iterators with Tokio.

I removed the Tokio test, but I added an example with Tokio in the docstring in iter.rs.
</blockquote></details>

remove the extra features?


<!-- Sent from Reviewable.io -->

2024-11-24 15:26 UTC, tamird reviewed
> Reviewed 2 of 2 files at r6, 24 of 24 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1088)* status: 38 of 39 files reviewed, all discussions resolved (waiting on @alessandrod)



<!-- Sent from Reviewable.io -->

2024-11-24 15:27 UTC, tamird approved these changes
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/1088)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alessandrod)



<!-- Sent from Reviewable.io -->

2024-11-24 15:27 UTC, merged