aya: adds support for AF_XDP
aya-rs/aya pull request #1096
Opened 2024-11-26 13:37 UTC by vegkams

Contains user-space functionality for doing
AF_XDP socket interactions. Much is copy-paste
from xdpilone, but with higher-level abstractions
put on top.

It should be usable at a high level without requiring unsafe code on the library user's side. The more
low-level control is still available, for power users who need that level of control (and accept the safety implications).

Fixes: #507

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1096)

2024-11-26 15:31 UTC, dave-tucker requested changes
Hi and thanks for your contribution!
I'm yet to take a look at the code but something in your commit message set off alarm bells.

> Much is copy-paste from xdpilone, but with higher-level abstractions put on top.

[xdpilone](https://github.com/HeroicKatora/xdpilone) is licensed under the [EUPL-1.2](https://choosealicense.com/licenses/eupl-1.2/) whereas Aya is Apache 2.0 / MIT.

Unfortunately I don't think we can accept this PR as the license terms are incompatible.
I will get clarification on this, but for now adding a -1 so we don't proceed with merging as-is.

2024-11-26 16:22 UTC, vegkams commented
@dave-tucker Ok, I wasn't aware of the licensing incompatibility issue, but that's on me I guess. I can rip out the xdpilone parts, shouldn't be too much work.

2024-11-27 09:57 UTC, Tuetuopay commented
This may get quite hard. I don't know how hard the EUPL-1.2 is, but you may be contaminated by it. And since you mentioned xdpilone, you may not be eligible anymore for any cleanroom implementation. IANAL though.

2024-11-27 11:24 UTC, vegkams commented
Ok. I'm sorry for my mistake, it was stupid of me to not check the license. 

Would be nice to get clarification on whether or not I'm ineligible for a cleanroom implementation in the future, as I would really like this feature to be available in Aya. Or if someone else plans on implementing it in the near future.

2024-12-02 06:02 UTC, esemeniuc commented
I would also love to see this as part of aya. If not possible, a personal fork of aya would be appreciated

2024-12-02 06:51 UTC, alessandrod commented
> This may get quite hard. I don't know how hard the EUPL-1.2 is, but you may be contaminated by it. And since you mentioned xdpilone, you may not be eligible anymore for any cleanroom implementation. IANAL though.

I mean, the actual functionality is provided by the kernel, I haven't looked at xdpilone (nor at the code in this PR yet) but I imagine that it's 99% API and so would be our impl, so unless we rebuild the same API (which would make no sense), I don't think there's much to worry about. There's only so many ways you can use the underlying API (provided by the kernel), and the whole point of this project is to make an API that would fit with the rest of the aya APIs, so presumably very different from xdpilone?

2025-10-02 19:33 UTC, vadorovsky commented
Given no activity and concerns about licensing, I'm closing this PR.

2025-10-02 19:33 UTC, closed without merging

2025-12-04 18:41 UTC, OzzyKampha commented
Still want this

2025-12-09 11:31 UTC, OliverGavin commented
I'm experimenting in my free time to make an aya focused xsk crate which I hope to be able to share in the next month or so. It will be stand alone at first but would be great to get it merged into aya once properly tested. I'd love if a few people were willing to test it too.

2025-12-09 11:34 UTC, alessandrod commented
I have an aya based AF_XDP impl currently living in the agave-xdp crate which I’m planning to move back to aya soon

2025-12-13 17:51 UTC, OzzyKampha commented
I would love test them both