aya-bpf: Add docs for the main lib annd few map types
aya-rs/aya pull request #244
Opened 2022-04-12 10:27 UTC by vadorovsky

This change adds a summary of the aya-bpf lib and docs for:

* hash map
* lpm trie
* perf event arrays

Signed-off-by: Michal Rostecki <vadorovsky@gmail.com>

2022-04-17 11:01 UTC, alessandrod requested changes
Thanks so much for getting this started!

See my comments. I think the reference docs are generally ok, but I think we need better examples.

I wouldn't worry about the module level documentation too much for now. I think we'll have to be very thorough when we get to that, and possibly cross reference examples with the user space API. I think that's going to be a lot of work so we can probably do it separately/at the end once everything else is in place.

2022-12-19 22:34 UTC, shaneutt reviewed
Overall Looking good: this significantly improves documentation.

I think for docs that could simply use more elaboration it may be fair to create follow-up issues as `good-first-issues` for newcomers to get a chance to make a small change. However I think there's a couple examples here that need more explanation, or perhaps some re-working before we merge.

2022-12-19 22:34 UTC, shaneutt commented on bpf/aya-bpf/src/lib.rs
> +//! [compile once, run everywhere solution](https://facebookmicrosites.github.io/bpf/blog/2020/02/19/bpf-portability-and-co-re.html),
This link is solid, I did some scouring and was really surprised to find that https://docs.kernel.org basically has nothing on CO-RE except for a couple mentions in the FAQ. Not something we need to figure out for this PR, but perhaps this is an opportunity for us: if we add a really solid CO-RE section to our own documentation we can probably capture a lot of traffic from interested eBPF developers who are just looking for a "landing page" for learning about what CO-RE is and how it actually works under the hood.

I've created https://github.com/aya-rs/book/issues/79 as a follow-up for this.

2022-12-19 22:34 UTC, shaneutt commented on bpf/aya-bpf/src/maps/hash_map.rs
> +/// static mut MY_MAP: HashMap<u32, u32> = HashMap::with_max_entries(1024, 0);
Perhaps given the limits on everyone's time, and the fact that this PR ended up going stale would suggest that follow-up items for expanding this documentation would be good: e.g. we could accept this as-is for now as "better than nothing" and then follow-up issues to extend the documentation further could be created, tagged as `good-first-issue` so as to provide some smaller, simple places new contributors could jump in and contribute?

2022-12-19 22:34 UTC, shaneutt commented on bpf/aya-bpf/src/maps/hash_map.rs
> +/// # unsafe fn try_test(ctx: &LsmContext) -> Result<i32, i32> {
+1 if I'm understanding the original intention here it was to try and "scare" the caller of the code into noticing that what they're doing is unsafe, and I get that. However in Rust it's more idiomatic to "wrap" the unsafe functionality with code that carefully considers and accounts for all the potential safety issues and then provide a safe interface to that functionality.

Given my impression that the intention here was meant to alert the reader of the safety issues, I think a good compromise here would be to place the unsafe around the exact thing it needs to be around but make the function itself safe as @alessandrod suggests, but THEN add comments to that code which explains _why_ we must currently do that as unsafe (extra credit if there's an open issue we can link to which tracks making that code safe in the future).

2022-12-19 22:34 UTC, shaneutt commented on bpf/aya-bpf/src/maps/hash_map.rs
> +    /// if let Some(mut value) = MY_MAP.get_mut(&key) {
+1 we should be careful about examples that might not have clear implications to code readers, as example code often unfortunately finds it's way into production.

2023-03-06 11:23 UTC, vadorovsky commented
Closing it. I will submit smaller PR-s per map type every day. Drowning myself in attempt to document everything at once isn't really working.

2023-03-06 11:24 UTC, closed without merging