aya-log: Make tokio optional
aya-rs/aya pull request #396
Opened 2022-09-23 12:24 UTC by vadorovsky

Use tokio only when `async_tokio` feature is enabled, otherwise use `std::thread`.

Signed-off-by: Michal Rostecki <vadorovsky@gmail.com>

2022-10-11 13:23 UTC, dave-tucker approved these changes
LGTM

2022-11-09 00:23 UTC, alessandrod requested changes
This needs more work. As it is now it'll spin loop when using threads, using all the available CPUs :D 

We need to make this sleep, and in the process probably rework the API so that the caller can optionally read from its own threads (the threads are created from the caller - aya-log just provides an interface that can be polled)

2022-11-09 00:23 UTC, alessandrod commented on aya-log/src/lib.rs
> +                let events = buf.read_events(&mut buffers).unwrap();
this spin loops without sleeping

2022-12-13 12:35 UTC, vadorovsky commented
@alessandrod Thanks! I will open a new PR for that, since it's broken enough that doesn't make sense to rebase.

2022-12-13 12:35 UTC, closed without merging