Avoid integer to pointer casts
aya-rs/aya pull request #398
Opened 2022-09-30 05:15 UTC by vadorovsky

Instead, operate on byte slices if possible. If we have only `usize`, then use the Strict Provenance API[0][1] instead.

[0] https://doc.rust-lang.org/nightly/std/ptr/index.html#strict-provenance
[1] https://crates.io/crates/sptr

Signed-off-by: Michal Rostecki <vadorovsky@gmail.com>

2022-09-30 14:00 UTC, astoycos approved these changes
Miri now passes locally with these fixes and I've also included them here https://github.com/aya-rs/aya/pull/397 

Thanks!

2022-09-30 15:10 UTC, dave-tucker requested changes

2022-09-30 15:10 UTC, dave-tucker commented on aya/src/obj/mod.rs
>  pub(crate) fn copy_instructions(data: &[u8]) -> Result<Vec<bpf_insn>, ParseError> {
```rust
pub(crate) fn copy_instructions(data: &[u8]) -> Result<Vec<bpf_insn>, ParseError> {
    if data.len() % mem::size_of::<bpf_insn>() > 0 {
        return Err(ParseError::InvalidProgramCode);
    }
    let instructions = data.chunks_exact(mem::size_of::<bpf_insn>())
        .map(|d| unsafe {
            ptr::read_unaligned(d.as_ptr() as *const bpf_insn)
        })
        .collect::<Vec<_>>();
    Ok(instructions)
}
```

2022-10-03 20:51 UTC, alessandrod approved these changes

2022-10-03 20:52 UTC, merged