add list, run cli flags to integration tests.
aya-rs/aya pull request #409
Opened 2022-10-10 17:36 UTC by abhijeetbhagat

fixes: #338

2022-10-10 21:09 UTC, vadorovsky commented on test/integration-test/src/main.rs
> +                            info!("Running {}", t.name);
nit: Maybe let's move

```rust
info!("Running {}", t.name);
if let Err(e) = (t.test_fn)() {
    panic!("{}", e)
}
```

to some common function/macro, to not repeat that twice.

2022-10-11 09:51 UTC, vadorovsky commented
Lint check fails.

2022-10-11 11:18 UTC, abhijeetbhagat commented
running `cargo clippy --workspace --exclude integration-test -- --deny warnings` on my system doesn't give any warnings.

2022-10-11 11:28 UTC, vadorovsky commented
That's because CI is running with Rust nightly. You are going to see those errors when you do:

```
cargo +nightly clippy --workspace --exclude integration-test -- --deny warnings
```

2022-10-11 11:54 UTC, abhijeetbhagat commented
nothing:
```
(rust:nightly) ↪ cargo +nightly clippy --workspace --exclude integration-test -- --deny warnings
   Compiling aya-bpf-cty v0.2.1 (/home/abhi/code/aya/bpf/aya-bpf-cty)
   Compiling aya-bpf-bindings v0.1.0 (/home/abhi/code/aya/bpf/aya-bpf-bindings)
   Compiling aya-bpf v0.1.0 (/home/abhi/code/aya/bpf/aya-bpf)
   Compiling aya-bpf-macros v0.1.0 (/home/abhi/code/aya/aya-bpf-macros)
   Compiling aya v0.11.0 (/home/abhi/code/aya/aya)
    Checking aya-tool v0.1.0 (/home/abhi/code/aya/aya-tool)
    Checking xtask v0.1.0 (/home/abhi/code/aya/xtask)
    Checking integration-test-macros v0.1.0 (/home/abhi/code/aya/test/integration-test-macros)
    Checking integration-ebpf v0.1.0 (/home/abhi/code/aya/test/integration-ebpf)
    Checking aya-log-common v0.1.12-dev.0 (/home/abhi/code/aya/aya-log-common)
    Checking aya-log v0.1.12-dev.0 (/home/abhi/code/aya/aya-log)
    Checking aya-log-parser v0.1.11-dev.0 (/home/abhi/code/aya/aya-log-parser)
    Checking aya-log-ebpf-macros v0.1.0 (/home/abhi/code/aya/aya-log-ebpf-macros)
    Checking aya-log-ebpf v0.1.0 (/home/abhi/code/aya/bpf/aya-log-ebpf)
    Finished dev [unoptimized + debuginfo] target(s) in 6.31s
abhi at hyperion in ~/c/aya on integration-tests-cli-options [✓]
(rust:nightly) ↪ rustc --version
rustc 1.66.0-nightly (f83e0266c 2022-10-03)
```

2022-10-11 11:58 UTC, vadorovsky commented
Try `rustup update`, there is a newer version of nightly available (you have `f83e0266c 2022-10-03`, the newest one is `3cdf1ab25 2022-10-07`).

2022-10-11 12:03 UTC, abhijeetbhagat commented
ok, i get those warnings now. should i fix them all in the same PR?

2022-10-11 12:05 UTC, vadorovsky commented
Maybe do a separate one, since those warnings are not related to your changes and they appear on the current `main` branch too.

2022-10-11 13:20 UTC, vadorovsky commented
I merged the lint PR. You can rebase this one and I will merge it once CI passes.

2022-10-11 13:20 UTC, dave-tucker requested changes
Added some comments to help preserve the existing behaviour and avoid changes to GitHub Workflows and/or xtask.

You might even be able to simply the command match arms further with something like:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5ca0ad4d05a8d71393a4acfa2c4fc7e9

2022-10-11 13:20 UTC, dave-tucker commented on test/integration-test/src/main.rs
> +    command: Command,
```rust
    command: Option<Command>,
```

2022-10-11 13:20 UTC, dave-tucker commented on test/integration-test/src/main.rs
> +struct Options {
```rust
struct Cli {
```

2022-10-11 13:20 UTC, dave-tucker commented on test/integration-test/src/main.rs
> +#[derive(Debug, Parser)]
```rust
#[clap(author, version, about, long_about = None)]
#[clap(propagate_version = true)]
```

2022-10-11 13:20 UTC, dave-tucker commented on test/integration-test/src/main.rs
> +        Command::Run(opts) => match opts.tests {
```rust
        Some(Command::Run(opts)) => match opts.tests {
```

2022-10-11 13:20 UTC, dave-tucker commented on test/integration-test/src/main.rs
> +        Command::List => {
```rust
        Some(Command::List) => {
```

2022-10-11 13:20 UTC, dave-tucker commented on test/integration-test/src/main.rs
>          }
```rust
        None => {
            for t in inventory::iter::<IntegrationTest> {
                exec_test!(t)
            }
        }
```

2022-10-11 13:20 UTC, dave-tucker commented on test/integration-test/src/main.rs
> +    let cmd = Command::parse();
```rust
Cli.parse()
```

2022-10-11 13:20 UTC, dave-tucker commented on test/integration-test/src/main.rs
> +    match cmd {
```rust
   match &cli.command {
```

2022-10-11 22:06 UTC, vadorovsky approved these changes

2022-10-13 09:00 UTC, dave-tucker approved these changes
lgtm thanks @abhijeetbhagat

2022-10-13 09:00 UTC, merged