Remove libbpf dependency from relocation tests
aya-rs/aya pull request #485
Opened 2023-01-09 14:56 UTC by MatteoNardi

Simplifiy the relocation tests build process by removing the need for libbpf at runtime.
Its usage is replaced with local `__builtin_*` attributes.
This removes the need for the `LIBBPF_INCLUDE` env variable.

An alternative solution would be to create a `libbpf_polyfill.h` file with the needed definitions (and explain why the file is needed) and include just that from the relocation tests. Let me know if you'd prefer it that way.

2023-01-10 03:44 UTC, vadorovsky requested changes
Thanks! It looks good to me and I think using `__builtin_preserve_access_index` is a good solution.

But please also update README:

https://github.com/aya-rs/aya/blob/main/test/README.md

And remove this CLI option:

https://github.com/aya-rs/aya/blob/055d94f58be4f80ada416b99278a22f600c71285/xtask/src/run.rs#L19-L21

2023-01-10 07:59 UTC, MatteoNardi commented
I didn't add that option in my latest PR: all the other tests still require libbpf! 
I removed the need for it just in relocation tests because it required the env variable hack and an extra build in run.sh

2023-01-10 13:45 UTC, vadorovsky commented
Oh, ok, sorry for misunderstanding.

2023-01-10 13:45 UTC, vadorovsky approved these changes

2023-01-14 09:21 UTC, alessandrod approved these changes
Awesome thank you!

2023-01-14 09:21 UTC, merged