aya: add a safe wrapper for 'BPF_TASK_FD_QUERY' logic
aya-rs/aya pull request #492
Opened 2023-01-17 10:49 UTC by lucab

This add bindings for the `bpf_task_fd_type` FFI type, and then add a safe wrapper for the `BPF_TASK_FD_QUERY` logic.

2023-01-17 10:53 UTC, lucab commented
CI is failing because of https://github.com/aya-rs/aya/issues/490.

2023-01-25 12:19 UTC, lucab commented
Rebased on `main`, CI is now green.

2025-03-05 20:58 UTC, tamird requested changes
@lucab I have rebased this and made sure clippy passes. The codegen changes were no longer needed. However, this needs a test.

2025-03-24 15:07 UTC, tamird commented
I'm going to close this for now. Please send a new PR if you intend to land this.

2025-03-24 15:07 UTC, closed without merging