Add support for PerfEvent programs
aya-rs/aya pull request #52
Opened 2021-08-13 21:45 UTC by mstange

This seems to work, in my very basic tests. I would appreciate if somebody else could push it over the finish line, because I'm not sure how much time I'll be able to spend on this.

Things that need to be tweaked:

 - Public API: I'm not sure if the "PerfEvent" name is appropriate in all the cases. It clashes a little bit with the existing name `PerfEventBuffer`.
 - Public API: The arguments `perf_type` and `config` are currently exposed as u32 and u64. At least for `perf_type` it would be preferable to use the `perf_type_id` enum, but it wasn't straightforward to me how to make that type public.
 - Comments: I don't have a deep understanding of how all of this works, and who determines what kinds of perf events exist (kernel version? CPU model? user privileges?) so I left this mostly blank.

2021-08-22 09:59 UTC, alessandrod requested changes
Thanks a lot for this! It's 99% done, let me know if you're going to do the changes or if you want me to pick it up :)

2021-08-22 09:59 UTC, alessandrod commented on aya/src/programs/perf_event.rs
> +/// TODO: minimum kernel version?
4.9

2021-08-22 09:59 UTC, alessandrod commented on aya/src/programs/perf_event.rs
> +        perf_type: u32, // perf_type_id
I think we should probably define a `PerfTypeId` enum here instead of re-exporting an auto generated binding of `perf_type_id`

2021-08-22 09:59 UTC, alessandrod commented on aya/src/programs/perf_event.rs
> +///         0, /* PERF_COUNT_SW_CPU_CLOCK */
We should generate bindings for ids and flags and whatever else can be passed as config

2021-08-22 09:59 UTC, alessandrod commented on aya/src/programs/perf_event.rs
> +///
We should generate bindings for all these https://github.com/torvalds/linux/blob/a0e31f3a38e77612ed8967aaad28db6d3ee674b5/include/uapi/linux/perf_event.h#L60

2021-08-22 10:03 UTC, alessandrod commented
> This seems to work, in my very basic tests. I would appreciate if somebody else could push it over the finish line, because I'm not sure how much time I'll be able to spend on this.
> 
> Things that need to be tweaked:
> 
>     * Public API: I'm not sure if the "PerfEvent" name is appropriate in all the cases. It clashes a little bit with the existing name `PerfEventBuffer`.

I think the name is fine. It's unfortunate that the perf API is used for a bunch of barely related things, but it's how it is.


> 
>     * Public API: The arguments `perf_type` and `config` are currently exposed as u32 and u64. At least for `perf_type` it would be preferable to use the `perf_type_id` enum, but it wasn't straightforward to me how to make that type public.

I think we should generate the bindingsd for `perf_type_id`, but then export a hand written `PerfTypeId` enum with snake case etc. `perf_event_id` hasn't been changed in 9 years so it's not going to be much of a maintenance burden 😅


>     * Comments: I don't have a deep understanding of how all of this works, and who determines what kinds of perf events exist (kernel version? CPU model? user privileges?) so I left this mostly blank.

I think it's a combination of all 3. As a start I'd be fine with generating bindings for the common ids defined in `perf.h` and pointing to those in the doc.

2021-08-22 14:19 UTC, mstange commented
Thanks for the review! I'm planning to address the comments during the week. If, by the end of next weekend, I still haven't gotten to it, I'll hand it off to you.

2021-09-20 10:48 UTC, alessandrod commented
I have tweaked this a bit as per review and just merged it. Thanks again for working on it!

I wasn't able to improve the docs much, since well, the perf API is a black box. I have created an issue about improving the docs https://github.com/aya-rs/aya/issues/60

2021-09-20 10:48 UTC, closed without merging

2021-09-20 16:24 UTC, mstange commented
Perfect, thanks!