ebpf: Call `bpf_probe_read` on `*const T` BTF arguments
aya-rs/aya pull request #543
Opened 2023-03-14 14:00 UTC by vadorovsky

It's necessary to call `bpf_probe_read` not only for pointers retrieved from `PtRegs`, but also from BTF arguments.

`bpf_probe_read` might return an error, so the return type of `.arg()` methods in contexts handling BTF arguments changes from `Self` to `Option<Self>`. `None` is returned when `bpf_probe_read` call is not successful.

Fixes: #542

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/543)

2023-08-25 23:49 UTC, tamird commented
@vadorovsky mind rebasing?

2024-11-21 11:51 UTC, tamird commented
I rebased this, but I think the tests need more work.

2024-11-21 11:52 UTC, tamird requested changes
> Reviewed 7 of 9 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/543)* status: all files reviewed, 2 unresolved discussions (waiting on @vadorovsky)

___
*[`test/integration-test/src/tests/args.rs` line 1 at r2](https://reviewable.io/reviews/aya-rs/aya/543#-OCDZKH6DqzyCLi61BGM:-OCDZKH6DqzyCLi61BGN:bqhp9yg) ([raw file](https://github.com/aya-rs/aya/blob/497d3e333c94cc3ad78451a43cda2f48959b7b33/test/integration-test/src/tests/args.rs#L1)):*
> ```XML
> use aya::{
> ```

not clear to me what we're testing here
___
*[`test/integration-ebpf/src/args.rs` line 11 at r2](https://reviewable.io/reviews/aya-rs/aya/543#-OCDZDSvBK9OIoGLTzU_:-OCDZDSvBK9OIoGLTzUa:b-w6qh30) ([raw file](https://github.com/aya-rs/aya/blob/497d3e333c94cc3ad78451a43cda2f48959b7b33/test/integration-ebpf/src/args.rs#L11)):*
> ```XML
> #[kprobe]
> pub fn kprobe_vfs_write(ctx: ProbeContext) {
>     let _: Option<usize> = ctx.arg(3);
> ```

what exactly are we testing here?


<!-- Sent from Reviewable.io -->

2024-11-21 14:46 UTC, tamird reviewed
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/543)* status: all files reviewed, 2 unresolved discussions (waiting on @vadorovsky)



<!-- Sent from Reviewable.io -->

2025-01-08 17:57 UTC, vadorovsky commented
After giving it some more thought, I'm closing it.

My initial intention behind the PR was handling the `FEntry` arguments in a similar way as we handle `KProbe` arguments. In case of `KProbe`, we call `bpf_probe_read` on each accessed register:

https://github.com/aya-rs/aya/blob/f34d355d7d70f8f9ef0f0a01a4338e50cf0080b4/ebpf/aya-ebpf/src/args.rs#L107-L118

We don't do that for BTF arguments:

https://github.com/aya-rs/aya/blob/f34d355d7d70f8f9ef0f0a01a4338e50cf0080b4/ebpf/aya-ebpf/src/args.rs#L41-L52

Therefore, when writing an `FProbe`, you often need to `bpf_probe_read_kernel` some pointers. For example, this program works:

```rust
#[fentry(function = "vfs_write")]
pub fn vfs_write(ctx: FEntryContext) -> u32 {
    match try_vfs_write(ctx) {
        Ok(_) => 0,
        Err(ret) => ret,
    }
}

fn try_vfs_write(ctx: FEntryContext) -> Result<(), u32> {
    let size: size_t = unsafe { ctx.arg(2) };
    let pos: *const i64 = unsafe { ctx.arg(3) };
    let pos = unsafe { bpf_probe_read_kernel(pos).map_err(|_| 1u32)? };
    info!(&ctx, "size={},pos={}", size, pos);
    Ok(())
}
```

But without `bpf_probe_read_kernel`:

```rust
    let pos: *const i64 = unsafe { ctx.arg(3) };
    let pos = unsafe { *pos };
```

It triggers the verifier error:

```
Error: the BPF_PROG_LOAD syscall failed. Verifier output: 0: R1=ctx() R10=fp0
0: (bf) r6 = r1                       ; R1=ctx() R6_w=ctx()
1: (79) r1 = *(u64 *)(r6 +16)         ; R1_w=scalar() R6_w=ctx()
2: (7b) *(u64 *)(r10 -16) = r1        ; R1_w=scalar(id=1) R10=fp0 fp-16_w=scalar(id=1)
3: (79) r1 = *(u64 *)(r6 +24)         ; R1_w=scalar() R6_w=ctx()
4: (79) r1 = *(u64 *)(r1 +0)
R1 invalid mem access 'scalar'
verification time 47 usec
stack depth 16+0+0+0
```

My initial though was - *let's make user's life easier and just do `bpf_probe_read` behind the scenes`.

But not I realized that:

* libbpf is not doing that for BTF argument based programs.
* The situation is not really analogic here (we are reading BTF arguments, not `pt_regs` pointer fields).
* Do we really care some much about requiring usage of `bpf_probe_read`? :thinking: 

So I'm closing the PR.

2025-01-08 17:57 UTC, closed without merging