Miscellaneous fixes to allow running integration tests in bpf-linker
aya-rs/aya pull request #641
Opened 2023-07-09 23:08 UTC by tamird

See individual commits and https://github.com/aya-rs/bpf-linker/pull/69.

2023-07-09 23:50 UTC, tamird commented
cc @ajwerner

2023-07-10 03:35 UTC, ajwerner approved these changes
LGTM

2023-07-10 14:02 UTC, ajwerner approved these changes

2023-07-10 18:01 UTC, vadorovsky commented on test/integration-test/tests/smoke.rs
> +    if kernel_version < KernelVersion::new(5, 18, 0) {
Let's maybe address that in another PR, but it would be nice to have some basic XDP test which can run on kernels older than 5.18.0.

2023-07-10 18:08 UTC, vadorovsky commented on test/integration-test/tests/btf_relocations.rs
> +        }
Ah, crap. Alright, then maybe let's just do our wrapper handling `status.code()`?

2023-07-10 18:18 UTC, tamird commented on xtask/src/docs/mod.rs
> +    match status.code() {
done

2023-07-10 18:18 UTC, tamird commented on xtask/src/docs/mod.rs
> +    match status.code() {
done

2023-07-10 18:18 UTC, tamird commented on xtask/src/build_test.rs
> +    match status.code() {
done

2023-07-10 18:18 UTC, tamird commented on xtask/src/build_ebpf.rs
> +    match status.code() {
done

2023-07-10 18:18 UTC, tamird commented on xtask/src/build_ebpf.rs
> +    match status.code() {
done

2023-07-10 18:18 UTC, tamird commented on xtask/src/build_ebpf.rs
> +    match status.code() {
done

2023-07-10 18:19 UTC, tamird commented on test/integration-test/tests/btf_relocations.rs
> +    let mut cmd = Command::new("clang");
can't share the implementation here because it's in xtask, and it doesn't seem worth it to extract a helper here for 2 callers.

2023-07-10 18:19 UTC, tamird commented on test/integration-test/tests/btf_relocations.rs
> +        }
done

2023-07-10 18:21 UTC, vadorovsky approved these changes

2023-07-10 19:10 UTC, dave-tucker requested changes
Some things to clarify here before merge

2023-07-10 19:26 UTC, tamird commented on aya/Cargo.toml
> +procfs = "0.15.1"
Done. Looks pretty active to me.

2023-07-10 19:26 UTC, tamird commented on aya/src/bpf.rs
> +        bpf_load_btf(raw_btf.as_slice(), logger, VerifierLogLevel::default())
Good point, done.

2023-07-10 19:26 UTC, tamird commented on aya/src/programs/mod.rs
> +            verifier_log_level: VerifierLogLevel::default(),
There's no BpfLoader in hand here. Where do you suggest I get one?

2023-07-10 19:26 UTC, tamird commented on aya/src/programs/mod.rs
> +            let procfs::KernelVersion {
Done, replaced the aya KernelVersion with Option<u32>

2023-07-10 19:26 UTC, tamird commented on test/integration-ebpf/src/pass.rs
> +// Note: the `frags` attribute causes this probe to be incompatible with kernel versions < 5.18.0.
Sure, please fix in another PR.

2023-07-10 19:26 UTC, tamird commented on test/integration-test/tests/load.rs
> +    if kernel_version < KernelVersion::new(5, 18, 0) {
Yes, I realize, but I chose not to fix this here. Please fix it in another PR.

2023-07-10 19:26 UTC, tamird commented on test/integration-test/tests/smoke.rs
> +        eprintln!("skipping test on kernel {kernel_version:?}, support for BPF_F_XDP_HAS_FRAGS was added in 5.18.0; see https://github.com/torvalds/linux/commit/c2f2cdb");
Indeed.

2023-07-10 19:33 UTC, dave-tucker commented on aya/src/programs/mod.rs
> +            verifier_log_level: VerifierLogLevel::default(),
I would suggest plumbing in the `verifier_log_level: VerifierLogLevel` as an argument to this function...
If `BpfLoader` is never available in the call stack, then it should probably be part of the public API.

The option that's less work is to keep the existing behaviour and use `VerifierLogLevel::None`

2023-07-10 19:44 UTC, tamird commented on aya/src/programs/mod.rs
> +            verifier_log_level: VerifierLogLevel::default(),
Plumbed it all the way to `from_pin`, which is a public API. There's no loader object in sight.

Would you like me to break the public API?

2023-07-10 20:18 UTC, dave-tucker commented on aya/src/programs/mod.rs
> +            verifier_log_level: VerifierLogLevel::default(),
Ah okay, no need to expose that in `from_pin`, You can safely use `VerifierLogLevel::None` then, not `default()`.
Programs are already loaded to the kernel so you won't get any verifier logs loading from pin in this case.

2023-07-10 20:20 UTC, tamird commented on aya/src/programs/mod.rs
> +            verifier_log_level: VerifierLogLevel::default(),
If it's all the same to you, I'd rather leave `default` here. If there aren't verifier logs to be had, then it doesn't matter. Agreed?

2023-07-10 21:16 UTC, dave-tucker approved these changes
LGTM

2023-07-10 21:22 UTC, merged