cargo: Define dependencies on the workspace level
aya-rs/aya pull request #667
Opened 2023-07-17 20:18 UTC by vadorovsky

This way we will avoid version mismatches and make differences in features across our crates clearer.

2023-07-17 21:02 UTC, tamird requested changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/667)* status: all files reviewed, 3 unresolved discussions (waiting on @vadorovsky)

___
*[`Cargo.toml` line 43 at r1](https://reviewable.io/reviews/aya-rs/aya/667#-N__dfjU3QZQfNlxzRji:-N__dfjU3QZQfNlxzRjj:b-j5jkoq) ([raw file](https://github.com/aya-rs/aya/blob/4dfb9fa2b1bb97f4a3d6aa21907fe22856c11938/Cargo.toml#L43)):*
> ```TOML
> ]
> 
> [workspace.dependencies]
> ```

if one of these becomes unused, will anything inform us?
___
*[`Cargo.toml` line 47 at r1](https://reviewable.io/reviews/aya-rs/aya/667#-N__dr3KDSqxIsFPUXJ-:-N__dr3KDSqxIsFPUXJ0:bq7sxut) ([raw file](https://github.com/aya-rs/aya/blob/4dfb9fa2b1bb97f4a3d6aa21907fe22856c11938/Cargo.toml#L47)):*
> ```TOML
> assert_matches = "1.5.0"
> async-io = { version = "1.3" }
> aya = { path = "aya", version = "0.11.0", features=["async_tokio"] }
> ```

is it necessary to list features here? seems to me like we just want versions here since each user crate should specify used features for itself
___
*[`Cargo.toml` line 77 at r1](https://reviewable.io/reviews/aya-rs/aya/667#-N__e59T9nYTvIot-AHQ:-N__e59T9nYTvIot-AHR:b-judso2) ([raw file](https://github.com/aya-rs/aya/blob/4dfb9fa2b1bb97f4a3d6aa21907fe22856c11938/Cargo.toml#L77)):*
> ```TOML
> testing_logger = "0.1.1"
> thiserror = "1"
> tokio = { version = "1.24.0" }
> ```

this should be default-features = false, i think? i'm not sure how features work in workspace dependencies, perhaps they are ignored?


<!-- Sent from Reviewable.io -->

2023-07-17 21:05 UTC, tamird requested changes
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/667)* status: all files reviewed, 3 unresolved discussions (waiting on @vadorovsky)

___
*[`Cargo.toml` line 77 at r1](https://reviewable.io/reviews/aya-rs/aya/667#-N__e59T9nYTvIot-AHQ:-N__eyNw1G8JgjLJR9XB:b-h1rso1) ([raw file](https://github.com/aya-rs/aya/blob/4dfb9fa2b1bb97f4a3d6aa21907fe22856c11938/Cargo.toml#L77)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this should be default-features = false, i think? i'm not sure how features work in workspace dependencies, perhaps they are ignored?
</blockquote></details>

yeah, this is causing cargo to log warnings:
```
warning: /home/tamird/src/aya/aya-obj/Cargo.toml: `default-features` is ignored for thiserror, since `default-features` was not specified for `workspace.dependencies.thiserror`, this could become a hard error in the future
warning: /home/tamird/src/aya/test/integration-test/Cargo.toml: `default-features` is ignored for tokio, since `default-features` was not specified for `workspace.dependencies.tokio`, this could become a hard error in the future
```


<!-- Sent from Reviewable.io -->

2023-07-17 21:30 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/667)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @tamird)

___
*[`Cargo.toml` line 43 at r1](https://reviewable.io/reviews/aya-rs/aya/667#-N__dfjU3QZQfNlxzRji:-N__jPE1BtvUZA8f8aG5:bblh5x4) ([raw file](https://github.com/aya-rs/aya/blob/4dfb9fa2b1bb97f4a3d6aa21907fe22856c11938/Cargo.toml#L43)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

if one of these becomes unused, will anything inform us?
</blockquote></details>

I checked and cargo-udeps doesn't inform about unused workspace dependencies. :/ I will keep thinking about the solution.
___
*[`Cargo.toml` line 47 at r1](https://reviewable.io/reviews/aya-rs/aya/667#-N__dr3KDSqxIsFPUXJ-:-N__jiIxBS1yNrghNU3O:bnj8jhc) ([raw file](https://github.com/aya-rs/aya/blob/4dfb9fa2b1bb97f4a3d6aa21907fe22856c11938/Cargo.toml#L47)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is it necessary to list features here? seems to me like we just want versions here since each user crate should specify used features for itself
</blockquote></details>

It's not, we can always list features in user crates.

My idea was to define them here if we know that we are going to use those features in all crates and keep only single feature lists which differ in user crates. To not repeat the feature list over everywhere when not necessary.
___
*[`Cargo.toml` line 77 at r1](https://reviewable.io/reviews/aya-rs/aya/667#-N__e59T9nYTvIot-AHQ:-N__kiVV4J4EiPm6Wike:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/4dfb9fa2b1bb97f4a3d6aa21907fe22856c11938/Cargo.toml#L77)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

yeah, this is causing cargo to log warnings:
```
warning: /home/tamird/src/aya/aya-obj/Cargo.toml: `default-features` is ignored for thiserror, since `default-features` was not specified for `workspace.dependencies.thiserror`, this could become a hard error in the future
warning: /home/tamird/src/aya/test/integration-test/Cargo.toml: `default-features` is ignored for tokio, since `default-features` was not specified for `workspace.dependencies.tokio`, this could become a hard error in the future
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-17 21:42 UTC, tamird requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/667)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @vadorovsky)

___
*[`Cargo.toml` line 43 at r1](https://reviewable.io/reviews/aya-rs/aya/667#-N__dfjU3QZQfNlxzRji:-N__nKA2DVgRpXjR2p2_:b-8hq1i9) ([raw file](https://github.com/aya-rs/aya/blob/4dfb9fa2b1bb97f4a3d6aa21907fe22856c11938/Cargo.toml#L43)):*
<details><summary><i>Previously, vadorovsky wrote…</i></summary><blockquote>

I checked and cargo-udeps doesn't inform about unused workspace dependencies. :/ I will keep thinking about the solution.
</blockquote></details>

Does cargo machete do any better? https://blog.benj.me/2022/04/27/cargo-machete/
___
*[`Cargo.toml` line 47 at r1](https://reviewable.io/reviews/aya-rs/aya/667#-N__dr3KDSqxIsFPUXJ-:-N__m_j2AWiRmWSbmza4:b-phrjwk) ([raw file](https://github.com/aya-rs/aya/blob/4dfb9fa2b1bb97f4a3d6aa21907fe22856c11938/Cargo.toml#L47)):*
<details><summary><i>Previously, vadorovsky wrote…</i></summary><blockquote>

It's not, we can always list features in user crates.

My idea was to define them here if we know that we are going to use those features in all crates and keep only single feature lists which differ in user crates. To not repeat the feature list over everywhere when not necessary.
</blockquote></details>

I think it'd be better to mark everything here `default-features = false` and let downstream crates request the features they want. Otherwise you risk introducing unintended features (and dependencies) downstream.


<!-- Sent from Reviewable.io -->

2023-07-17 21:48 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/667)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @tamird)

___
*[`Cargo.toml` line 43 at r1](https://reviewable.io/reviews/aya-rs/aya/667#-N__dfjU3QZQfNlxzRji:-N__ovaa2ySqhcQEEGZB:b-5tqkmc) ([raw file](https://github.com/aya-rs/aya/blob/4dfb9fa2b1bb97f4a3d6aa21907fe22856c11938/Cargo.toml#L43)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Does cargo machete do any better? https://blog.benj.me/2022/04/27/cargo-machete/
</blockquote></details>

It doesn't :(
___
*[`Cargo.toml` line 47 at r1](https://reviewable.io/reviews/aya-rs/aya/667#-N__dr3KDSqxIsFPUXJ-:-N__oR8L4GuWq10FY2Rw:b-orumjy) ([raw file](https://github.com/aya-rs/aya/blob/4dfb9fa2b1bb97f4a3d6aa21907fe22856c11938/Cargo.toml#L47)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I think it'd be better to mark everything here `default-features = false` and let downstream crates request the features they want. Otherwise you risk introducing unintended features (and dependencies) downstream.
</blockquote></details>

Good point


<!-- Sent from Reviewable.io -->

2023-07-18 13:13 UTC, tamird approved these changes
> Reviewed 1 of 2 files at r2, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/667)* status: all files reviewed, 1 unresolved discussion (waiting on @vadorovsky)

___
*[`Cargo.toml` line 43 at r1](https://reviewable.io/reviews/aya-rs/aya/667#-N__dfjU3QZQfNlxzRji:-N_d7Fma7_gbQeXRGKV0:b-ib7ooz) ([raw file](https://github.com/aya-rs/aya/blob/4dfb9fa2b1bb97f4a3d6aa21907fe22856c11938/Cargo.toml#L43)):*
<details><summary><i>Previously, vadorovsky wrote…</i></summary><blockquote>

It doesn't :(
</blockquote></details>

Maybe the best we can do is add a comment here?


<!-- Sent from Reviewable.io -->

2023-07-18 20:25 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/667)* status: all files reviewed, 1 unresolved discussion (waiting on @tamird)

___
*[`Cargo.toml` line 43 at r1](https://reviewable.io/reviews/aya-rs/aya/667#-N__dfjU3QZQfNlxzRji:-N_efL6dDbQAXItGxJkm:b-80w82l) ([raw file](https://github.com/aya-rs/aya/blob/4dfb9fa2b1bb97f4a3d6aa21907fe22856c11938/Cargo.toml#L43)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Maybe the best we can do is add a comment here?
</blockquote></details>

Done. I will also think about contributing either to cargo-udeps or cargo-machete.


<!-- Sent from Reviewable.io -->

2023-07-18 20:40 UTC, tamird approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/667)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vadorovsky)



<!-- Sent from Reviewable.io -->

2023-07-18 21:11 UTC, tamird approved these changes
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/667)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vadorovsky)



<!-- Sent from Reviewable.io -->

2023-07-18 22:05 UTC, tamird reviewed
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/667)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vadorovsky)



<!-- Sent from Reviewable.io -->

2023-07-18 22:28 UTC, merged