Tidy up use of sleepable in aya-bpf-macros and plumb through into aya
aya-rs/aya pull request #711
Opened 2023-08-01 16:42 UTC by dave-tucker

This PR contains 3 commits.

The bulk of the PR is in aya-bpf-macros where I've added the ability to parse `bool` attributes.
This is neat as args are permitted in any order, and can be mixed with K/V style arguments.
For example, `sleepable, function = "foo"` and `function = "foo", sleepable` are both permitted.

Per https://kernel.org/doc/html/latest/bpf/libbpf/program_types.html I added support to all sleepable program types since this was already done at the macro-level for LSM. This required changes in aya-obj and aya.

2023-08-01 19:03 UTC, tamird requested changes
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/711)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @dave-tucker)

___
*[`aya-bpf-macros/src/args.rs` line 28 at r1](https://reviewable.io/reviews/aya-rs/aya/711#-NamQ7Ag6_HXui8tGEJW:-NamQ7Ag6_HXui8tGEJX:b-nkmevc) ([raw file](https://github.com/aya-rs/aya/blob/8f4b609a36bda59e0ccd1c5d732aec65d0b7f936/aya-bpf-macros/src/args.rs#L28)):*
> ```XML
>             let lookahead = input.lookahead1();
>             if lookahead.peek(Token![=]) {
>                 let _ = input.parse::<Eq>()?;
> ```

a little odd that we're looking ahead, and then fallibly parsing the token. can we just skip the token, or perhaps take the else arm if `parse::<Eq>()` fails?

finally, should we be parsing to the end? it looks to me like this will now accept any jibberish that isn't an equal sign.
___
*[`aya-bpf-macros/src/args.rs` line 49 at r1](https://reviewable.io/reviews/aya-rs/aya/711#-NamR3Fd-nB97NIOcJtj:-NamR3Fd-nB97NIOcJtk:b8prpuh) ([raw file](https://github.com/aya-rs/aya/blob/8f4b609a36bda59e0ccd1c5d732aec65d0b7f936/aya-bpf-macros/src/args.rs#L49)):*
> ```XML
> 
> pub(crate) fn pop_string_arg(args: &mut Args, name: &str) -> Option<String> {
>     let value = match args.args.iter().position(|arg| match arg {
> ```

this function should be

```
let index = args.args.iter().position(|arg| matches!(arg, ....))?;
match args.args.remove(index) {
  Arg::String => ...,
  arg => panic!("impossible variant {arg:?})
}
```

currently it seems to allow impossible things to happen.
___
*[`aya-bpf-macros/src/args.rs` line 63 at r1](https://reviewable.io/reviews/aya-rs/aya/711#-NamTTXIAcEpoH-sb07c:-NamTTXJAUYHzbn-SW6f:b-z4ot4j) ([raw file](https://github.com/aya-rs/aya/blob/8f4b609a36bda59e0ccd1c5d732aec65d0b7f936/aya-bpf-macros/src/args.rs#L63)):*
> ```XML
> 
> pub(crate) fn pop_bool_arg(args: &mut Args, name: &str) -> bool {
>     let value = match args.args.iter().position(|arg| match arg {
> ```

this looks like Option::map

more below


<!-- Sent from Reviewable.io -->

2023-08-01 20:27 UTC, dave-tucker commented
> > _[Reviewable](https://reviewable.io/reviews/aya-rs/aya/711)_ status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @dave-tucker)
> 
> _[`aya-bpf-macros/src/args.rs` line 28 at r1](https://reviewable.io/reviews/aya-rs/aya/711#-NamQ7Ag6_HXui8tGEJW:-NamQ7Ag6_HXui8tGEJX:b-nkmevc) ([raw file](https://github.com/aya-rs/aya/blob/8f4b609a36bda59e0ccd1c5d732aec65d0b7f936/aya-bpf-macros/src/args.rs#L28)):_
> 
> > ```
> >             let lookahead = input.lookahead1();
> >             if lookahead.peek(Token![=]) {
> >                 let _ = input.parse::<Eq>()?;
> > ```
> 
> a little odd that we're looking ahead, and then fallibly parsing the token. can we just skip the token, or perhaps take the else arm if `parse::<Eq>()` fails?
> 
> finally, should we be parsing to the end? it looks to me like this will now accept any jibberish that isn't an equal sign.
> 

This is now more robust. The lookahead is still there - we need to know after we've parse the first ident whether to continue parsing or not. However this time we handle cases where the next token is a comma, or there is no input and return early... otherwise we continue parsing. 

> _[`aya-bpf-macros/src/args.rs` line 49 at r1](https://reviewable.io/reviews/aya-rs/aya/711#-NamR3Fd-nB97NIOcJtj:-NamR3Fd-nB97NIOcJtk:b8prpuh) ([raw file](https://github.com/aya-rs/aya/blob/8f4b609a36bda59e0ccd1c5d732aec65d0b7f936/aya-bpf-macros/src/args.rs#L49)):_
> 
> > ```
> > pub(crate) fn pop_string_arg(args: &mut Args, name: &str) -> Option<String> {
> >     let value = match args.args.iter().position(|arg| match arg {
> > ```
> 
> this function should be
> 
> ```
> let index = args.args.iter().position(|arg| matches!(arg, ....))?;
> match args.args.remove(index) {
>   Arg::String => ...,
>   arg => panic!("impossible variant {arg:?})
> }
> ```
> 
> currently it seems to allow impossible things to happen.

Done.

> _[`aya-bpf-macros/src/args.rs` line 63 at r1](https://reviewable.io/reviews/aya-rs/aya/711#-NamTTXIAcEpoH-sb07c:-NamTTXJAUYHzbn-SW6f:b-z4ot4j) ([raw file](https://github.com/aya-rs/aya/blob/8f4b609a36bda59e0ccd1c5d732aec65d0b7f936/aya-bpf-macros/src/args.rs#L63)):_
> 
> > ```
> > pub(crate) fn pop_bool_arg(args: &mut Args, name: &str) -> bool {
> >     let value = match args.args.iter().position(|arg| match arg {
> > ```
> 
> this looks like Option::map
> 
> more below

And also done.

2023-08-01 20:41 UTC, tamird reviewed
> Reviewed 10 of 11 files at r1, 3 of 3 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/711)* status: all files reviewed, 10 unresolved discussions (waiting on @dave-tucker)

___
*[`-- commits` line 7 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-Namohmu-y8rGpFod9vj):*
can you include an integration test in this commit? does it make sense to do so?
___
*[`aya/src/bpf.rs` line 565 at r6](https://reviewable.io/reviews/aya-rs/aya/711#-NampHLRDKaHtk0HcOXZ:-NampHLRDKaHtk0HcOX_:bp9fdic) ([raw file](https://github.com/aya-rs/aya/blob/77e27d330fe94bf7eed7e7c86f941e3b33615b57/aya/src/bpf.rs#L565)):*
> ```XML
>                             kind: ProbeKind::KRetProbe,
>                         }),
>                         ProgramSection::UProbe { sleepable, .. } => {
> ```

can you make these destructurings exhaustive? i think it's just one more field, and that would let the compiler helps us in the future.
___
*[`aya-bpf-macros/src/args.rs` line 28 at r1](https://reviewable.io/reviews/aya-rs/aya/711#-NamQ7Ag6_HXui8tGEJW:-NammIA0BfHOX89iF7-S:b-rkdl9m) ([raw file](https://github.com/aya-rs/aya/blob/8f4b609a36bda59e0ccd1c5d732aec65d0b7f936/aya-bpf-macros/src/args.rs#L28)):*
<details><summary><i>Previously, dave-tucker (Dave Tucker) wrote…</i></summary><blockquote>

This is now more robust. The lookahead is still there - we need to know after we've parse the first ident whether to continue parsing or not. However this time we handle cases where the next token is a comma, or there is no input and return early... otherwise we continue parsing. 
</blockquote></details>

OK. Would you mind writing this line as `let _: Eq = input.parse()?`? it's a little more obvious that way what it is that's being discarded.
___
*[`aya-bpf-macros/src/args.rs` line 80 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-NammtyGAYI102dXobhn:-NammtyGAYI102dXobho:bhao214) ([raw file](https://github.com/aya-rs/aya/blob/4e5be68ee012fbe28458583b59ba23f390953760/aya-bpf-macros/src/args.rs#L80)):*
> ```XML
>         })
>         .ok_or_else(|| {
>             let tokens = match args.args.first().unwrap() {
> ```

isn't it possible for args to be empty?
___
*[`aya-bpf-macros/src/fentry.rs` line 75 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-NamnayLBgQJclLjyPRf:-NamnayLBgQJclLjyPRg:b-aed3bb) ([raw file](https://github.com/aya-rs/aya/blob/4e5be68ee012fbe28458583b59ba23f390953760/aya-bpf-macros/src/fentry.rs#L75)):*
> ```XML
>             #[link_section = "fentry/sys_clone"]
>             fn sys_clone(ctx: *mut ::core::ffi::c_void) -> i32 {
>                 let _ = sys_clone(::aya_bpf::programs::FEntryContext::new(ctx));
> ```

recognizing this pattern is already here, why not return this value rather than discard it?

```
            fn sys_clone(ctx: *mut ::core::ffi::c_void) -> i32 {
                fn sys_clone(ctx: &mut aya_bpf::programs::FEntryContext) -> i32 {
                    0
                }
                sys_clone(::aya_bpf::programs::FEntryContext::new(ctx))
            }
```
___
*[`aya-bpf-macros/src/fexit.rs` line 75 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-Namnpny2SYqZhSyFtf8:-Namnpny2SYqZhSyFtf9:b-2guby3) ([raw file](https://github.com/aya-rs/aya/blob/4e5be68ee012fbe28458583b59ba23f390953760/aya-bpf-macros/src/fexit.rs#L75)):*
> ```XML
>             #[link_section = "fexit/sys_clone"]
>             fn sys_clone(ctx: *mut ::core::ffi::c_void) -> i32 {
>                 let _ = sys_clone(::aya_bpf::programs::FExitContext::new(ctx));
> ```

same here
___
*[`aya-bpf-macros/src/kprobe.rs` line 39 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-NamnyhA30nBOZlIZD12:-NamnyhA30nBOZlIZD13:btjwky1) ([raw file](https://github.com/aya-rs/aya/blob/4e5be68ee012fbe28458583b59ba23f390953760/aya-bpf-macros/src/kprobe.rs#L39)):*
> ```XML
>         let mut offset = None;
> 
>         if !attrs.is_empty() {
> ```

why is this check needed?
___
*[`aya-bpf-macros/src/raw_tracepoint.rs` line 17 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-NamoCti8Mz84BKJctwj:-NamoCti8Mz84BKJctwk:bjnejqn) ([raw file](https://github.com/aya-rs/aya/blob/4e5be68ee012fbe28458583b59ba23f390953760/aya-bpf-macros/src/raw_tracepoint.rs#L17)):*
> ```XML
> impl RawTracePoint {
>     pub(crate) fn parse(attrs: TokenStream, item: TokenStream) -> Result<RawTracePoint> {
>         if attrs.is_empty() {
> ```

why not use `pop_string_arg` below and bail if it's absent? this check seems redundant.
___
*[`aya-bpf-macros/src/uprobe.rs` line 42 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-NamoU1B0n8fC-IJjzFs:-NamoU1B0n8fC-IJjzFt:b-icv0pt) ([raw file](https://github.com/aya-rs/aya/blob/4e5be68ee012fbe28458583b59ba23f390953760/aya-bpf-macros/src/uprobe.rs#L42)):*
> ```XML
>         let mut offset = None;
>         let mut sleepable = false;
>         if !attrs.is_empty() {
> ```

why is this check required?
___
*[`aya-bpf-macros/src/uprobe.rs` line 135 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-NamoY4i3Qmcv8mmmhJN:-NamoY4i3Qmcv8mmmhJO:b-7ropln) ([raw file](https://github.com/aya-rs/aya/blob/4e5be68ee012fbe28458583b59ba23f390953760/aya-bpf-macros/src/uprobe.rs#L135)):*
> ```XML
>                 #[link_section = "uprobe"]
>                 fn foo(ctx: *mut ::core::ffi::c_void) -> u32 {
>                     let _ = foo(::aya_bpf::programs::ProbeContext::new(ctx));
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-08-01 21:35 UTC, dave-tucker reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/711)* status: all files reviewed, 10 unresolved discussions (waiting on @tamird)

___
*[`-- commits` line 7 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-Namohmu-y8rGpFod9vj):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you include an integration test in this commit? does it make sense to do so?
</blockquote></details>

I could, but I'd rather open an issue and do it later since these macro fixups are stacking up :)
___
*[`aya/src/bpf.rs` line 565 at r6](https://reviewable.io/reviews/aya-rs/aya/711#-NampHLRDKaHtk0HcOXZ:-Namqb2T29xjmQMDXbaw:ben1pev) ([raw file](https://github.com/aya-rs/aya/blob/77e27d330fe94bf7eed7e7c86f941e3b33615b57/aya/src/bpf.rs#L565)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you make these destructurings exhaustive? i think it's just one more field, and that would let the compiler helps us in the future.
</blockquote></details>

Can I do it in a follow up? I'm about to do more tidy up on ProgramSection after these macro fixes.
___
*[`aya-bpf-macros/src/args.rs` line 80 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-NammtyGAYI102dXobhn:-NamqobK-Hs-H7svFPNW:b-su7gxl) ([raw file](https://github.com/aya-rs/aya/blob/4e5be68ee012fbe28458583b59ba23f390953760/aya-bpf-macros/src/args.rs#L80)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

isn't it possible for args to be empty?
</blockquote></details>

Yes this is 100% the wrong thing to do, but I'm also ripping this out in #713.
I've closed #713 and brought that commit in here.
___
*[`aya-bpf-macros/src/fentry.rs` line 75 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-NamnayLBgQJclLjyPRf:-NamrtQnEMCGMzBKzyky:bejurdh) ([raw file](https://github.com/aya-rs/aya/blob/4e5be68ee012fbe28458583b59ba23f390953760/aya-bpf-macros/src/fentry.rs#L75)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

recognizing this pattern is already here, why not return this value rather than discard it?

```
            fn sys_clone(ctx: *mut ::core::ffi::c_void) -> i32 {
                fn sys_clone(ctx: &mut aya_bpf::programs::FEntryContext) -> i32 {
                    0
                }
                sys_clone(::aya_bpf::programs::FEntryContext::new(ctx))
            }
```
</blockquote></details>

These tests only test that the macro contents is rendered correctly. BPF program return values is a can of worms we shouldn't open in this PR :)
___
*[`aya-bpf-macros/src/kprobe.rs` line 39 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-NamnyhA30nBOZlIZD12:-NamsENTDr3nr18qfnNN:bqa76jf) ([raw file](https://github.com/aya-rs/aya/blob/4e5be68ee012fbe28458583b59ba23f390953760/aya-bpf-macros/src/kprobe.rs#L39)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why is this check needed?
</blockquote></details>

There were a few of these around... they were to guard us from attempting to parse tokens if there were none to parse. Most of them can be removed. I've pushed a commit to do this here.
___
*[`aya-bpf-macros/src/raw_tracepoint.rs` line 17 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-NamoCti8Mz84BKJctwj:-Nan0Wtv7Q93LQpmguGu:b-b7h1sm) ([raw file](https://github.com/aya-rs/aya/blob/4e5be68ee012fbe28458583b59ba23f390953760/aya-bpf-macros/src/raw_tracepoint.rs#L17)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why not use `pop_string_arg` below and bail if it's absent? this check seems redundant.
</blockquote></details>

yep, that was also something in #713, i've now added that commit here too. tracepoint is now an option so pop_string_arg doesn't need to bail.


<!-- Sent from Reviewable.io -->

2023-08-01 21:52 UTC, tamird requested changes
> Reviewed 4 of 4 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, 3 of 3 files at r10, 1 of 1 files at r11, 6 of 6 files at r12, 7 of 7 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/711)* status: all files reviewed, 17 unresolved discussions (waiting on @dave-tucker)

___
*[`-- commits` line 7 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-Namohmu-y8rGpFod9vj):*
<details><summary><i>Previously, dave-tucker (Dave Tucker) wrote…</i></summary><blockquote>

I could, but I'd rather open an issue and do it later since these macro fixups are stacking up :)
</blockquote></details>

OK.
___
*[`-- commits` line 36 at r12](https://reviewable.io/reviews/aya-rs/aya/711#-Nan3BRTDgZmI686Qzy3):*
can we avoid this diary-entry style of commit message? reading this, i have no idea what this change does. Please use the imperative voice to describe what this commit is doing.
___
*[`aya/src/bpf.rs` line 565 at r6](https://reviewable.io/reviews/aya-rs/aya/711#-NampHLRDKaHtk0HcOXZ:-Nan21eo2pFrQkEnFiky:b6ltfq7) ([raw file](https://github.com/aya-rs/aya/blob/77e27d330fe94bf7eed7e7c86f941e3b33615b57/aya/src/bpf.rs#L565)):*
<details><summary><i>Previously, dave-tucker (Dave Tucker) wrote…</i></summary><blockquote>

Can I do it in a follow up? I'm about to do more tidy up on ProgramSection after these macro fixes.
</blockquote></details>

Could you do it here just for the lines you're already touching?
___
*[`aya-bpf-macros/src/args.rs` line 80 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-NammtyGAYI102dXobhn:-Nan2FI28R4HKenvCTmF:bcqzcf8) ([raw file](https://github.com/aya-rs/aya/blob/4e5be68ee012fbe28458583b59ba23f390953760/aya-bpf-macros/src/args.rs#L80)):*
<details><summary><i>Previously, dave-tucker (Dave Tucker) wrote…</i></summary><blockquote>

Yes this is 100% the wrong thing to do, but I'm also ripping this out in #713.
I've closed #713 and brought that commit in here.
</blockquote></details>

I don't love that a single logical change is spread over multiple commits.
___
*[`aya-bpf-macros/src/btf_tracepoint.rs` line 16 at r12](https://reviewable.io/reviews/aya-rs/aya/711#-Nan3O7iCJmxbeD5n8AD:-Nan3O7iCJmxbeD5n8AE:b-uprezm) ([raw file](https://github.com/aya-rs/aya/blob/b6387882267a64c6e43dca72f8f83beecd1dc690/aya-bpf-macros/src/btf_tracepoint.rs#L16)):*
> ```XML
> impl BtfTracePoint {
>     pub(crate) fn parse(attrs: TokenStream, item: TokenStream) -> Result<Self> {
>         let item = syn::parse2(item)?;
> ```

is this reversal meaningful?
___
*[`aya-bpf-macros/src/btf_tracepoint.rs` line 25 at r12](https://reviewable.io/reviews/aya-rs/aya/711#-Nan3RYx7xc6n1IzynPK:-Nan3RYx7xc6n1IzynPL:b-ddd7au) ([raw file](https://github.com/aya-rs/aya/blob/b6387882267a64c6e43dca72f8f83beecd1dc690/aya-bpf-macros/src/btf_tracepoint.rs#L25)):*
> ```XML
> 
>     pub(crate) fn expand(&self) -> Result<TokenStream> {
>         let section_name: Cow<'_, _> = if self.function.is_none() {
> ```

`is_none()` + `unwrap()` is just `if let Some`
___
*[`aya-bpf-macros/src/btf_tracepoint.rs` line 67 at r12](https://reviewable.io/reviews/aya-rs/aya/711#-Nan3WMX09Lb7RNQMzsQ:-Nan3WMX09Lb7RNQMzsR:bnein7y) ([raw file](https://github.com/aya-rs/aya/blob/b6387882267a64c6e43dca72f8f83beecd1dc690/aya-bpf-macros/src/btf_tracepoint.rs#L67)):*
> ```XML
>             #[link_section = "tp_btf"]
>             fn foo(ctx: *mut ::core::ffi::c_void) -> i32 {
>                 let _ = foo(::aya_bpf::programs::BtfTracePointContext::new(ctx));
> ```

please just let the value flow through, it's zero no matter what.
___
*[`aya-bpf-macros/src/cgroup_skb.rs` line 21 at r10](https://reviewable.io/reviews/aya-rs/aya/711#-Nan2mlbEzF4LQyY96oF:-Nan2mlbEzF4LQyY96oG:b-fhvs2z) ([raw file](https://github.com/aya-rs/aya/blob/a6582737448fad00ff0bb1ac743738fd48d7b681/aya-bpf-macros/src/cgroup_skb.rs#L21)):*
> ```XML
>             match ident.to_string().as_str() {
>                 "ingress" | "egress" => (),
>                 _ => abort!(ident, "invalid attach type"),
> ```

the commit message on this change is `aya-bpf-macros: Remove useless attrs.is_empty`. Help me understand?
___
*[`aya-bpf-macros/src/cgroup_sock.rs` line 15 at r13](https://reviewable.io/reviews/aya-rs/aya/711#-Nan46wC8mkNJdMqWttf:-Nan46wC8mkNJdMqWttg:b-emmh5) ([raw file](https://github.com/aya-rs/aya/blob/98498d18de5ea9a949f01c3dbc354be68fb60d05/aya-bpf-macros/src/cgroup_sock.rs#L15)):*
> ```XML
> impl CgroupSock {
>     pub(crate) fn parse(attrs: TokenStream, item: TokenStream) -> Result<CgroupSock> {
>         if attrs.is_empty() {
> ```

why is this check needed? where's the test?

same for `cgroup_sock_addr.rs` and `cgroup_sockopt.rs`
___
*[`aya-bpf-macros/src/fentry.rs` line 75 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-NamnayLBgQJclLjyPRf:-Nan2PaY8y7odW7r7k2w:b-t703gv) ([raw file](https://github.com/aya-rs/aya/blob/4e5be68ee012fbe28458583b59ba23f390953760/aya-bpf-macros/src/fentry.rs#L75)):*
<details><summary><i>Previously, dave-tucker (Dave Tucker) wrote…</i></summary><blockquote>

These tests only test that the macro contents is rendered correctly. BPF program return values is a can of worms we shouldn't open in this PR :)
</blockquote></details>

This returns zero no matter what, why do we need to draw the reader's eye to this `let _`?
___
*[`aya-bpf-macros/src/fentry.rs` line 31 at r12](https://reviewable.io/reviews/aya-rs/aya/711#-Nan3w_wDMQMRNNHCj1C:-Nan3w_wDMQMRNNHCj1D:bwl7pfv) ([raw file](https://github.com/aya-rs/aya/blob/b6387882267a64c6e43dca72f8f83beecd1dc690/aya-bpf-macros/src/fentry.rs#L31)):*
> ```XML
>     pub(crate) fn expand(&self) -> Result<TokenStream> {
>         let section_prefix = if self.sleepable { "fentry.s" } else { "fentry" };
>         let section_name: Cow<'_, _> = if self.function.is_none() {
> ```

this is `if let Some`
___
*[`aya-bpf-macros/src/fentry.rs` line 73 at r12](https://reviewable.io/reviews/aya-rs/aya/711#-Nan3ujaDStRQk9IONMI:-Nan3ujaDStRQk9IONMJ:b-bhoxg9) ([raw file](https://github.com/aya-rs/aya/blob/b6387882267a64c6e43dca72f8f83beecd1dc690/aya-bpf-macros/src/fentry.rs#L73)):*
> ```XML
>             #[link_section = "fentry"]
>             fn sys_clone(ctx: *mut ::core::ffi::c_void) -> i32 {
>                 let _ = sys_clone(::aya_bpf::programs::FEntryContext::new(ctx));
> ```

please let the value flow through.
___
*[`aya-bpf-macros/src/fexit.rs` line 31 at r12](https://reviewable.io/reviews/aya-rs/aya/711#-Nan3bdV6nC7Z1lYVHFG:-Nan3bdV6nC7Z1lYVHFH:bwl7pfv) ([raw file](https://github.com/aya-rs/aya/blob/b6387882267a64c6e43dca72f8f83beecd1dc690/aya-bpf-macros/src/fexit.rs#L31)):*
> ```XML
>     pub(crate) fn expand(&self) -> Result<TokenStream> {
>         let section_prefix = if self.sleepable { "fexit.s" } else { "fexit" };
>         let section_name: Cow<'_, _> = if self.function.is_none() {
> ```

this is `if let Some`
___
*[`aya-bpf-macros/src/fexit.rs` line 73 at r12](https://reviewable.io/reviews/aya-rs/aya/711#-Nan3djyEdL2Vlm-COeG:-Nan3djyEdL2Vlm-COeH:b-7ropln) ([raw file](https://github.com/aya-rs/aya/blob/b6387882267a64c6e43dca72f8f83beecd1dc690/aya-bpf-macros/src/fexit.rs#L73)):*
> ```XML
>             #[link_section = "fexit"]
>             fn sys_clone(ctx: *mut ::core::ffi::c_void) -> i32 {
>                 let _ = sys_clone(::aya_bpf::programs::FExitContext::new(ctx));
> ```

ditto
___
*[`aya-bpf-macros/src/lsm.rs` line 31 at r12](https://reviewable.io/reviews/aya-rs/aya/711#-Nan3hPA5miWlw6K2Ab-:-Nan3hPA5miWlw6K2Ab0:bwl7pfv) ([raw file](https://github.com/aya-rs/aya/blob/b6387882267a64c6e43dca72f8f83beecd1dc690/aya-bpf-macros/src/lsm.rs#L31)):*
> ```XML
>     pub(crate) fn expand(&self) -> Result<TokenStream> {
>         let section_prefix = if self.sleepable { "lsm.s" } else { "lsm" };
>         let section_name: Cow<'_, _> = if self.hook.is_none() {
> ```

this is `if let Some`
___
*[`aya-bpf-macros/src/raw_tracepoint.rs` line 17 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-NamoCti8Mz84BKJctwj:-Nan3pDGEvqIjGLtGIB [...]

2023-08-01 23:36 UTC, dave-tucker reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/711)* status: 1 of 19 files reviewed, 17 unresolved discussions (waiting on @tamird)

___
*[`-- commits` line 36 at r12](https://reviewable.io/reviews/aya-rs/aya/711#-Nan3BRTDgZmI686Qzy3):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can we avoid this diary-entry style of commit message? reading this, i have no idea what this change does. Please use the imperative voice to describe what this commit is doing.
</blockquote></details>

Yep I'll squash the aya-bpf-macros changes together
___
*[`aya/src/bpf.rs` line 565 at r6](https://reviewable.io/reviews/aya-rs/aya/711#-NampHLRDKaHtk0HcOXZ:-NanE2Am5svXPSLloWhy:b-xrv757) ([raw file](https://github.com/aya-rs/aya/blob/77e27d330fe94bf7eed7e7c86f941e3b33615b57/aya/src/bpf.rs#L565)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Could you do it here just for the lines you're already touching?
</blockquote></details>

Sure why not
___
*[`aya-bpf-macros/src/args.rs` line 28 at r1](https://reviewable.io/reviews/aya-rs/aya/711#-NamQ7Ag6_HXui8tGEJW:-Nan1LUy699QtS91mMzo:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/8f4b609a36bda59e0ccd1c5d732aec65d0b7f936/aya-bpf-macros/src/args.rs#L28)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

OK. Would you mind writing this line as `let _: Eq = input.parse()?`? it's a little more obvious that way what it is that's being discarded.
</blockquote></details>

Done.
___
*[`aya-bpf-macros/src/args.rs` line 80 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-NammtyGAYI102dXobhn:-NanE5d2ALIvgYsZv9lC:b-q7tho4) ([raw file](https://github.com/aya-rs/aya/blob/4e5be68ee012fbe28458583b59ba23f390953760/aya-bpf-macros/src/args.rs#L80)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I don't love that a single logical change is spread over multiple commits.
</blockquote></details>

Ack, will squash these together.
___
*[`aya-bpf-macros/src/btf_tracepoint.rs` line 16 at r12](https://reviewable.io/reviews/aya-rs/aya/711#-Nan3O7iCJmxbeD5n8AD:-NanEE2N1YhwHEJIJuAL:b-c1lyjr) ([raw file](https://github.com/aya-rs/aya/blob/b6387882267a64c6e43dca72f8f83beecd1dc690/aya-bpf-macros/src/btf_tracepoint.rs#L16)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is this reversal meaningful?
</blockquote></details>

No, this will be squashed.
___
*[`aya-bpf-macros/src/btf_tracepoint.rs` line 25 at r12](https://reviewable.io/reviews/aya-rs/aya/711#-Nan3RYx7xc6n1IzynPK:-NanEMaS7vWV6VlqSKN9:bb6sh2i) ([raw file](https://github.com/aya-rs/aya/blob/b6387882267a64c6e43dca72f8f83beecd1dc690/aya-bpf-macros/src/btf_tracepoint.rs#L25)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`is_none()` + `unwrap()` is just `if let Some`
</blockquote></details>

Ack.
___
*[`aya-bpf-macros/src/btf_tracepoint.rs` line 67 at r12](https://reviewable.io/reviews/aya-rs/aya/711#-Nan3WMX09Lb7RNQMzsQ:-NanRcw-1JOkAVn6qJAS:b-u9pnt6) ([raw file](https://github.com/aya-rs/aya/blob/b6387882267a64c6e43dca72f8f83beecd1dc690/aya-bpf-macros/src/btf_tracepoint.rs#L67)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

please just let the value flow through, it's zero no matter what.
</blockquote></details>

again, this requires changing `expand()` - i'd rather not do that in this PR
___
*[`aya-bpf-macros/src/cgroup_skb.rs` line 21 at r10](https://reviewable.io/reviews/aya-rs/aya/711#-Nan2mlbEzF4LQyY96oF:-NanH246BQIK4VBBOybk:b-4dlc0e) ([raw file](https://github.com/aya-rs/aya/blob/a6582737448fad00ff0bb1ac743738fd48d7b681/aya-bpf-macros/src/cgroup_skb.rs#L21)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

the commit message on this change is `aya-bpf-macros: Remove useless attrs.is_empty`. Help me understand?
</blockquote></details>

Ooops yes this snuck in because I accidentally removed the attrs.is_empty() guard here.
And then realized that the error manifested in the wrong place.

Compiletests will make this clear, when we finally add some.

This will be squashed anyway and I'll add some context in the commit message.
___
*[`aya-bpf-macros/src/cgroup_sock.rs` line 15 at r13](https://reviewable.io/reviews/aya-rs/aya/711#-Nan46wC8mkNJdMqWttf:-NanE_gYCnSXYpjX7Re1:b-6az3yt) ([raw file](https://github.com/aya-rs/aya/blob/98498d18de5ea9a949f01c3dbc354be68fb60d05/aya-bpf-macros/src/cgroup_sock.rs#L15)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why is this check needed? where's the test?

same for `cgroup_sock_addr.rs` and `cgroup_sockopt.rs`
</blockquote></details>

It's needed to give a nice error message to the caller if they were to use `#[cgroup_sock]` - note, there's not attach type there. Failing to do that gives a generic message about not being able to parse ident, which isn't as nice.

There are no tests, because negative testing of proc_macros has to be done with compiletests and I haven't been motivated enough to set that up just yet.

Otherwise you get a "fun" error message like this:
```
thread 'cgroup_sock::tests::cgroup_sock_no_attach' panicked at 'proc-macro-error API cannot be used outside of `entry_point` invocation, perhaps you forgot to annotate your #[proc_macro] function with `#[proc_macro_error]', /home/dave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro-error-1.0.4/src/lib.rs:483:9
```
___
*[`aya-bpf-macros/src/fentry.rs` line 75 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-NamnayLBgQJclLjyPRf:-NanGUC91rus-oyXzNdD:b13strv) ([raw file](https://github.com/aya-rs/aya/blob/4e5be68ee012fbe28458583b59ba23f390953760/aya-bpf-macros/src/fentry.rs#L75)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

This returns zero no matter what, why do we need to draw the reader's eye to this `let _`?
</blockquote></details>

You're argument is with the implementation of `expand()` for this macro.
I'm not saying it's not worth fixing, but I'm not doing it in this PR.
___
*[`aya-bpf-macros/src/fentry.rs` line 31 at r12](https://reviewable.io/reviews/aya-rs/aya/711#-Nan3w_wDMQMRNNHCj1C:-NanHYqT5TQbyLyeo-zB:b2nhb2c) ([raw file](https://github.com/aya-rs/aya/blob/b6387882267a64c6e43dca72f8f83beecd1dc690/aya-bpf-macros/src/fentry.rs#L31)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this is `if let Some`
</blockquote></details>

Ack
___
*[`aya-bpf-macros/src/fentry.rs` line 73 at r12](https://reviewable.io/reviews/aya-rs/aya/711#-Nan3ujaDStRQk9IONMI:-NanGiAl5DhZ_kTcwls_:b-tkcp0i) ([raw file](https://github.com/aya-rs/aya/blob/b6387882267a64c6e43dca72f8f83beecd1dc690/aya-bpf-macros/src/fentry.rs#L73)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

please let the value flow through.
</blockquote></details>

Sorry what value? 
___
*[`aya-bpf-macros/src/fexit.rs` line 75 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-Namnpny2SYqZhSyFtf8:-NanLyQP4J5fddTQHMEt:bdlm5j9) ([raw file](https://github.com/aya-rs/aya/blob/4e5be68ee012fbe28458583b59ba23f390953760/aya-bpf-macros/src/fexit.rs#L75)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

same here
</blockquote></details>

ditto - re: expand() changes
___
*[`aya-bpf-macros/src/fexit.rs` line 31 at r12](https://reviewable.io/reviews/aya-rs/aya/711#-Nan3bdV6nC7Z1lYVHFG:-NanM7XI-iZoUOwVJ2Cn:b-896fix) ([raw file](https://github.com/aya-rs/aya/blob/b6387882267a64c6e43dca72f8f83beecd1dc690/aya-bpf-macros/src/fexit.rs#L31)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this is `if let Some`
</blockquote></details>

Done.
___
*[`aya-bpf-macros/src/fexit.rs` l [...]

2023-08-02 00:46 UTC, tamird reviewed
> Reviewed 18 of 18 files at r14, 2 of 2 files at r15, 1 of 1 files at r16, 3 of 3 files at r17, 1 of 1 files at r18, 6 of 6 files at r19, 7 of 7 files at r20, 8 of 8 files at r21, 2 of 2 files at r22, 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/711)* status: all files reviewed, 7 unresolved discussions (waiting on @dave-tucker)

___
*[`aya-bpf-macros/src/fentry.rs` line 75 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-NamnayLBgQJclLjyPRf:-NangpN723DKn6pDqfaX:b9xn7z1) ([raw file](https://github.com/aya-rs/aya/blob/4e5be68ee012fbe28458583b59ba23f390953760/aya-bpf-macros/src/fentry.rs#L75)):*
<details><summary><i>Previously, dave-tucker (Dave Tucker) wrote…</i></summary><blockquote>

You're argument is with the implementation of `expand()` for this macro.
I'm not saying it's not worth fixing, but I'm not doing it in this PR.
</blockquote></details>

That seems fine, but I'm confused because `lsm.rs` seems to do the right thing. Am I missing something?
___
*[`aya-bpf-macros/src/fentry.rs` line 73 at r12](https://reviewable.io/reviews/aya-rs/aya/711#-Nan3ujaDStRQk9IONMI:-NanghYZ5wM8tcpWWKM1:bl7y9m8) ([raw file](https://github.com/aya-rs/aya/blob/b6387882267a64c6e43dca72f8f83beecd1dc690/aya-bpf-macros/src/fentry.rs#L73)):*
<details><summary><i>Previously, dave-tucker (Dave Tucker) wrote…</i></summary><blockquote>

Sorry what value? 
</blockquote></details>

(this comment was `let _` again), please ignore it for now
___
*[`aya-bpf-macros/src/lsm.rs` line 78 at r21](https://reviewable.io/reviews/aya-rs/aya/711#-Nang1IlCcSOTRH0BjR9:-Nang1IlCcSOTRH0BjRA:b4y5ujk) ([raw file](https://github.com/aya-rs/aya/blob/7eebdcbdebe46136970d759ac66bbab304fc35c1/aya-bpf-macros/src/lsm.rs#L78)):*
> ```XML
>             #[link_section = "lsm.s/bprm_committed_creds"]
>             fn bprm_committed_creds(ctx: *mut ::core::ffi::c_void) -> i32 {
>                 return bprm_committed_creds(::aya_bpf::programs::LsmContext::new(ctx));
> ```

is the `expand` impl here different than the others? here you return the value, while in the others you write `let _ = thing-that-returns 0; return 0`


<!-- Sent from Reviewable.io -->

2023-08-02 10:56 UTC, dave-tucker reviewed
> Dismissed @tamird from a discussion.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/711)* status: all files reviewed, 6 unresolved discussions (waiting on @tamird)

___
*[`aya-bpf-macros/src/fentry.rs` line 75 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-NamnayLBgQJclLjyPRf:-NapqrRu3Xjsm6wmqc8Q:b-a6ybj8) ([raw file](https://github.com/aya-rs/aya/blob/4e5be68ee012fbe28458583b59ba23f390953760/aya-bpf-macros/src/fentry.rs#L75)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

That seems fine, but I'm confused because `lsm.rs` seems to do the right thing. Am I missing something?
</blockquote></details>

Yes, here's the body of the fentry macro - we're asserting that given a set of inputs, the output is correct:
https://github.com/aya-rs/aya/blob/main/aya-bpf-macros/src/fentry.rs#L38-L47

LSM does the right thing because the BPF program may return -EPERM to deny an action.
We're deliberately ignoring the return code here. I would guess that non-zero return codes trip the verifier, but I can't be certain.

Either way, it's probably better for fentry/fexit functions to have no return value vs. ignoring the value. That can be fixed in another PR though.
___
*[`aya-bpf-macros/src/lsm.rs` line 78 at r21](https://reviewable.io/reviews/aya-rs/aya/711#-Nang1IlCcSOTRH0BjR9:-Napt6GJ6Ub_p1uzHSZZ:bu03twa) ([raw file](https://github.com/aya-rs/aya/blob/7eebdcbdebe46136970d759ac66bbab304fc35c1/aya-bpf-macros/src/lsm.rs#L78)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is the `expand` impl here different than the others? here you return the value, while in the others you write `let _ = thing-that-returns 0; return 0`
</blockquote></details>

Yes: https://github.com/aya-rs/aya/blob/main/aya-bpf-macros/src/lsm.rs#L41-L48


<!-- Sent from Reviewable.io -->

2023-08-02 12:51 UTC, tamird approved these changes
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/711)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dave-tucker)

___
*[`aya-bpf-macros/src/fentry.rs` line 75 at r4](https://reviewable.io/reviews/aya-rs/aya/711#-NamnayLBgQJclLjyPRf:-NaqINw8B_P9UHYfjkfd:b5rx3hm) ([raw file](https://github.com/aya-rs/aya/blob/4e5be68ee012fbe28458583b59ba23f390953760/aya-bpf-macros/src/fentry.rs#L75)):*
<details><summary><i>Previously, dave-tucker (Dave Tucker) wrote…</i></summary><blockquote>

Yes, here's the body of the fentry macro - we're asserting that given a set of inputs, the output is correct:
https://github.com/aya-rs/aya/blob/main/aya-bpf-macros/src/fentry.rs#L38-L47

LSM does the right thing because the BPF program may return -EPERM to deny an action.
We're deliberately ignoring the return code here. I would guess that non-zero return codes trip the verifier, but I can't be certain.

Either way, it's probably better for fentry/fexit functions to have no return value vs. ignoring the value. That can be fixed in another PR though.
</blockquote></details>

OK, thanks for explaining.


<!-- Sent from Reviewable.io -->

2023-08-02 14:44 UTC, merged