aya, aya-obj: Implement ENUM64 fixups
aya-rs/aya pull request #725
Opened 2023-08-07 13:58 UTC by dave-tucker

This commit adds:

- A probe to see if the ENUM64 feature is supported
- Fixups for the use of signed enums, or enum64 types on systems where enum64 is not supported

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/725)

2023-08-07 15:03 UTC, tamird requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/725)* status: all files reviewed, 12 unresolved discussions (waiting on @dave-tucker)

___
*[`aya-obj/src/btf/btf.rs` line 486 at r1](https://reviewable.io/reviews/aya-rs/aya/725#-NbFQPvr71aF6kfIZmuR:-NbFQPvr71aF6kfIZmuS:b-q525c5) ([raw file](https://github.com/aya-rs/aya/blob/a3cc48935f8c9b8257b801deead79004a729c713/aya-obj/src/btf/btf.rs#L486)):*
> ```XML
>         // ENUM64 placeholder type needs to be added before
>         // we take ownership of self.types to ensure that
>         // the offsets in the BtfHeader are correct
> ```

period, odd wrap width
___
*[`aya-obj/src/btf/btf.rs` line 487 at r1](https://reviewable.io/reviews/aya-rs/aya/725#-NbFQTaNCw521ezk5haN:-NbFQTaNCw521ezk5haO:b-fmis3d) ([raw file](https://github.com/aya-rs/aya/blob/a3cc48935f8c9b8257b801deead79004a729c713/aya-obj/src/btf/btf.rs#L487)):*
> ```XML
>         // we take ownership of self.types to ensure that
>         // the offsets in the BtfHeader are correct
>         let mut enum64_placeholder_id = None;
> ```

this looks like bool::then
___
*[`aya-obj/src/btf/btf.rs` line 490 at r1](https://reviewable.io/reviews/aya-rs/aya/725#-NbFQCSm3N66XL6GOSPP:-NbFQCSm3N66XL6GOSPQ:b-yghdw7) ([raw file](https://github.com/aya-rs/aya/blob/a3cc48935f8c9b8257b801deead79004a729c713/aya-obj/src/btf/btf.rs#L490)):*
> ```XML
>         if self
>             .types()
>             .any(|t| t.kind() == BtfKind::Enum64 && !features.btf_enum64)
> ```

can we hoist features.btf_enum64 out of the iteration?
___
*[`aya-obj/src/btf/btf.rs` line 695 at r1](https://reviewable.io/reviews/aya-rs/aya/725#-NbFQfFrAzDaAsK33LD2:-NbFQfFrAzDaAsK33LD3:b400ivq) ([raw file](https://github.com/aya-rs/aya/blob/a3cc48935f8c9b8257b801deead79004a729c713/aya-obj/src/btf/btf.rs#L695)):*
> ```XML
>                 }
>                 BtfType::Enum(ty) if !features.btf_enum64 && ty.is_signed() => {
>                     debug!("{}: signed ENUMs not supported. Marking as unsigned", kind);
> ```

do we want to link to libbpf?
___
*[`aya-obj/src/btf/btf.rs` line 696 at r1](https://reviewable.io/reviews/aya-rs/aya/725#-NbFQkPW2SgjU0tOdo-X:-NbFQkPW2SgjU0tOdo-Y:bgt549c) ([raw file](https://github.com/aya-rs/aya/blob/a3cc48935f8c9b8257b801deead79004a729c713/aya-obj/src/btf/btf.rs#L696)):*
> ```XML
>                 BtfType::Enum(ty) if !features.btf_enum64 && ty.is_signed() => {
>                     debug!("{}: signed ENUMs not supported. Marking as unsigned", kind);
>                     let mut ty = ty.clone();
> ```

how come we need to clone? could we write `let t = &mut types.types[i]` and just mutate it directly?
___
*[`aya-obj/src/btf/btf.rs` line 1751 at r1](https://reviewable.io/reviews/aya-rs/aya/725#-NbFWC5B91k54NKU5jSi:-NbFWC5B91k54NKU5jSj:bpl6tc0) ([raw file](https://github.com/aya-rs/aya/blob/a3cc48935f8c9b8257b801deead79004a729c713/aya-obj/src/btf/btf.rs#L1751)):*
> ```XML
>         assert_matches!(btf.type_by_id(enum_type_id).unwrap(), BtfType::Enum(fixed) => {
>            assert!(!fixed.is_signed());
>            assert_eq!(fixed.variants.len(), 3);
> ```

can we use assert_matches here instead of separately asserting length and content?
___
*[`aya-obj/src/btf/btf.rs` line 1757 at r1](https://reviewable.io/reviews/aya-rs/aya/725#-NbFWHCQ2--ChkdHyUpC:-NbFWHCQ2--ChkdHyUpD:bf562dc) ([raw file](https://github.com/aya-rs/aya/blob/a3cc48935f8c9b8257b801deead79004a729c713/aya-obj/src/btf/btf.rs#L1757)):*
> ```XML
>         });
> 
>         // Ensure we can convert to bytes and back again
> ```

periods in comments please.
___
*[`aya-obj/src/btf/btf.rs` line 1786 at r1](https://reviewable.io/reviews/aya-rs/aya/725#-NbFWNiPA-RVbWxh7M8-:-NbFWNiPA-RVbWxh7M80:bk6sj7a) ([raw file](https://github.com/aya-rs/aya/blob/a3cc48935f8c9b8257b801deead79004a729c713/aya-obj/src/btf/btf.rs#L1786)):*
> ```XML
> 
>         assert_matches!(btf.type_by_id(enum_type_id).unwrap(), BtfType::Union(fixed) => {
>             assert_eq!(fixed.members.len(), 3);
> ```

suggest assert_matches here too, with a pattern of `[_, _, _]` so that it's obvious how to extent to check the values
___
*[`aya-obj/src/btf/btf.rs` line 1789 at r1](https://reviewable.io/reviews/aya-rs/aya/725#-NbFWMuJ4arYzT3R8Rps:-NbFWMuJ4arYzT3R8Rpt:b-7ropln) ([raw file](https://github.com/aya-rs/aya/blob/a3cc48935f8c9b8257b801deead79004a729c713/aya-obj/src/btf/btf.rs#L1789)):*
> ```XML
>         });
> 
>         // Ensure we can convert to bytes and back again
> ```

ditto
___
*[`aya-obj/src/btf/types.rs` line 398 at r1](https://reviewable.io/reviews/aya-rs/aya/725#-NbFRY0U0BxrRDgJdT02:-NbFRY0U0BxrRDgJdT03:bytnxjj) ([raw file](https://github.com/aya-rs/aya/blob/a3cc48935f8c9b8257b801deead79004a729c713/aya-obj/src/btf/types.rs#L398)):*
> ```XML
> impl BtfEnum {
>     pub fn new(name_offset: u32, value: u32) -> Self {
>         BtfEnum { name_offset, value }
> ```

nit: s/BtfEnum/Self/

I did that for existing code in https://github.com/aya-rs/aya/pull/726
___
*[`aya-obj/src/btf/types.rs` line 402 at r1](https://reviewable.io/reviews/aya-rs/aya/725#-NbFRHv91paS1M8V18df:-NbFRHv91paS1M8V18dg:bqkn505) ([raw file](https://github.com/aya-rs/aya/blob/a3cc48935f8c9b8257b801deead79004a729c713/aya-obj/src/btf/types.rs#L402)):*
> ```XML
> 
>     pub(crate) fn to_bytes(&self) -> Vec<u8> {
>         let mut buf = vec![];
> ```

i think you can avoid multiple allocations here

```
let Self { name_offset, value } = self;
[bytes_of::<u32>(name_offset), bytes_of::<u32>(value)].into_iter().flatten().collect()
```

done for existing code in https://github.com/aya-rs/aya/pull/726
___
*[`aya-obj/src/btf/types.rs` line 533 at r1](https://reviewable.io/reviews/aya-rs/aya/725#-NbFRvQjCOOFQNBCZhba:-NbFRvQjCOOFQNBCZhbb:bh4bqps) ([raw file](https://github.com/aya-rs/aya/blob/a3cc48935f8c9b8257b801deead79004a729c713/aya-obj/src/btf/types.rs#L533)):*
> ```XML
>             name_offset,
>             info,
>             size: 8, // docs say size is 1/2/4/8 but we'll assume 8
> ```

link to docs?


<!-- Sent from Reviewable.io -->

2023-08-08 10:42 UTC, tamird requested changes
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/725)* status: all files reviewed, 5 unresolved discussions (waiting on @dave-tucker)

___
*[`aya-obj/src/btf/btf.rs` line 487 at r1](https://reviewable.io/reviews/aya-rs/aya/725#-NbFQTaNCw521ezk5haN:-NbJjJ-h9yffAcH2GgSM:byyz5a4) ([raw file](https://github.com/aya-rs/aya/blob/a3cc48935f8c9b8257b801deead79004a729c713/aya-obj/src/btf/btf.rs#L487)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this looks like bool::then
</blockquote></details>

```rust
let enum64_placeholder_id = 
        (!features.btf_enum64 && self.types().any(|t| t.kind() == BtfKind::Enum64)).then(|| {
            self.add_type(BtfType::Int(Int::new(
                self.add_string("enum64_placeholder"),
                1,
                IntEncoding::None,
                0,
            )))
        });

```
___
*[`aya-obj/src/btf/btf.rs` line 696 at r1](https://reviewable.io/reviews/aya-rs/aya/725#-NbFQkPW2SgjU0tOdo-X:-NbJidJ956dTu5cStNDn:b8hgbl4) ([raw file](https://github.com/aya-rs/aya/blob/a3cc48935f8c9b8257b801deead79004a729c713/aya-obj/src/btf/btf.rs#L696)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

how come we need to clone? could we write `let t = &mut types.types[i]` and just mutate it directly?
</blockquote></details>

rather than do it here, why not do it where the existing `let t = &types.types[i]` is?
___
*[`aya-obj/src/btf/btf.rs` line 693 at r3](https://reviewable.io/reviews/aya-rs/aya/725#-NbJhmXj7ZoP9LxX8Ztd:-NbJhmXj7ZoP9LxX8Zte:b87kyg) ([raw file](https://github.com/aya-rs/aya/blob/a9fbe1b66572d2e9e79b6b5981c72c6664f28f82/aya-obj/src/btf/btf.rs#L693)):*
> ```XML
>                     types.types[i] = int_type;
>                 }
>                 // Sanitize TYPE_TAG
> ```

periods on all of these?
___
*[`aya-obj/src/btf/btf.rs` line 1808 at r3](https://reviewable.io/reviews/aya-rs/aya/725#-NbJiFkBElBgVquPaO-c:-NbJiFkBElBgVquPaO-d:bm6s8yt) ([raw file](https://github.com/aya-rs/aya/blob/a9fbe1b66572d2e9e79b6b5981c72c6664f28f82/aya-obj/src/btf/btf.rs#L1808)):*
> ```XML
>             assert_matches!(fixed.members[..], [
>                 BtfMember { name_offset: name_offset1, btf_type: btf_type1, offset:0 },
>                 BtfMember { name_offset: name_offset2, btf_type:btf_type2, offset:0 },
> ```

a few missing spaces after colons
___
*[`aya-obj/src/btf/types.rs` line 664 at r3](https://reviewable.io/reviews/aya-rs/aya/725#-NbJiRfX2fumEItBSkzB:-NbJiRfX2fumEItBSkzC:bb740dt) ([raw file](https://github.com/aya-rs/aya/blob/a9fbe1b66572d2e9e79b6b5981c72c6664f28f82/aya-obj/src/btf/types.rs#L664)):*
> ```XML
>     pub(crate) fn new(name_offset: u32, size: u32, members: Vec<BtfMember>) -> Self {
>         let info = (BtfKind::Union as u32) << 24;
>         Union {
> ```

Self


<!-- Sent from Reviewable.io -->

2023-08-09 11:51 UTC, dave-tucker commented
Parking this one until #731 lands to handle the comment re: mutate in place

2023-08-09 16:44 UTC, tamird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/725#-:-NbQAtX37vRh5V3l_8QM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dave-tucker)



<!-- Sent from Reviewable.io -->

2023-08-09 16:46 UTC, merged