bpf: Handle raw tracepoint arguments
aya-rs/aya pull request #805
Opened 2023-10-03 21:41 UTC by vadorovsky

Provide an `arg()` method in `RawTracepointArgs` wrapper of `bpf_raw_tracepoint_args` and also in `RawTracepointContext`, so it's directly available in raw tracepoint programs.

The methods and traits implemented here are unsafe. There is no way to reliably check the number of available arguments, so requesting a non-existing one leads to undefined behavior.

2023-10-07 17:36 UTC, tamird requested changes
LGTM though I don't know much about tracepoint.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/805#-:-NgACdSE8qBnb1pG_swZ:b-ujumcz)* status: all files reviewed, 7 unresolved discussions (waiting on @alessandrod and @vadorovsky)

___
*[`bpf/aya-bpf/src/args.rs` line 333 at r1](https://reviewable.io/reviews/aya-rs/aya/805#-NgAA9VL6xjm5B0qUy7N:-NgAA9VL6xjm5B0qUy7O:b-bqk34j) ([raw file](https://github.com/aya-rs/aya/blob/96ae8cdd97cca7cfc045cf0920b3193289d49e11/bpf/aya-bpf/src/args.rs#L333)):*
> ```XML
> 
> impl RawTracepointArgs {
>     pub fn new(args: *mut bpf_raw_tracepoint_args) -> Self {
> ```

doc comment?
___
*[`bpf/aya-bpf/src/args.rs` line 344 at r1](https://reviewable.io/reviews/aya-rs/aya/805#-NgAAxRlEj019n5ba9WC:-NgAAxRlEj019n5ba9WD:b-eu9ydf) ([raw file](https://github.com/aya-rs/aya/blob/96ae8cdd97cca7cfc045cf0920b3193289d49e11/bpf/aya-bpf/src/args.rs#L344)):*
> ```XML
>     /// about the structure of the `bpf_raw_tracepoint_args` type. The tracepoint arguments are
>     /// represented as an array of `__u64` values (i.e., `__u64 args[0]`), and this method
>     /// provides a way to access these arguments conveniently in Rust using `as_slice`.
> ```

here and everywhere, can you link to the specific method using [\`path::to::as_slice\`]? I'm struggling to understand what this is referring to.

EDIT: after some searching I see this is a wrapper in the generated bindings. it would be good to state that
___
*[`bpf/aya-bpf/src/args.rs` line 346 at r1](https://reviewable.io/reviews/aya-rs/aya/805#-NgAAMDY5YAjlk62OdUt:-NgAAMDY5YAjlk62OdUu:b-3jcqw4) ([raw file](https://github.com/aya-rs/aya/blob/96ae8cdd97cca7cfc045cf0920b3193289d49e11/bpf/aya-bpf/src/args.rs#L346)):*
> ```XML
>     /// provides a way to access these arguments conveniently in Rust using `as_slice`.
>     ///
>     /// However, the method does not check the total number of available arguments for a given
> ```

can you rephrase this to say that such a check is not possible? this may lead the reader to believe an improvement is possible
___
*[`test/integration-ebpf/src/raw_tracepoint.rs` line 18 at r1](https://reviewable.io/reviews/aya-rs/aya/805#-NgACT6V-Mp1U6UDHhur:-NgACT6V-Mp1U6UDHhus:b-1iy36x) ([raw file](https://github.com/aya-rs/aya/blob/96ae8cdd97cca7cfc045cf0920b3193289d49e11/test/integration-ebpf/src/raw_tracepoint.rs#L18)):*
> ```XML
>     pub common_type: u16,
>     pub common_flags: u8,
>     _padding: u8,
> ```

i think an earlier version of this PR had this in a common crate, is there a reason you went away from that?
___
*[`test/integration-test/src/tests/raw_tracepoint.rs` line 8 at r1](https://reviewable.io/reviews/aya-rs/aya/805#-NgACLMuDoQcYI5N2kdr:-NgACLMuDoQcYI5N2kds:b70lvzw) ([raw file](https://github.com/aya-rs/aya/blob/96ae8cdd97cca7cfc045cf0920b3193289d49e11/test/integration-test/src/tests/raw_tracepoint.rs#L8)):*
> ```XML
>     pub common_type: u16,
>     pub common_flags: u8,
>     _padding: u8,
> ```

how come this is needed manually?
___
*[`test/integration-test/src/tests/raw_tracepoint.rs` line 20 at r1](https://reviewable.io/reviews/aya-rs/aya/805#-NgACBuk3ornwhUNBL3r:-NgACBuk3ornwhUNBL3s:b9tru6d) ([raw file](https://github.com/aya-rs/aya/blob/96ae8cdd97cca7cfc045cf0920b3193289d49e11/test/integration-test/src/tests/raw_tracepoint.rs#L20)):*
> ```XML
>     prog.attach("sys_enter").unwrap();
> 
>     let map: Array<_, SysEnterEvent> = Array::try_from(bpf.map_mut("RESULT").unwrap()).unwrap();
> ```

is the idea that this makes a syscall? how do you know that a syscall will have happened between here and the assertion below?
___
*[`test/integration-test/src/tests/raw_tracepoint.rs` line 21 at r1](https://reviewable.io/reviews/aya-rs/aya/805#-NgACIOb97gVtaGmM932:-NgACIOb97gVtaGmM933:by3tfgn) ([raw file](https://github.com/aya-rs/aya/blob/96ae8cdd97cca7cfc045cf0920b3193289d49e11/test/integration-test/src/tests/raw_tracepoint.rs#L21)):*
> ```XML
> 
>     let map: Array<_, SysEnterEvent> = Array::try_from(bpf.map_mut("RESULT").unwrap()).unwrap();
>     let result = map.get(&0, 0).unwrap();
> ```

nit: destructure?


<!-- Sent from Reviewable.io -->

2023-10-10 14:46 UTC, vadorovsky commented
*[`test/integration-test/src/tests/raw_tracepoint.rs` line 20 at r1](https://reviewable.io/reviews/aya-rs/aya/805#-NgACBuk3ornwhUNBL3r:-NgP20Oo4VGOr7TTzeBM:b-ipje95) ([raw file](https://github.com/aya-rs/aya/blob/96ae8cdd97cca7cfc045cf0920b3193289d49e11/test/integration-test/src/tests/raw_tracepoint.rs#L20)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is the idea that this makes a syscall? how do you know that a syscall will have happened between here and the assertion below?
</blockquote></details>

There is always some syscall going on in the given moment, but actually, I think I should make it more reliable.

I can try writing a PID of the current process into a static variable and then using some syscall here, in the user-space test, then explicitly expect it in the program and then write to a map.


<!-- Sent from Reviewable.io -->

2023-10-10 14:49 UTC, vadorovsky commented
*[`test/integration-test/src/tests/raw_tracepoint.rs` line 8 at r1](https://reviewable.io/reviews/aya-rs/aya/805#-NgACLMuDoQcYI5N2kdr:-NgP2Ue32PYQ8WcaYBDa:b-l3a9oy) ([raw file](https://github.com/aya-rs/aya/blob/96ae8cdd97cca7cfc045cf0920b3193289d49e11/test/integration-test/src/tests/raw_tracepoint.rs#L8)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

how come this is needed manually?
</blockquote></details>

Because BPF verifier is expecting all the memory used to be initialized. When Rust compiler adds extra bytes for alignment, those extra bytes are uninitialized, which often triggers verifier errors. See (ctrl+f "Alignment, padding and verifier errors"):

https://deploy-preview-93--aya-rs.netlify.app/book/start/getting-data-to-user-space/#sharing-data


<!-- Sent from Reviewable.io -->

2023-10-10 15:30 UTC, tamird requested changes
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/805)* status: all files reviewed, 7 unresolved discussions (waiting on @alessandrod and @vadorovsky)

___
*[`test/integration-test/src/tests/raw_tracepoint.rs` line 8 at r1](https://reviewable.io/reviews/aya-rs/aya/805#-NgACLMuDoQcYI5N2kdr:-NgPC9vo9Om1BdYdhi6-:b-b0ygja) ([raw file](https://github.com/aya-rs/aya/blob/96ae8cdd97cca7cfc045cf0920b3193289d49e11/test/integration-test/src/tests/raw_tracepoint.rs#L8)):*
<details><summary><i>Previously, vadorovsky wrote…</i></summary><blockquote>

Because BPF verifier is expecting all the memory used to be initialized. When Rust compiler adds extra bytes for alignment, those extra bytes are uninitialized, which often triggers verifier errors. See (ctrl+f "Alignment, padding and verifier errors"):

https://deploy-preview-93--aya-rs.netlify.app/book/start/getting-data-to-user-space/#sharing-data
</blockquote></details>

Ack, can you leave a small comment?
___
*[`test/integration-test/src/tests/raw_tracepoint.rs` line 20 at r1](https://reviewable.io/reviews/aya-rs/aya/805#-NgACBuk3ornwhUNBL3r:-NgPCJpn-VU2g1MLMF4D:b6dbvga) ([raw file](https://github.com/aya-rs/aya/blob/96ae8cdd97cca7cfc045cf0920b3193289d49e11/test/integration-test/src/tests/raw_tracepoint.rs#L20)):*
<details><summary><i>Previously, vadorovsky wrote…</i></summary><blockquote>

There is always some syscall going on in the given moment, but actually, I think I should make it more reliable.

I can try writing a PID of the current process into a static variable and then using some syscall here, in the user-space test, then explicitly expect it in the program and then write to a map.
</blockquote></details>

More reliable seems good.


<!-- Sent from Reviewable.io -->

2024-11-21 14:46 UTC, tamird reviewed
> Reviewed 1 of 9 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 11 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/805)* status: 11 of 13 files reviewed, 4 unresolved discussions (waiting on @alessandrod and @vadorovsky)



<!-- Sent from Reviewable.io -->

2024-12-01 21:28 UTC, tamird reviewed
> Reviewed 2 of 13 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/805)* status: all files reviewed, 1 unresolved discussion (waiting on @alessandrod and @vadorovsky)



<!-- Sent from Reviewable.io -->

2025-01-07 16:50 UTC, tamird reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/805)* status: 12 of 14 files reviewed, all discussions resolved (waiting on @alessandrod)

___
*[`test/integration-test/src/tests/raw_tracepoint.rs` line 20 at r1](https://reviewable.io/reviews/aya-rs/aya/805#-NgACBuk3ornwhUNBL3r:-OG0f6tj62rfXsD3iYnx:b-sdkd3i) ([raw file](https://github.com/aya-rs/aya/blob/96ae8cdd97cca7cfc045cf0920b3193289d49e11/test/integration-test/src/tests/raw_tracepoint.rs#L20)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

More reliable seems good.
</blockquote></details>

Alright, I think this is fine here. I made this ever so slightly more robust and I'll merge it when CI passes.


<!-- Sent from Reviewable.io -->

2025-01-07 16:50 UTC, tamird approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/805)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alessandrod)



<!-- Sent from Reviewable.io -->

2025-01-07 16:52 UTC, vadorovsky commented
Awesome, TYSM

2025-01-07 17:27 UTC, merged