aya: Add `bpf_map_delete_elem` for `XskMap`
aya-rs/aya pull request #848
Opened 2023-12-06 21:01 UTC by arctic-alpaca

Add `clear_index()` to be able to use `bpf_map_delete_elem` for `XskMap`. Test is added to the existing af_xdp integration test.

2023-12-12 10:46 UTC, dave-tucker requested changes
One small nit and one API related query for @alessandrod:

For eBPF maps that have are array-like we expose `get` and `set`.
For eBPF maps that have are hashmap-like we expose `get`, `insert` and `remove`.

Since BPF_MAP_TYPE_ARRAY doesn't support bpf_map_delete_elem we never implemented it, so there is no precedent set for naming.

Would you go with, `delete`, `remove` or `clear`?

2023-12-12 10:46 UTC, dave-tucker commented on aya/src/maps/xdp/xsk_map.rs
> +    /// if `bpf_map_update_elem` fails.
```suggestion
    /// if `bpf_map_delete_elem` fails.
```

2023-12-12 10:46 UTC, dave-tucker commented on aya/src/maps/xdp/xsk_map.rs
> +    pub fn clear_index(&mut self, index: u32) -> Result<(), MapError> {
This should likely be either `remove` or `delete`. Hold please while we hear from @alessandrod.

2024-12-05 19:44 UTC, arctic-alpaca commented
@alessandrod Could you take a look this please? Without the function, it's not possible (as far as I know) to clean up a single AF_XDP socket without detaching/unloading the whole program.

2025-03-04 22:54 UTC, alessandrod commented on aya/src/maps/xdp/xsk_map.rs
> +    pub fn clear_index(&mut self, index: u32) -> Result<(), MapError> {
My thinking:

XskMap is fixed side - if you call map.len() you get `max_entries`.  So calling it `remove(index)` would be weird because len() before and after remove() is unchanged - so it doesn't remove?

I think this is why originally I suggested clear_index. Could also be unset()? I'm not really sure.

2025-03-05 12:13 UTC, dave-tucker approved these changes

2025-03-05 18:22 UTC, tamird commented
I've changed this to `unset` to match `set`. Assuming this looks good to everyone, let's merge it?

2025-03-05 20:34 UTC, merged