integration-test: Prefer system-wide lld over rust-lld
aya-rs/aya pull request #908
Opened 2024-03-13 19:35 UTC by vadorovsky

rust-lld is unaware of system libraries and seems like there is no way to point it to them. That often triggers issues like:

```
cargo:warning=error: linking with `rust-lld` failed: exit status: 1ger, ppv-lite86, libc...
cargo:warning=  |
cargo:warning=  = note: LC_ALL="C" PATH="/home/vadorovsky/.rustup/toolchains/stable-x86_64-un
cargo:warning=  = note: rust-lld: error: unable to find library -lgcc_s
cargo:warning=          rust-lld: error: unable to find library -lc
cargo:warning=
cargo:warning=
cargo:warning=
cargo:warning=error: aborting due to 1 previous error
```

Using system-wide LLD makes the issue disappear.

Fixes #907

2024-04-07 10:38 UTC, tamird approved these changes

2024-10-08 07:45 UTC, vadorovsky commented
> Is this no longer necessary?

I would say it's still necessary. I'm still facing the same issue when I'm building integration tests on any musl-based system.

I asked Rust community about that here https://github.com/rust-lang/rust/issues/130062 and the conclusion is basically:

"you're supposed to use the C compiler driver as the linker, as it knows where to find these libraries"

It's still a mystery for me why `-C linker=rust-lld` doesn't face the same issue on Ubuntu and I'm only able to reproduce that on Alpine and Gentoo(musl-llvm), but their explanation makes sense. I ended working around this issue on my side with custom RUSTFLAGS (`-C linker=clang -C link-arg=-fuse-ld=lld`).

Let me rebase it. The red builds are still the old ones from September, unrelated to the PR itself.

2024-10-08 07:47 UTC, vadorovsky commented
On a side note, Rust nightly is currently using rust-lld by default (but still through the system C compiler which figures out the paths). If they decide to ship that in any stable version, I believe we won't have to touch any RUSTFLAGS here.

2024-10-08 10:13 UTC, vadorovsky commented
Ubuntu fails now because of old clang. I also noticed just now that we are entering the `if let Some(target)` statement even for native builds, when running integration tests...

Taking a step back, I'm starting to doubt whether we should mangle with the linkers and linker flags at all at this place. Our [default cargo configuration specifies the cross gcc wrappers as linkers](https://github.com/aya-rs/aya/blob/main/.cargo/config.toml), which should be good enough for Ubuntu/Debian/Fedora users even for cross-compilation scenarios. People wanting to link with clang+lld could just define their own RUSTFLAGS. I will give it a try now, but not touching the flags is going to work both on Ubuntu and macOS, then I think that would be a solution.

2024-10-09 14:28 UTC, tamird commented
> Ubuntu fails now because of old clang. I also noticed just now that we are entering the `if let Some(target)` statement even for native builds, when running integration tests...

That doesn't sound right. Are you sure?

> Taking a step back, I'm starting to doubt whether we should mangle with the linkers and linker flags at all in this place. Our [default cargo configuration specifies the cross gcc wrappers as linkers](https://github.com/aya-rs/aya/blob/main/.cargo/config.toml), which should be good enough for Ubuntu/Debian/Fedora users even for cross-compilation scenarios. People wanting to link with clang+lld could just define their own RUSTFLAGS (at least I'm fine with doing that,). I will give it a try now, but if not touching the flags is going to work both on Ubuntu and macOS, then I think that would be a solution.

How is `aarch64-linux-musl-gcc` going to work for someone running on macOS? I believe I added that for exactly this reason.

2024-10-09 17:15 UTC, tamird commented
Thanks for the detail. Let's give it a shot. Can we add a CI job that verifies that everything works as expected?

2024-11-21 14:57 UTC, tamird requested changes
> Reviewed 1 of 1 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/908)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @vadorovsky)

___
*[`.github/workflows/ci.yml` line 192 at r2](https://reviewable.io/reviews/aya-rs/aya/908#-OCEDKyHD8gQpWCGUe4a:-OCEDKyHD8gQpWCGUe4b:btm4tpu) ([raw file](https://github.com/aya-rs/aya/blob/ae94156e2a40c93d997fc30a8cdfe26e880fd01c/.github/workflows/ci.yml#L192)):*
> ```YAML
>     steps:
>       - name: Log in to GHCR
>         run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
> ```

is there a reason we can't use github actions' "native" syntax for docker actions? https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-docker-container-action#creating-an-action-metadata-file
___
*[`.github/workflows/ci.yml` line 274 at r2](https://reviewable.io/reviews/aya-rs/aya/908#-OCECmMyBLLB7Sf7dSIG:-OCECmMyBLLB7Sf7dSIH:b-r6655n) ([raw file](https://github.com/aya-rs/aya/blob/ae94156e2a40c93d997fc30a8cdfe26e880fd01c/.github/workflows/ci.yml#L274)):*
> ```YAML
>       - name: Install prerequisites
>         if: runner.os == 'Linux' && contains(matrix.container, 'alpine')
>         # Use clang for building the C eBPF programs for integration tests.
> ```

can we document each dep please as we do above?
___
*[`xtask/src/run.rs` line 63 at r1](https://reviewable.io/reviews/aya-rs/aya/908#-OCEBvuwEK40UN7QvXpj:-OCEBvuwEK40UN7QvXpk:bavj3wf) ([raw file](https://github.com/aya-rs/aya/blob/89098e316c56cde0ddbb00e6ca53be2d725d7754/xtask/src/run.rs#L63)):*
> ```XML
>         cmd.args(["--target", target]);
>         // Always use rust-lld on macOS hosts. See
>         // https://github.com/aya-rs/aya/pull/908#issuecomment-2402813711
> ```

let's not do this. please write a sensible explanation here; don't make me go to a (mutable) comment in github


<!-- Sent from Reviewable.io -->

2024-11-27 11:54 UTC, vadorovsky reviewed
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/908)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @tamird)

___
*[`.github/workflows/ci.yml` line 192 at r2](https://reviewable.io/reviews/aya-rs/aya/908#-OCEDKyHD8gQpWCGUe4a:-OChT-UQCvwBVSO6NcIb:b-gnmbjf) ([raw file](https://github.com/aya-rs/aya/blob/ae94156e2a40c93d997fc30a8cdfe26e880fd01c/.github/workflows/ci.yml#L192)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is there a reason we can't use github actions' "native" syntax for docker actions? https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-docker-container-action#creating-an-action-metadata-file
</blockquote></details>

I removed the custom image all together. I left a comment, but tl;dr - runners don't support running containers with regular users, because of host mounts owned by root.
___
*[`.github/workflows/ci.yml` line 274 at r2](https://reviewable.io/reviews/aya-rs/aya/908#-OCECmMyBLLB7Sf7dSIG:-OChTFQo06gxq4fM-J1n:bb7f2mf) ([raw file](https://github.com/aya-rs/aya/blob/ae94156e2a40c93d997fc30a8cdfe26e880fd01c/.github/workflows/ci.yml#L274)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can we document each dep please as we do above?
</blockquote></details>

done
___
*[`xtask/src/run.rs` line 63 at r1](https://reviewable.io/reviews/aya-rs/aya/908#-OCEBvuwEK40UN7QvXpj:-OChTHiFCmdlnNNqJjbp:b-oo7l51) ([raw file](https://github.com/aya-rs/aya/blob/89098e316c56cde0ddbb00e6ca53be2d725d7754/xtask/src/run.rs#L63)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

let's not do this. please write a sensible explanation here; don't make me go to a (mutable) comment in github
</blockquote></details>

fair, what about now?


<!-- Sent from Reviewable.io -->

2024-11-27 16:41 UTC, tamird requested changes
> Reviewed 2 of 2 files at r5, 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aya-rs/aya/908)* status: all files reviewed, 7 unresolved discussions (waiting on @vadorovsky)

___
*[`xtask/src/run.rs` line 76 at r5](https://reviewable.io/reviews/aya-rs/aya/908#-OCiSiFM6uxUI80BlYV9:-OCiSiFM6uxUI80BlYVA:b-gmg0ah) ([raw file](https://github.com/aya-rs/aya/blob/613aaf8d7ad42e8d5bffbf0ee8e84b99a43052fe/xtask/src/run.rs#L76)):*
> ```XML
>         // linker (like ldd or mold) can be done with `-C link-arg=-fuse-ld=`.
>         //
>         // However, the same doesn't hold true for macOS. Cross toolchains for
> ```

i'm not i understand how this works. if we were compiling for linux-gnu instead of linux-musl i think we'd still have a problem, no?

in other words i think this is a property of musl vs gcc rather than the host being mac vs linux, but i haven't tested it. how sure are you?
___
*[`.github/workflows/ci.yml` line 209 at r9](https://reviewable.io/reviews/aya-rs/aya/908#-OCiTWjQ22yrxR1QhWnu:-OCiTWjQ22yrxR1QhWnv:b-trjmyx) ([raw file](https://github.com/aya-rs/aya/blob/9e1d8b4cf97a9acd10b1dcd1769f370358fc62db/.github/workflows/ci.yml#L209)):*
> ```YAML
>             container:
>               image: docker.io/alpine:3.20
>               options: --privileged -v /sys/fs/bpf:/sys/fs/bpf -v /sys/kernel:/sys/kernel
> ```

can you use the `volumes` attribute?

```yaml
      volumes:
        - my_docker_volume:/volume_mount
```

https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/running-jobs-in-a-container
___
*[`.github/workflows/ci.yml` line 230 at r9](https://reviewable.io/reviews/aya-rs/aya/908#-OCiTsey6yBrmYVToJWr:-OCiTsey6yBrmYVToJWs:b-umqkrt) ([raw file](https://github.com/aya-rs/aya/blob/9e1d8b4cf97a9acd10b1dcd1769f370358fc62db/.github/workflows/ci.yml#L230)):*
> ```YAML
>         # git is needed for the `checkout` action.
>         #
>         # libstdc++ is a dependency of llvm-sys, which is a dependency of
> ```

nit: libstdc++-dev, no?
___
*[`.github/workflows/ci.yml` line 285 at r9](https://reviewable.io/reviews/aya-rs/aya/908#-OCiUcVZ3-apukD6nI6v:-OCiUcVZ3-apukD6nI6w:b-x6u3c3) ([raw file](https://github.com/aya-rs/aya/blob/9e1d8b4cf97a9acd10b1dcd1769f370358fc62db/.github/workflows/ci.yml#L285)):*
> ```YAML
>       # fatal: detected dubious ownership in repository at '/__w/aya/aya'
>       #
>       # Which makes a lot of sense, not running regular git commands as root is
> ```

i think this isn't about running git as root, it's about git noticing that you're in a repo that isn't owned by you
___
*[`.github/workflows/ci.yml` line 287 at r9](https://reviewable.io/reviews/aya-rs/aya/908#-OCiUigNB54EU1B29y9t:-OCiUigNB54EU1B29y9u:b-t4oy86) ([raw file](https://github.com/aya-rs/aya/blob/9e1d8b4cf97a9acd10b1dcd1769f370358fc62db/.github/workflows/ci.yml#L287)):*
> ```YAML
>       # Which makes a lot of sense, not running regular git commands as root is
>       # a good thing. However, using a container image with a regular user
>       # results in permission errors thrown by the runner binary.[0] It's most
> ```

this should be on the `--privileged` option way up on the container settings

could we just not run the BPF iterator tests if we notice we're in a container? That would also allow you to ditch the previous commit but the big win is not running as root
___
*[`.github/workflows/ci.yml` line 295 at r9](https://reviewable.io/reviews/aya-rs/aya/908#-OCiU32J0Q4d6JyZxcwD:-OCiU32J0Q4d6JyZxcwE:b-agr4w8) ([raw file](https://github.com/aya-rs/aya/blob/9e1d8b4cf97a9acd10b1dcd1769f370358fc62db/.github/workflows/ci.yml#L295)):*
> ```YAML
>       - name: Mark the directory as safe for git
>         if: matrix.container != ''
>         run: git config --global --add safe.directory /__w/aya/aya
> ```

can we avoid using __w? isn't there a github root thing we can read?
___
*[`test/integration-test/src/tests/iter.rs` line 23 at r8](https://reviewable.io/reviews/aya-rs/aya/908#-OCiT627AqcQxS40v6fe:-OCiT627AqcQxS40v6ff:b-kuwgji) ([raw file](https://github.com/aya-rs/aya/blob/a77399393b04634cc289b676a63711c5816e46e9/test/integration-test/src/tests/iter.rs#L23)):*
> ```XML
> 
>     assert_eq!(line_title, "tgid     pid      name");
>     // It's hard to predict what's the PID of the first process in a container.
> ```

can we make the assertion agnostic to the pid number but still check it? e.g. we could split each line on whitespace and assert we find init or systemd?


<!-- Sent from Reviewable.io -->

2025-03-26 21:01 UTC, dave-tucker commented
Closing as fixed via #1160. Feel free to rebase and re-open if you'd like to bring in the alpine test in CI to avoid regressions.

2025-03-26 21:01 UTC, closed without merging