xtask: Generate new bindings
aya-rs/aya pull request #919
Opened 2024-04-02 22:34 UTC by kevinji

libbpf is bumped to [v1.4.0](https://github.com/libbpf/libbpf/releases/tag/v1.4.0) and new bindings are generated via `cargo +nightly xtask codegen`.

2024-04-03 06:32 UTC, vadorovsky requested changes
Thanks for the PR! :pray: It seems like you need to run `cargo xtask public-api --bless`. Could you add the `public-api` changes (in a separate commit)?

2024-04-03 07:50 UTC, kevinji commented
@vadorovsky Should be done; let me know if you see any issues.

2024-04-03 19:25 UTC, kevinji commented
I rebased my changes to pick up af1a9b39112a8341ef049c8697bed3350e76f2f1, so that should fix the lint issue that was showing up.

2024-04-04 09:51 UTC, vadorovsky approved these changes

2024-04-04 09:52 UTC, merged